/// <reference types="cypress" />
// When a customer is logged in
describe('Login', () => {
    beforeEach(() => {
        cy.visit("https://giveblockchain.io/givers/")
        cy.url()
            .should("include", "/givers/")   
    })

    // it('Expecting/Asserting all text on page', () => {
    //     cy.get('h1').should(($h1) => {
    //         expect($h1.eq(0), 'H2 First Title').to.contain("Givers")
    //     }) 

    //     cy.get('h2').should(($h2) => {
    //         expect($h2.eq(0), 'H2 First Title').to.contain("GIVE TO YOUR GIVER")
    //         expect($h2.eq(1), 'H2 Second Title').to.contain("THE GIVERS")
    //         expect($h2.eq(2), 'H2 Second Title').to.contain("Are you ready to")
    //     }) 

    //     cy.get('h3').should(($h3) => {
    //         expect($h3.eq(0), 'H3 First Title').to.contain('Free A Girl')
    //         expect($h3.eq(1), 'H3 Second Title').to.contain("Free A Girl")
    //         expect($h3.eq(2), 'H3 Second Title').to.contain("WHOLives")
    //         expect($h3.eq(3), 'H3 Second Title').to.contain("ROAM Humanitarian")
    //     }) 
        
    //     cy.get('h4').should(($givers_title) => {
    //         expect($givers_title.eq(0), 'First title text')
    //             .to.contain("Sponsoring:")
    //         expect($givers_title.eq(1), 'First title text')
    //             .to.contain("FREE A GIRL")
    //         expect($givers_title.eq(2), 'Second title text')
    //             .to.contain("WHOLives")
    //         expect($givers_title.eq(3), 'Third title text')
    //             .to.contain("ROAM HUMANITARIAN")
    //     }) 

    //     cy.get('h5').should(($h5) => {
    //         expect($h5.eq(0), 'First title text')
    //             .to.contain("Our core mission provides a conduit for doing good around the globe by supporting the extraordinary individuals who give everything to their organizations and projects they have founded.")
    //         expect($h5.eq(1), 'Second title text')
    //             .to.contain("Your contribution ensures that those giving of their time and talents will continue to have the resources needed in their own lives to continue the work they are doing to create positive changes.")
    //         expect($h5.eq(2), 'Third title text')
    //             .to.contain("Give to Evelien Hölsken")
    //         expect($h5.eq(3), 'Fourth title text')
    //             .to.contain("Give to Arjan Erkel")
    //         expect($h5.eq(4), 'Fourth title text')
    //             .to.contain("Give to John Renouard")
    //         expect($h5.eq(5), 'Fourth title text')
    //             .to.contain("Give to Justin & Lindsay Bowen")
    //     }) 

    //     cy.get('h6').should(($h6) => {
    //         expect($h6.eq(0), 'First title text')
    //             .to.contain("(Co) Founder Free a Girl")
    //         expect($h6.eq(1), 'Second title text')
    //             .to.contain("(Co) Founder Free A Girl")
    //         expect($h6.eq(2), 'Third title text')
    //             .to.contain("Founder, Director WHOLives")
    //         expect($h6.eq(3), 'Fourth title text')
    //             .to.contain("Founders ROAM Humanitarian")
    //     }) 

    //     cy.get('p').should(($para) => {
    //         expect($para.eq(0), 'First paragraph text')
    //             .to.contain("Back in 2006, I read in a newspaper article that children in India were being kidnapped, imprisoned in cages, and raped by adult men multiple times a day. My stomach literally turned; first I was distressed, then I became angry. Someone had to do something about this! At that moment, standing there with the article in my hand, I realized that I could be that person. It took a few years, but by July 2008, Free a Girl was a fact. Starting from an attic room with a distant goal on the horizon, I worked tirelessly by drawing on strength, by having a goal, and by believing that the universe always cooperates if you believe in the solution, rather than just focus on the problem.")
    //         expect($para.eq(1), 'Second paragraph text')
    //             .to.contain("My solution took me to co-found Free A Girl with Arjan Erkel. And our fight continues as we speak up for all children who are in a situation of sexual exploitation, to free them, heal them, love them, and empower them. I will work to make sure that society protects them and put an end to child exploitation. This starts with breaking the silence and putting every perpetrator behind bars. My fight will continue until we free the last girl.")            
    //         expect($para.eq(2), 'Third paragraph text')
    //             .to.contain("She is not a drop in the ocean, she is the entire ocean in one drop…")            
    //         expect($para.eq(3), 'Fourth paragraph text')
    //             .to.contain("Evelien Hölsken")           
    //         expect($para.eq(4), 'Fifth paragraph text')
    //             .to.contain("When I first heard the horrible stories about sexual exploitation of children I immediately felt this I needed to fight for this cause. I stood up and made sure the problem of sexual exploitation of children was addressed on national tv and lots of money was raised to support this cause. I felt connected because of an episode in my life where I was taken hostage during my work for Doctors without Borders in Dagestan. For 607 days armed rebels wearing masks kept me against my free will and took away my freedom. Every day for 20 months I hoped that someone was going to safe my life and get me out of my cage under the ground. Luckily, after all the pain and misery, I was released. I will never forget the smiles and hugs of my parents when I first met them. Other people stood up for me and made sure I got a second chance.")            
    //         expect($para.eq(5), 'Sixth paragraph text')
    //             .to.contain("I am deeply grateful that I got a second chance and want to use my ordeal to make sure to give as many second chances to children who need it the most. That is why in 2008 I co-founded Free a Girl with Evelien Holsken, to fight the trafficking and sexual abuse of minor girls. These evils must stop. Children are supposed to play and feel like a child and not to be abused. We need to free them, and we need to reunite them with their families; We need to protect children and we need to bring human trafficking to an end.")            
    //         expect($para.eq(6), 'Seventh paragraph text')
    //             .to.contain("“Those who deny freedom to others, deserve it not for themselves.”")            
    //         expect($para.eq(7), 'Eigth paragraph text')
    //             .to.contain("Arjan Erkel")            
    //         expect($para.eq(8), 'Ninth paragraph text')
    //             .to.contain("In 2010 John Renouard and his wife Nicci took their family on a humanitarian vacation to Africa. After seeing the devastating water poverty in Africa, John’s reaction was not one of pity, but rather a disbelief and some anger, that in 2010, so many people were still living at that extreme level of abject poverty. Upon returning home from Africa, John went to work. It would revolve around a logical set of actions: If you solve the water crisis, by default you have also solved ½ of the health care issues, and with clean water and better health you can now grow opportunities. So, there it was, Water, Health and Opportunity; and using this acronym, John founded WHOlives.org.")            
    //         expect($para.eq(9), 'Tenth paragraph text')
    //             .to.contain("Partnering with student engineers at BYU, John developed his idea of a human-powered drill, called the Village Drill, that can access clean, disease-free water up to 250 deep. WhoLives started with 40 drills in 15 developing countries in 2015 and suddenly over 250,000 people had access to clean water. John’s vision included his philosophy to empower local people, to create opportunity, and not more dependency. Today there are 115 Village Drills in 37 countries with over 8,500 wells bringing clean water to over 8 million people in need. Recognized for his innovation and hard work, John was awarded the ‘International Hero’ award by the Red Cross. Most recently, WHOlives and the Village Drill won the ‘2021 International World Water Challenge’ held in South Korea, with entries from 136 countries.")            
    //         expect($para.eq(10), 'Eleventh paragraph text')
    //             .to.contain("John Renouard")
    //         expect($para.eq(11), 'Twelve paragraph text')
    //             .to.contain("We are Justin and Lindsay Bowen. We are the heart behind ROAM Humanitarian. We are committed to creating lasting and positive change in both our expedition participants and those whom we serve throughout the world. We believe in making a difference to the one, whether that is you as the participant or the ones we serve. We may not change the world, but we believe we can change the world of an individual one smile, one project, and one expedition at a time. We consider it our privilege to work alongside you and become change-makers while we ROAM with purpose together.")
    //         expect($para.eq(12), 'Thirteenth paragraph text')
    //             .to.contain("Together, we believe we have the secret sauce that creates the magic behind each ROAM Humanitarian expedition. We are just as interested in building homes, gardens, and schools as we are in creating opportunities that build you and your family relationships.")
    //         expect($para.eq(13), 'Fourteenth paragraph text')
    //             .to.contain("Come as you are and join the ROAM family today! You are welcome here, and we can’t wait to share the adventures of a lifetime with you!")
    //         expect($para.eq(14), 'Fifteenth paragraph text')
    //             .to.contain("Justin and Lindsay Bowen")
    //         expect($para.eq(15), 'Sixteenth paragraph text')
    //             .to.contain("“We need to speak for all children who are in a situation of sexual exploitation. As we put an end to human trafficking, we need to free them, heal them, love them, and empower them.”")
    //         expect($para.eq(16), 'Seventeenth paragraph text')
    //             .to.contain("“Innovation and hard work have been the keys to making radical and positive changes and provide clean water to millions of people in need.”")
    //         expect($para.eq(17), 'Eighteenth paragraph text')
    //             .to.contain("“We believe in making a difference by creating lasting and positive changes to those who serve with us and those whom we serve.”")
    //         expect($para.eq(18), 'Nineteenth paragraph text')
    //             .to.contain("Contribute to Givers.")
    //     }) 

    //     cy.get('[class="nectar-button large regular has-icon regular-button"]').should(($button) => {
    //         expect($button.eq(0), 'First button text')
    //             .to.contain("GIVE NOW")
    //         expect($button.eq(1), 'Second button text')
    //             .to.contain("GIVE NOW")
    //         expect($button.eq(2), 'Second button text')
    //             .to.contain("GIVE NOW")
    //         expect($button.eq(3), 'Second button text')
    //             .to.contain("GIVE NOW")
    //         expect($button.eq(4), 'Second button text')
    //             .to.contain("GIVE NOW")
    //     }) 
    // })

    it('Expecting/Asserting for all button clicks that are active', () => {
        cy.get('[class="nectar-button large regular has-icon regular-button"]')
            .eq(0)
            .click()
        cy.url().should('include', "blockchain.io/givers-evelien-holsken/")
        cy.go('back')
        cy.get('[class="nectar-button large regular has-icon regular-button"]')
            .eq(1)
            .click()
        cy.url().should('include', "blockchain.io/givers-arjan-erkel/")
        cy.go('back')
        cy.get('[class="nectar-button large regular has-icon regular-button"]')
            .eq(2)
            .click()
        cy.url().should('include', "blockchain.io/givers-john-renouard/")
        cy.go('back')
        cy.get('[class="nectar-button large regular has-icon regular-button"]')
            .eq(3)
            .click()
        cy.url().should('include', "blockchain.io/givers-justin-lindsay-bowen/")
        cy.go('back')
        cy.get('[class="nectar-button large regular has-icon regular-button"]')
            .eq(4)
            .click()
        cy.url().should('include', "blockchain.io/givers/")
    })
})