/// <reference types="cypress" />

describe('Login', () => {
    beforeEach(() => {
        cy.visit("https://giveblockchain.io/")
        cy.url()
            .should('include', "giveblockchain")
        cy.get('[class="hover-wrap-inner img-loaded"]')
            .should('have.class', "hover-wrap-inner img-loaded")
        cy.wait(2000)
    })

    it('Document Test - iPhone-8-portrait', () => {
        cy.viewport('iphone-8', 'portrait')
        cy.get('[class="nectar-button jumbo see-through accent-color"]').should(($necton) => {
            //expect($necton).to.have.length(3)
            expect($necton.eq(0), 'first button').to.contain('Give')
            expect($necton.eq(1), 'second button').to.contain('Mission')
            expect($necton.eq(2), 'third button').to.contain('Blockchain')
            expect($necton.eq(3), 'fourth button').to.contain('Sign Up Free')
            expect($necton.eq(4), 'fifth button').to.contain('Login')
        }) 
        
        cy.get('[class="nectar-button jumbo see-through accent-color"]')
            .eq(0)
            .should('have.text', "Give")
            .should('have.attr', 'style', 'margin-right: 15px; margin-left: 15px; visibility: visible; color: rgb(255, 255, 255); border-color: rgba(255, 255, 255, 0.75);')
            .should('have.attr', 'href', "/give-information/")
            .click()
        cy.url()
            .should("include", "/give-information/")
        cy.get('h1').should(($h1) => {
            expect($h1, 'H1 Title').to.contain('Give')
            expect($h1, 'H1 Title').to.have.attr('style', "text-align: center")
        })
        cy.get('[class="starting-logo dark-version mobile-only-logo skip-lazy"]').click()

        cy.get('[class="nectar-button jumbo see-through accent-color"]')
            .eq(1)
            .should('have.text', "Mission")
            .should('have.attr', 'style', 'margin-right: 15px; margin-left: 15px; border-color: rgba(255, 255, 255, 0.75); color: rgb(255, 255, 255); visibility: visible;')
            .should('have.attr', 'href', "/mission-information/")
            .click()
        cy.url()
            .should("include", "/mission-information/")
        cy.get('h1').should(($h1) => {
            expect($h1, 'H1 Title').to.contain('We Can Make a Change')
        })
        cy.get('[class="starting-logo dark-version mobile-only-logo skip-lazy"]').click()

        cy.get('[class="nectar-button jumbo see-through accent-color"]')
            .eq(2)
            .should('have.text', "Blockchain")
            .should('have.attr', 'style', 'margin-right: 15px; margin-left: 15px; visibility: visible; color: rgb(255, 255, 255); border-color: rgba(255, 255, 255, 0.75);')
            .should('have.attr', 'href', "/give-node-information/")
            .click()
        cy.url()
            .should("include", "/give-node-information/")
        cy.get('h4').should(($h4) => {
            expect($h4, 'H4 Title').to.contain('Login to make purchases and give.')
            expect($h4, 'style assert').to.have.attr('style', "text-align: center;")
        }) 
        cy.get('[class="starting-logo dark-version mobile-only-logo skip-lazy"]').click()

        cy.get('[class="nectar-button jumbo see-through accent-color"]')
            .eq(3)
            .should('have.text', "Sign Up Free")
            .should('have.attr', 'style', 'margin-right: 15px; margin-left: 15px; visibility: visible; color: rgb(255, 255, 255); border-color: rgba(255, 255, 255, 0.75);')
            .should('have.attr', 'href', "/lets-give/")
            .click()
        cy.url()
            .should("include", "/lets-give/")
        cy.get('h5').should(($h5) => {
            expect($h5, 'H5 Title').to.contain("Join The Movement")
        }) 
        cy.go('back')

        cy.get('[class="nectar-button jumbo see-through accent-color"]')
            .eq(4)
            .should('have.text', "Login")
            .should('have.attr', 'style', 'margin-right: 15px; margin-left: 15px; visibility: visible; color: rgb(255, 255, 255); border-color: rgba(255, 255, 255, 0.75);')
            .should('have.attr', 'href', "/login/")
            .click()
        cy.url()
            .should("include", "/login/")
        cy.get('h5').should(($h5) => {
            expect($h5, 'H5 Title').to.contain("Login to access your account:")
        }) 
    })

    it('Document Test - iPhone-x-portrait', () => {
        cy.viewport('iphone-x', 'portrait')
        cy.get('[class="nectar-button jumbo see-through accent-color"]').should(($necton) => {
            //expect($necton).to.have.length(3)
            expect($necton.eq(0), 'first button').to.contain('Give')
            expect($necton.eq(1), 'second button').to.contain('Mission')
            expect($necton.eq(2), 'third button').to.contain('Blockchain')
            expect($necton.eq(3), 'fourth button').to.contain('Sign Up Free')
            expect($necton.eq(4), 'fifth button').to.contain('Login')
        }) 
        
        cy.get('[class="nectar-button jumbo see-through accent-color"]')
            .eq(0)
            .should('have.text', "Give")
            .should('have.attr', 'style', 'margin-right: 15px; margin-left: 15px; visibility: visible; color: rgb(255, 255, 255); border-color: rgba(255, 255, 255, 0.75);')
            .should('have.attr', 'href', "/give-information/")
            .click()
        cy.url()
            .should("include", "/give-information/")
        cy.get('h1').should(($h1) => {
            expect($h1, 'H1 Title').to.contain('Give')
            expect($h1, 'H1 Title').to.have.attr('style', "text-align: center")
        })
        cy.get('[class="starting-logo dark-version mobile-only-logo skip-lazy"]').click()

        cy.get('[class="nectar-button jumbo see-through accent-color"]')
            .eq(1)
            .should('have.text', "Mission")
            .should('have.attr', 'style', 'margin-right: 15px; margin-left: 15px; border-color: rgba(255, 255, 255, 0.75); color: rgb(255, 255, 255); visibility: visible;')
            .should('have.attr', 'href', "/mission-information/")
            .click()
        cy.url()
            .should("include", "/mission-information/")
        cy.get('h1').should(($h1) => {
            expect($h1, 'H1 Title').to.contain('We Can Make a Change')
        })
        cy.get('[class="starting-logo dark-version mobile-only-logo skip-lazy"]').click()

        cy.get('[class="nectar-button jumbo see-through accent-color"]')
            .eq(2)
            .should('have.text', "Blockchain")
            .should('have.attr', 'style', 'margin-right: 15px; margin-left: 15px; visibility: visible; color: rgb(255, 255, 255); border-color: rgba(255, 255, 255, 0.75);')
            .should('have.attr', 'href', "/give-node-information/")
            .click()
        cy.url()
            .should("include", "/give-node-information/")
        cy.get('h4').should(($h4) => {
            expect($h4, 'H4 Title').to.contain('Login to make purchases and give.')
            expect($h4, 'style assert').to.have.attr('style', "text-align: center;")
        }) 
        cy.get('[class="starting-logo dark-version mobile-only-logo skip-lazy"]').click()

        cy.get('[class="nectar-button jumbo see-through accent-color"]')
            .eq(3)
            .should('have.text', "Sign Up Free")
            .should('have.attr', 'style', 'margin-right: 15px; margin-left: 15px; visibility: visible; color: rgb(255, 255, 255); border-color: rgba(255, 255, 255, 0.75);')
            .should('have.attr', 'href', "/lets-give/")
            .click()
        cy.url()
            .should("include", "/lets-give/")
        cy.get('h5').should(($h5) => {
            expect($h5, 'H5 Title').to.contain("Join The Movement")
        }) 
        cy.go('back')

        cy.get('[class="nectar-button jumbo see-through accent-color"]')
            .eq(4)
            .should('have.text', "Login")
            .should('have.attr', 'style', 'margin-right: 15px; margin-left: 15px; visibility: visible; color: rgb(255, 255, 255); border-color: rgba(255, 255, 255, 0.75);')
            .should('have.attr', 'href', "/login/")
            .click()
        cy.url()
            .should("include", "/login/")
        cy.get('h5').should(($h5) => {
            expect($h5, 'H5 Title').to.contain("Login to access your account:")
        }) 
    })

    it('Document Test - iPad-mini-landscape', () => {
        cy.viewport('ipad-mini', 'landscape')
        cy.get('[class="nectar-button jumbo see-through accent-color"]').should(($necton) => {
            //expect($necton).to.have.length(3)
            expect($necton.eq(0), 'first button').to.contain('Give')
            expect($necton.eq(1), 'second button').to.contain('Mission')
            expect($necton.eq(2), 'third button').to.contain('Blockchain')
            expect($necton.eq(3), 'fourth button').to.contain('Sign Up Free')
            expect($necton.eq(4), 'fifth button').to.contain('Login')
        }) 
        
        cy.get('[class="nectar-button jumbo see-through accent-color"]')
            .eq(0)
            .should('have.text', "Give")
            .should('have.attr', 'style', 'margin-right: 15px; margin-left: 15px; visibility: visible; color: rgb(255, 255, 255); border-color: rgba(255, 255, 255, 0.75);')
            .should('have.attr', 'href', "/give-information/")
            .click()
        cy.url()
            .should("include", "/give-information/")
        cy.get('h1').should(($h1) => {
            expect($h1, 'H1 Title').to.contain('Give')
            expect($h1, 'H1 Title').to.have.attr('style', "text-align: center")
        })
        cy.get('[class="starting-logo dark-version skip-lazy default-logo"]').click()

        cy.get('[class="nectar-button jumbo see-through accent-color"]')
            .eq(1)
            .should('have.text', "Mission")
            .should('have.attr', 'style', 'margin-right: 15px; margin-left: 15px; border-color: rgba(255, 255, 255, 0.75); color: rgb(255, 255, 255); visibility: visible;')
            .should('have.attr', 'href', "/mission-information/")
            .click()
        cy.url()
            .should("include", "/mission-information/")
        cy.get('h1').should(($h1) => {
            expect($h1, 'H1 Title').to.contain('We Can Make a Change')
        })
        cy.get('[class="starting-logo dark-version skip-lazy default-logo"]').click()

        cy.get('[class="nectar-button jumbo see-through accent-color"]')
            .eq(2)
            .should('have.text', "Blockchain")
            .should('have.attr', 'style', 'margin-right: 15px; margin-left: 15px; visibility: visible; color: rgb(255, 255, 255); border-color: rgba(255, 255, 255, 0.75);')
            .should('have.attr', 'href', "/give-node-information/")
            .click()
        cy.url()
            .should("include", "/give-node-information/")
        cy.get('h4').should(($h4) => {
            expect($h4, 'H4 Title').to.contain('Login to make purchases and give.')
            expect($h4, 'style assert').to.have.attr('style', "text-align: center;")
        }) 
        cy.get('[class="starting-logo dark-version skip-lazy default-logo"]').click()

        cy.get('[class="nectar-button jumbo see-through accent-color"]')
            .eq(3)
            .should('have.text', "Sign Up Free")
            .should('have.attr', 'style', 'margin-right: 15px; margin-left: 15px; visibility: visible; color: rgb(255, 255, 255); border-color: rgba(255, 255, 255, 0.75);')
            .should('have.attr', 'href', "/lets-give/")
            .click()
        cy.url()
            .should("include", "/lets-give/")
        cy.get('h5').should(($h5) => {
            expect($h5, 'H5 Title').to.contain("Join The Movement")
        }) 
        cy.go('back')

        cy.get('[class="nectar-button jumbo see-through accent-color"]')
            .eq(4)
            .should('have.text', "Login")
            .should('have.attr', 'style', 'margin-right: 15px; margin-left: 15px; visibility: visible; color: rgb(255, 255, 255); border-color: rgba(255, 255, 255, 0.75);')
            .should('have.attr', 'href', "/login/")
            .click()
        cy.url()
            .should("include", "/login/")
        cy.get('h5').should(($h5) => {
            expect($h5, 'H5 Title').to.contain("Login to access your account:")
        }) 
    })

    it('Document Test - iPad-2-landscape', () => {
        cy.viewport('ipad-2', 'landscape')
        cy.get('[class="nectar-button jumbo see-through accent-color"]').should(($necton) => {
            //expect($necton).to.have.length(3)
            expect($necton.eq(0), 'first button').to.contain('Give')
            expect($necton.eq(1), 'second button').to.contain('Mission')
            expect($necton.eq(2), 'third button').to.contain('Blockchain')
            expect($necton.eq(3), 'fourth button').to.contain('Sign Up Free')
            expect($necton.eq(4), 'fifth button').to.contain('Login')
        }) 
        
        cy.get('[class="nectar-button jumbo see-through accent-color"]')
            .eq(0)
            .should('have.text', "Give")
            .should('have.attr', 'style', 'margin-right: 15px; margin-left: 15px; visibility: visible; color: rgb(255, 255, 255); border-color: rgba(255, 255, 255, 0.75);')
            .should('have.attr', 'href', "/give-information/")
            .click()
        cy.url()
            .should("include", "/give-information/")
        cy.get('h1').should(($h1) => {
            expect($h1, 'H1 Title').to.contain('Give')
            expect($h1, 'H1 Title').to.have.attr('style', "text-align: center")
        })
        cy.get('[class="starting-logo dark-version skip-lazy default-logo"]').click()

        cy.get('[class="nectar-button jumbo see-through accent-color"]')
            .eq(1)
            .should('have.text', "Mission")
            .should('have.attr', 'style', 'margin-right: 15px; margin-left: 15px; border-color: rgba(255, 255, 255, 0.75); color: rgb(255, 255, 255); visibility: visible;')
            .should('have.attr', 'href', "/mission-information/")
            .click()
        cy.url()
            .should("include", "/mission-information/")
        cy.get('h1').should(($h1) => {
            expect($h1, 'H1 Title').to.contain('We Can Make a Change')
        })
        cy.get('[class="starting-logo dark-version skip-lazy default-logo"]').click()

        cy.get('[class="nectar-button jumbo see-through accent-color"]')
            .eq(2)
            .should('have.text', "Blockchain")
            .should('have.attr', 'style', 'margin-right: 15px; margin-left: 15px; visibility: visible; color: rgb(255, 255, 255); border-color: rgba(255, 255, 255, 0.75);')
            .should('have.attr', 'href', "/give-node-information/")
            .click()
        cy.url()
            .should("include", "/give-node-information/")
        cy.get('h4').should(($h4) => {
            expect($h4, 'H4 Title').to.contain('Login to make purchases and give.')
            expect($h4, 'style assert').to.have.attr('style', "text-align: center;")
        }) 
        cy.get('[class="starting-logo dark-version skip-lazy default-logo"]').click()

        cy.get('[class="nectar-button jumbo see-through accent-color"]')
            .eq(3)
            .should('have.text', "Sign Up Free")
            .should('have.attr', 'style', 'margin-right: 15px; margin-left: 15px; visibility: visible; color: rgb(255, 255, 255); border-color: rgba(255, 255, 255, 0.75);')
            .should('have.attr', 'href', "/lets-give/")
            .click()
        cy.url()
            .should("include", "/lets-give/")
        cy.get('h5').should(($h5) => {
            expect($h5, 'H5 Title').to.contain("Join The Movement")
        }) 
        cy.go('back')

        cy.get('[class="nectar-button jumbo see-through accent-color"]')
            .eq(4)
            .should('have.text', "Login")
            .should('have.attr', 'style', 'margin-right: 15px; margin-left: 15px; visibility: visible; color: rgb(255, 255, 255); border-color: rgba(255, 255, 255, 0.75);')
            .should('have.attr', 'href', "/login/")
            .click()
        cy.url()
            .should("include", "/login/")
        cy.get('h5').should(($h5) => {
            expect($h5, 'H5 Title').to.contain("Login to access your account:")
        }) 
    })

    it('Document Test - SamsungS10-portrait', () => {
        cy.viewport('samsung-s10', 'portrait')
        cy.get('[class="nectar-button jumbo see-through accent-color"]').should(($necton) => {
            //expect($necton).to.have.length(3)
            expect($necton.eq(0), 'first button').to.contain('Give')
            expect($necton.eq(1), 'second button').to.contain('Mission')
            expect($necton.eq(2), 'third button').to.contain('Blockchain')
            expect($necton.eq(3), 'fourth button').to.contain('Sign Up Free')
            expect($necton.eq(4), 'fifth button').to.contain('Login')
        }) 
        
        cy.get('[class="nectar-button jumbo see-through accent-color"]')
            .eq(0)
            .should('have.text', "Give")
            .should('have.attr', 'style', 'margin-right: 15px; margin-left: 15px; visibility: visible; color: rgb(255, 255, 255); border-color: rgba(255, 255, 255, 0.75);')
            .should('have.attr', 'href', "/give-information/")
            .click()
        cy.url()
            .should("include", "/give-information/")
        cy.get('h1').should(($h1) => {
            expect($h1, 'H1 Title').to.contain('Give')
            expect($h1, 'H1 Title').to.have.attr('style', "text-align: center")
        })
        cy.get('[class="starting-logo dark-version mobile-only-logo skip-lazy"]').click()

        cy.get('[class="nectar-button jumbo see-through accent-color"]')
            .eq(1)
            .should('have.text', "Mission")
            .should('have.attr', 'style', 'margin-right: 15px; margin-left: 15px; border-color: rgba(255, 255, 255, 0.75); color: rgb(255, 255, 255); visibility: visible;')
            .should('have.attr', 'href', "/mission-information/")
            .click()
        cy.url()
            .should("include", "/mission-information/")
        cy.get('h1').should(($h1) => {
            expect($h1, 'H1 Title').to.contain('We Can Make a Change')
        })
        cy.get('[class="starting-logo dark-version mobile-only-logo skip-lazy"]').click()

        cy.get('[class="nectar-button jumbo see-through accent-color"]')
            .eq(2)
            .should('have.text', "Blockchain")
            .should('have.attr', 'style', 'margin-right: 15px; margin-left: 15px; visibility: visible; color: rgb(255, 255, 255); border-color: rgba(255, 255, 255, 0.75);')
            .should('have.attr', 'href', "/give-node-information/")
            .click()
        cy.url()
            .should("include", "/give-node-information/")
        cy.get('h4').should(($h4) => {
            expect($h4, 'H4 Title').to.contain('Login to make purchases and give.')
            expect($h4, 'style assert').to.have.attr('style', "text-align: center;")
        }) 
        cy.get('[class="starting-logo dark-version mobile-only-logo skip-lazy"]').click()

        cy.get('[class="nectar-button jumbo see-through accent-color"]')
            .eq(3)
            .should('have.text', "Sign Up Free")
            .should('have.attr', 'style', 'margin-right: 15px; margin-left: 15px; visibility: visible; color: rgb(255, 255, 255); border-color: rgba(255, 255, 255, 0.75);')
            .should('have.attr', 'href', "/lets-give/")
            .click()
        cy.url()
            .should("include", "/lets-give/")
        cy.get('h5').should(($h5) => {
            expect($h5, 'H5 Title').to.contain("Join The Movement")
        }) 
        cy.go('back')

        cy.get('[class="nectar-button jumbo see-through accent-color"]')
            .eq(4)
            .should('have.text', "Login")
            .should('have.attr', 'style', 'margin-right: 15px; margin-left: 15px; visibility: visible; color: rgb(255, 255, 255); border-color: rgba(255, 255, 255, 0.75);')
            .should('have.attr', 'href', "/login/")
            .click()
        cy.url()
            .should("include", "/login/")
        cy.get('h5').should(($h5) => {
            expect($h5, 'H5 Title').to.contain("Login to access your account:")
        }) 
    })

    it('Document Test - Samsung-Note9-portrait', () => {
        cy.viewport('samsung-note9', 'portrait')
        cy.get('[class="nectar-button jumbo see-through accent-color"]').should(($necton) => {
            //expect($necton).to.have.length(3)
            expect($necton.eq(0), 'first button').to.contain('Give')
            expect($necton.eq(1), 'second button').to.contain('Mission')
            expect($necton.eq(2), 'third button').to.contain('Blockchain')
            expect($necton.eq(3), 'fourth button').to.contain('Sign Up Free')
            expect($necton.eq(4), 'fifth button').to.contain('Login')
        }) 
        
        cy.get('[class="nectar-button jumbo see-through accent-color"]')
            .eq(0)
            .should('have.text', "Give")
            .should('have.attr', 'style', 'margin-right: 15px; margin-left: 15px; visibility: visible; color: rgb(255, 255, 255); border-color: rgba(255, 255, 255, 0.75);')
            .should('have.attr', 'href', "/give-information/")
            .click()
        cy.url()
            .should("include", "/give-information/")
        cy.get('h1').should(($h1) => {
            expect($h1, 'H1 Title').to.contain('Give')
            expect($h1, 'H1 Title').to.have.attr('style', "text-align: center")
        })
        cy.get('[class="starting-logo dark-version mobile-only-logo skip-lazy"]').click()

        cy.get('[class="nectar-button jumbo see-through accent-color"]')
            .eq(1)
            .should('have.text', "Mission")
            .should('have.attr', 'style', 'margin-right: 15px; margin-left: 15px; border-color: rgba(255, 255, 255, 0.75); color: rgb(255, 255, 255); visibility: visible;')
            .should('have.attr', 'href', "/mission-information/")
            .click()
        cy.url()
            .should("include", "/mission-information/")
        cy.get('h1').should(($h1) => {
            expect($h1, 'H1 Title').to.contain('We Can Make a Change')
        })
        cy.get('[class="starting-logo dark-version mobile-only-logo skip-lazy"]').click()

        cy.get('[class="nectar-button jumbo see-through accent-color"]')
            .eq(2)
            .should('have.text', "Blockchain")
            .should('have.attr', 'style', 'margin-right: 15px; margin-left: 15px; visibility: visible; color: rgb(255, 255, 255); border-color: rgba(255, 255, 255, 0.75);')
            .should('have.attr', 'href', "/give-node-information/")
            .click()
        cy.url()
            .should("include", "/give-node-information/")
        cy.get('h4').should(($h4) => {
            expect($h4, 'H4 Title').to.contain('Login to make purchases and give.')
            expect($h4, 'style assert').to.have.attr('style', "text-align: center;")
        }) 
        cy.get('[class="starting-logo dark-version mobile-only-logo skip-lazy"]').click()

        cy.get('[class="nectar-button jumbo see-through accent-color"]')
            .eq(3)
            .should('have.text', "Sign Up Free")
            .should('have.attr', 'style', 'margin-right: 15px; margin-left: 15px; visibility: visible; color: rgb(255, 255, 255); border-color: rgba(255, 255, 255, 0.75);')
            .should('have.attr', 'href', "/lets-give/")
            .click()
        cy.url()
            .should("include", "/lets-give/")
        cy.get('h5').should(($h5) => {
            expect($h5, 'H5 Title').to.contain("Join The Movement")
        }) 
        cy.go('back')

        cy.get('[class="nectar-button jumbo see-through accent-color"]')
            .eq(4)
            .should('have.text', "Login")
            .should('have.attr', 'style', 'margin-right: 15px; margin-left: 15px; visibility: visible; color: rgb(255, 255, 255); border-color: rgba(255, 255, 255, 0.75);')
            .should('have.attr', 'href', "/login/")
            .click()
        cy.url()
            .should("include", "/login/")
        cy.get('h5').should(($h5) => {
            expect($h5, 'H5 Title').to.contain("Login to access your account:")
        }) 
    })

    it('Document Test - iPhone12-portrait', () => {
        cy.viewport(390,844, 'portrait')
        cy.get('[class="nectar-button jumbo see-through accent-color"]').should(($necton) => {
            //expect($necton).to.have.length(3)
            expect($necton.eq(0), 'first button').to.contain('Give')
            expect($necton.eq(1), 'second button').to.contain('Mission')
            expect($necton.eq(2), 'third button').to.contain('Blockchain')
            expect($necton.eq(3), 'fourth button').to.contain('Sign Up Free')
            expect($necton.eq(4), 'fifth button').to.contain('Login')
        }) 
        
        cy.get('[class="nectar-button jumbo see-through accent-color"]')
            .eq(0)
            .should('have.text', "Give")
            .should('have.attr', 'style', 'margin-right: 15px; margin-left: 15px; visibility: visible; color: rgb(255, 255, 255); border-color: rgba(255, 255, 255, 0.75);')
            .should('have.attr', 'href', "/give-information/")
            .click()
        cy.url()
            .should("include", "/give-information/")
        cy.get('h1').should(($h1) => {
            expect($h1, 'H1 Title').to.contain('Give')
            expect($h1, 'H1 Title').to.have.attr('style', "text-align: center")
        })
        cy.get('[class="starting-logo dark-version mobile-only-logo skip-lazy"]').click()

        cy.get('[class="nectar-button jumbo see-through accent-color"]')
            .eq(1)
            .should('have.text', "Mission")
            .should('have.attr', 'style', 'margin-right: 15px; margin-left: 15px; border-color: rgba(255, 255, 255, 0.75); color: rgb(255, 255, 255); visibility: visible;')
            .should('have.attr', 'href', "/mission-information/")
            .click()
        cy.url()
            .should("include", "/mission-information/")
        cy.get('h1').should(($h1) => {
            expect($h1, 'H1 Title').to.contain('We Can Make a Change')
        })
        cy.get('[class="starting-logo dark-version mobile-only-logo skip-lazy"]').click()

        cy.get('[class="nectar-button jumbo see-through accent-color"]')
            .eq(2)
            .should('have.text', "Blockchain")
            .should('have.attr', 'style', 'margin-right: 15px; margin-left: 15px; visibility: visible; color: rgb(255, 255, 255); border-color: rgba(255, 255, 255, 0.75);')
            .should('have.attr', 'href', "/give-node-information/")
            .click()
        cy.url()
            .should("include", "/give-node-information/")
        cy.get('h4').should(($h4) => {
            expect($h4, 'H4 Title').to.contain('Login to make purchases and give.')
            expect($h4, 'style assert').to.have.attr('style', "text-align: center;")
        }) 
        cy.get('[class="starting-logo dark-version mobile-only-logo skip-lazy"]').click()

        cy.get('[class="nectar-button jumbo see-through accent-color"]')
            .eq(3)
            .should('have.text', "Sign Up Free")
            .should('have.attr', 'style', 'margin-right: 15px; margin-left: 15px; visibility: visible; color: rgb(255, 255, 255); border-color: rgba(255, 255, 255, 0.75);')
            .should('have.attr', 'href', "/lets-give/")
            .click()
        cy.url()
            .should("include", "/lets-give/")
        cy.get('h5').should(($h5) => {
            expect($h5, 'H5 Title').to.contain("Join The Movement")
        }) 
        cy.go('back')

        cy.get('[class="nectar-button jumbo see-through accent-color"]')
            .eq(4)
            .should('have.text', "Login")
            .should('have.attr', 'style', 'margin-right: 15px; margin-left: 15px; visibility: visible; color: rgb(255, 255, 255); border-color: rgba(255, 255, 255, 0.75);')
            .should('have.attr', 'href', "/login/")
            .click()
        cy.url()
            .should("include", "/login/")
        cy.get('h5').should(($h5) => {
            expect($h5, 'H5 Title').to.contain("Login to access your account:")
        }) 
    })

    it('Document Test - iPhone12-Mini-portrait', () => {
        cy.viewport(390,780, 'portrait')
        cy.get('[class="nectar-button jumbo see-through accent-color"]').should(($necton) => {
            //expect($necton).to.have.length(3)
            expect($necton.eq(0), 'first button').to.contain('Give')
            expect($necton.eq(1), 'second button').to.contain('Mission')
            expect($necton.eq(2), 'third button').to.contain('Blockchain')
            expect($necton.eq(3), 'fourth button').to.contain('Sign Up Free')
            expect($necton.eq(4), 'fifth button').to.contain('Login')
        }) 
        
        cy.get('[class="nectar-button jumbo see-through accent-color"]')
            .eq(0)
            .should('have.text', "Give")
            .should('have.attr', 'style', 'margin-right: 15px; margin-left: 15px; visibility: visible; color: rgb(255, 255, 255); border-color: rgba(255, 255, 255, 0.75);')
            .should('have.attr', 'href', "/give-information/")
            .click()
        cy.url()
            .should("include", "/give-information/")
        cy.get('h1').should(($h1) => {
            expect($h1, 'H1 Title').to.contain('Give')
            expect($h1, 'H1 Title').to.have.attr('style', "text-align: center")
        })
        cy.get('[class="starting-logo dark-version mobile-only-logo skip-lazy"]').click()

        cy.get('[class="nectar-button jumbo see-through accent-color"]')
            .eq(1)
            .should('have.text', "Mission")
            .should('have.attr', 'style', 'margin-right: 15px; margin-left: 15px; border-color: rgba(255, 255, 255, 0.75); color: rgb(255, 255, 255); visibility: visible;')
            .should('have.attr', 'href', "/mission-information/")
            .click()
        cy.url()
            .should("include", "/mission-information/")
        cy.get('h1').should(($h1) => {
            expect($h1, 'H1 Title').to.contain('We Can Make a Change')
        })
        cy.get('[class="starting-logo dark-version mobile-only-logo skip-lazy"]').click()

        cy.get('[class="nectar-button jumbo see-through accent-color"]')
            .eq(2)
            .should('have.text', "Blockchain")
            .should('have.attr', 'style', 'margin-right: 15px; margin-left: 15px; visibility: visible; color: rgb(255, 255, 255); border-color: rgba(255, 255, 255, 0.75);')
            .should('have.attr', 'href', "/give-node-information/")
            .click()
        cy.url()
            .should("include", "/give-node-information/")
        cy.get('h4').should(($h4) => {
            expect($h4, 'H4 Title').to.contain('Login to make purchases and give.')
            expect($h4, 'style assert').to.have.attr('style', "text-align: center;")
        }) 
        cy.get('[class="starting-logo dark-version mobile-only-logo skip-lazy"]').click()

        cy.get('[class="nectar-button jumbo see-through accent-color"]')
            .eq(3)
            .should('have.text', "Sign Up Free")
            .should('have.attr', 'style', 'margin-right: 15px; margin-left: 15px; visibility: visible; color: rgb(255, 255, 255); border-color: rgba(255, 255, 255, 0.75);')
            .should('have.attr', 'href', "/lets-give/")
            .click()
        cy.url()
            .should("include", "/lets-give/")
        cy.get('h5').should(($h5) => {
            expect($h5, 'H5 Title').to.contain("Join The Movement")
        }) 
        cy.go('back')

        cy.get('[class="nectar-button jumbo see-through accent-color"]')
            .eq(4)
            .should('have.text', "Login")
            .should('have.attr', 'style', 'margin-right: 15px; margin-left: 15px; visibility: visible; color: rgb(255, 255, 255); border-color: rgba(255, 255, 255, 0.75);')
            .should('have.attr', 'href', "/login/")
            .click()
        cy.url()
            .should("include", "/login/")
        cy.get('h5').should(($h5) => {
            expect($h5, 'H5 Title').to.contain("Login to access your account:")
        }) 
    })

    it('Document Test - iPad-Pro-landscape', () => {
        cy.viewport(1366,1024, 'landscape')
        cy.get('[class="nectar-button jumbo see-through accent-color"]').should(($necton) => {
            //expect($necton).to.have.length(3)
            expect($necton.eq(0), 'first button').to.contain('Give')
            expect($necton.eq(1), 'second button').to.contain('Mission')
            expect($necton.eq(2), 'third button').to.contain('Blockchain')
            expect($necton.eq(3), 'fourth button').to.contain('Sign Up Free')
            expect($necton.eq(4), 'fifth button').to.contain('Login')
        }) 
        
        cy.get('[class="nectar-button jumbo see-through accent-color"]')
            .eq(0)
            .should('have.text', "Give")
            .should('have.attr', 'style', 'margin-right: 15px; margin-left: 15px; visibility: visible; color: rgb(255, 255, 255); border-color: rgba(255, 255, 255, 0.75);')
            .should('have.attr', 'href', "/give-information/")
            .click()
        cy.url()
            .should("include", "/give-information/")
        cy.get('h1').should(($h1) => {
            expect($h1, 'H1 Title').to.contain('Give')
            expect($h1, 'H1 Title').to.have.attr('style', "text-align: center")
        })
        cy.get('[class="starting-logo dark-version skip-lazy default-logo"]').click()

        cy.get('[class="nectar-button jumbo see-through accent-color"]')
            .eq(1)
            .should('have.text', "Mission")
            .should('have.attr', 'style', 'margin-right: 15px; margin-left: 15px; border-color: rgba(255, 255, 255, 0.75); color: rgb(255, 255, 255); visibility: visible;')
            .should('have.attr', 'href', "/mission-information/")
            .click()
        cy.url()
            .should("include", "/mission-information/")
        cy.get('h1').should(($h1) => {
            expect($h1, 'H1 Title').to.contain('We Can Make a Change')
        })
        cy.get('[class="starting-logo dark-version skip-lazy default-logo"]').click()

        cy.get('[class="nectar-button jumbo see-through accent-color"]')
            .eq(2)
            .should('have.text', "Blockchain")
            .should('have.attr', 'style', 'margin-right: 15px; margin-left: 15px; visibility: visible; color: rgb(255, 255, 255); border-color: rgba(255, 255, 255, 0.75);')
            .should('have.attr', 'href', "/give-node-information/")
            .click()
        cy.url()
            .should("include", "/give-node-information/")
        cy.get('h4').should(($h4) => {
            expect($h4, 'H4 Title').to.contain('Login to make purchases and give.')
            expect($h4, 'style assert').to.have.attr('style', "text-align: center;")
        }) 
        cy.get('[class="starting-logo dark-version skip-lazy default-logo"]').click()

        cy.get('[class="nectar-button jumbo see-through accent-color"]')
            .eq(3)
            .should('have.text', "Sign Up Free")
            .should('have.attr', 'style', 'margin-right: 15px; margin-left: 15px; visibility: visible; color: rgb(255, 255, 255); border-color: rgba(255, 255, 255, 0.75);')
            .should('have.attr', 'href', "/lets-give/")
            .click()
        cy.url()
            .should("include", "/lets-give/")
        cy.get('h5').should(($h5) => {
            expect($h5, 'H5 Title').to.contain("Join The Movement")
        }) 
        cy.go('back')

        cy.get('[class="nectar-button jumbo see-through accent-color"]')
            .eq(4)
            .should('have.text', "Login")
            .should('have.attr', 'style', 'margin-right: 15px; margin-left: 15px; visibility: visible; color: rgb(255, 255, 255); border-color: rgba(255, 255, 255, 0.75);')
            .should('have.attr', 'href', "/login/")
            .click()
        cy.url()
            .should("include", "/login/")
        cy.get('h5').should(($h5) => {
            expect($h5, 'H5 Title').to.contain("Login to access your account:")
        }) 
    })

    it('Document Test - iPad-Pro-portrait', () => {
        cy.viewport(1024,1366, 'portrait')
        cy.get('[class="nectar-button jumbo see-through accent-color"]').should(($necton) => {
            //expect($necton).to.have.length(3)
            expect($necton.eq(0), 'first button').to.contain('Give')
            expect($necton.eq(1), 'second button').to.contain('Mission')
            expect($necton.eq(2), 'third button').to.contain('Blockchain')
            expect($necton.eq(3), 'fourth button').to.contain('Sign Up Free')
            expect($necton.eq(4), 'fifth button').to.contain('Login')
        }) 
        
        cy.get('[class="nectar-button jumbo see-through accent-color"]')
            .eq(0)
            .should('have.text', "Give")
            .should('have.attr', 'style', 'margin-right: 15px; margin-left: 15px; visibility: visible; color: rgb(255, 255, 255); border-color: rgba(255, 255, 255, 0.75);')
            .should('have.attr', 'href', "/give-information/")
            .click()
        cy.url()
            .should("include", "/give-information/")
        cy.get('h1').should(($h1) => {
            expect($h1, 'H1 Title').to.contain('Give')
            expect($h1, 'H1 Title').to.have.attr('style', "text-align: center")
        })
        cy.get('[class="starting-logo dark-version skip-lazy default-logo"]').click()

        cy.get('[class="nectar-button jumbo see-through accent-color"]')
            .eq(1)
            .should('have.text', "Mission")
            .should('have.attr', 'style', 'margin-right: 15px; margin-left: 15px; border-color: rgba(255, 255, 255, 0.75); color: rgb(255, 255, 255); visibility: visible;')
            .should('have.attr', 'href', "/mission-information/")
            .click()
        cy.url()
            .should("include", "/mission-information/")
        cy.get('h1').should(($h1) => {
            expect($h1, 'H1 Title').to.contain('We Can Make a Change')
        })
        cy.get('[class="starting-logo dark-version skip-lazy default-logo"]').click()

        cy.get('[class="nectar-button jumbo see-through accent-color"]')
            .eq(2)
            .should('have.text', "Blockchain")
            .should('have.attr', 'style', 'margin-right: 15px; margin-left: 15px; visibility: visible; color: rgb(255, 255, 255); border-color: rgba(255, 255, 255, 0.75);')
            .should('have.attr', 'href', "/give-node-information/")
            .click()
        cy.url()
            .should("include", "/give-node-information/")
        cy.get('h4').should(($h4) => {
            expect($h4, 'H4 Title').to.contain('Login to make purchases and give.')
            expect($h4, 'style assert').to.have.attr('style', "text-align: center;")
        })
        cy.get('[class="starting-logo dark-version skip-lazy default-logo"]').click()

        cy.get('[class="nectar-button jumbo see-through accent-color"]')
            .eq(3)
            .should('have.text', "Sign Up Free")
            .should('have.attr', 'style', 'margin-right: 15px; margin-left: 15px; visibility: visible; color: rgb(255, 255, 255); border-color: rgba(255, 255, 255, 0.75);')
            .should('have.attr', 'href', "/lets-give/")
            .click()
        cy.url()
            .should("include", "/lets-give/")
        cy.get('h5').should(($h5) => {
            expect($h5, 'H5 Title').to.contain("Join The Movement")
        }) 
        cy.go('back')

        cy.get('[class="nectar-button jumbo see-through accent-color"]')
            .eq(4)
            .should('have.text', "Login")
            .should('have.attr', 'style', 'margin-right: 15px; margin-left: 15px; visibility: visible; color: rgb(255, 255, 255); border-color: rgba(255, 255, 255, 0.75);')
            .should('have.attr', 'href', "/login/")
            .click()
        cy.url()
            .should("include", "/login/")
        cy.get('h5').should(($h5) => {
            expect($h5, 'H5 Title').to.contain("Login to access your account:")
        }) 
    })
})