/// <reference types="cypress" />
// When a customer is logged in
describe('Login', () => {
    beforeEach(() => {
        cy.visit('https://giveblockchain.io/terms-of-use/')
        cy.url().should('include', "/terms-of-use/") 
    })

    it('Expecting/Asserting Section 1 GIVE SERVICES text:', () => {

        cy.get('h3').should(($h3) => {
            expect($h3.eq(0), 'H3 First Title')
                .to.contain('Terms of Use')

        }) 

        cy.get('p').should(($terms_para) => {
            expect($terms_para.eq(0), 'Modified Date')
                .to.contain("Modified: August 27, 2021")
            expect($terms_para.eq(1), 'First paragraph text')
                .to.contain("These Terms and Conditions constitute the User Agreement and Terms of Service (hereafter the “Terms & Conditions”) between giveblockchain.io (referred to as “GIVE ” or the “Site”) and any person, customer, or entity (referred as the “User”) utilizing the website, GIVE Blockchain and any products, features and services provided thereon (“GIVE Services”). These Terms & Conditions do not create any agency, partnership, or joint venture between GIVE and User. By signing up for an account through GIVE or any associated websites, APIs, or mobile applications, the User has read and consents to the Terms & Conditions. The User also agrees to GIVE’s Privacy Policy. These Terms & Conditions may be amended and updated from time to time at the sole discretion of GIVE. Revised versions will be considered effective as of the date and time posted on the GIVE Site.")
            expect($terms_para.eq(2), 'First paragraph text')
                .to.contain("1. GIVE SERVICES.")
            expect($terms_para.eq(3), 'First paragraph text')
                .to.contain("GIVE is a decentralized distributed application on a blockchain network, using smart contracts (each a “Smart Contract”) to enable its Users to own, buy, sell, transfer, and share unique digital rewards that can be visualized on the GIVE site through the GIVE App.")
            expect($terms_para.eq(4), 'First paragraph text')
                .to.contain("1.1 GIVE Node.\u00a0GIVE Node is a computer software and/or hardware system connected to the GIVE blockchain. The GIVE Node supports blockchain work by maintaining the cryptography and confirming transactions on the GIVE Blockchain. It is foreseeable that at the option of the User, the GIVE Node may be recommissioned by the User to support other blockchains or other technologies. \u00a0Used herein, “GIVE Node” may represent either the node itself or a license the User obtains to run the node. \u00a0The GIVE Nodes when combined form the “GIVE Node Network.”")
            expect($terms_para.eq(5), 'First paragraph text')
                .to.contain("1.2 GIVE Blockchain.\u00a0The GIVE Blockchain allows each User to store digital rewards, and other attributes on the GIVE Blockchain public ledger that allows for decentralized, immutable record of ownership. When a User purchases, earns, or receives any digital reward through the Smart Contract process, the User owns completely and outright the digital reward.")
            expect($terms_para.eq(6), 'First paragraph text')
                .to.contain("1.3 GIVE Reward.\u00a0Each User of any service on the GIVE Blockchain and associated GIVE Node may be able to earn the GIVE Reward. The GIVE Reward is a digital reward and not a security token. GIVE is not being offered to investors and there is no Initial Coin Offering (ICO) to promote GIVE. Like BTC (which is the digital reward generated from the Bitcoin Blockchain), GIVE is created through a unique blockchain protocol. Although GIVE Reward may one day have market adoption, its utility may reside solely within the GIVE Blockchain, and may or may not have value.")
            expect($terms_para.eq(7), 'First paragraph text')
                .to.contain("1.4 GIVE App")
            expect($terms_para.eq(8), 'First paragraph text')
                .to.contain("1.4.1.\u00a0GIVE will provide each User with a GIVE App. GIVE will never take custody or control over any digital rewards stored in a User’s GIVE App. The GIVE App does not store, send or receive any NFT or digital reward, but such transactions occur directly on the GIVE Blockchain or other supported blockchains. Instead of the GIVE App, the User may use any compatible digital app or wallet provided by a third party company that safely connects to the GIVE Blockchain. A User may be able to use the GIVE App or other compatible wallet to send and receive digital rewards with other users of the GIVE Blockchain. GIVE does not offer any User the ability to exchange one form of currency for any other form of currency (fiat or digital). GIVE App is not a custodian, exchange or money transmitter.")
            expect($terms_para.eq(9), 'First paragraph text')
                .to.contain("1.4.2.\u00a0When a User creates a GIVE App, the GIVE Blockchain software generates a cryptographic private key and public key pair that the User must use to send and receive any digital reward supported on the GIVE Blockchain. The User is solely responsible for storing and keeping secret, outside of GIVE’s Services, a backup of any User’s GIVE App credentials, private key(s), passwords, and transaction information that the User maintains in the GIVE App or otherwise with the GIVE Services. If the User does not backup the GIVE App, the User may not be able to access the GIVE in the event that GIVE discontinues some or all of the GIVE Services. Any digital reward a User has stored within its GIVE App may become inaccessible if the User does not know or keep secret its GIVE App keys and passwords. GIVE does not receive or store a User’s app passwords, PIN, keys, network addresses or transaction history. GIVE cannot assist any User with app password or key retrieval. Any third party with knowledge of one or more of a User’s credentials (including, without limitation, a backup phrase, app identifier, password, or keys) can dispose of the Digital reward in the User’s app.")
            expect($terms_para.eq(10), 'First paragraph text')
                .to.contain("1.4.3.\u00a0In order for a transaction to be validated on the GIVE Blockchain, any GIVE transaction through the GIVE App must be confirmed and recorded in the distributed ledger associated with the GIVE Blockchain. The GIVE Blockchain is a decentralized, peer-to-peer network supported by the users of the GIVE Blockchain, which is not owned, controlled or operated by GIVE.")
            expect($terms_para.eq(11), 'First paragraph text')
                .to.contain("1.4.4.\u00a0GIVE has no control over digital rewards generated through the GIVE Blockchain, and cannot ensure that any transaction details a User submits via the GIVE Services and GIVE App will be confirmed or processed on the GIVE Blockchain. The User agrees and understands that the transaction details submitted by the User via the GIVE Services and GIVE App may not be completed or may be delayed by the GIVE Blockchain or any supporting blockchain used to process the transaction. GIVE does not guarantee that the GIVE App can transfer title or right in any NFT or digital reward, and GIVE makes no warranties of title of any kind. Once transaction details have been submitted to the GIVE Blockchain, GIVE cannot assist the User to cancel or otherwise modify such transaction or details.")
            expect($terms_para.eq(12), 'First paragraph text')
                .to.contain("1.4.5.\u00a0In the event of a fork of the GIVE Blockchain or any other supported blockchain, GIVE may not be able to support the User’s activity related to GIVE or any other supported NFT or reward. The User agrees and understands that in the event of a fork of the GIVE Blockchain, any transaction associated with the GIVE App or GIVE Services may not be completed, may be partially completed, incorrectly completed, or substantially delayed. GIVE is not responsible for any loss incurred by any User caused in whole or in part, directly or indirectly, by a fork of the GIVE Blockchain.")
            expect($terms_para.eq(13), 'First paragraph text')
                .to.contain("1.4.6.\u00a0GIVE does not currently charge a fee for the GIVE App, receiving, sending, or storing GIVE. However, GIVE reserves the right to do so in the future, and in such case any applicable fees will be displayed prior to the User incurring such fee. Notwithstanding, the GIVE Blockchain may have Blockchain Transaction Fees required to transact digital reward transactions through the GIVE Blockchain. GIVE may attempt to calculate for the User any Blockchain Transactions Fees, though such calculation may be inaccurate or excessive. The User may select a greater or lesser fee, and the User is solely responsible for paying any Blockchain Transaction Fees required on the GIVE Blockchain. GIVE will neither advance nor fund any Blockchain Transaction Fee on any User’s behalf, nor be responsible for any excess or insufficient fee calculation.")
            expect($terms_para.eq(14), 'First paragraph text')
                .to.contain("1.4.7 The User shall be responsible for all activities that occur through the GIVE APP and accepts all risks of any authorized or unauthorized access to the GIVE app, to the maximum extent permitted by law. The User represents and warrants that the User is familiar with and accepts the risks associated with digital apps and private keys, including the risks described herein.")
            expect($terms_para.eq(15), 'First paragraph text')
                .to.contain("1.4.8.\u00a0\u00a0From time to time, there may be programs in place to allow User to receive a reward, in the form of GIVE Reward, NFT, or otherwise, based on actions taken by the User, whether it be by referral or other program in place at the time (“Additional Rewards”). \u00a0User understands that GIVE makes no representations or warrants regarding the Additional Rewards. \u00a0Notwithstanding or limiting the foregoing, GIVE further makes no representations or warrants surrounding the operation of any GIVE Services or that said GIVE Services/Additional Rewards will be error-free or uninterrupted. \u00a0User accepts the sole responsibility for taking any and all actions to obtain any Additional Rewards, and holds GIVE harmless for any\u00a0opportunity\u00a0cost or losses that occur as a result of the non-receipt of\u00a0anticipated\u00a0Additional Rewards, monetary or otherwise.")
        }) 
    })

    it('Expecting/Asserting Section 2 PAYMENT TERMS text:', () => {

        cy.get('p').should(($terms_para) => {
            expect($terms_para.eq(16), 'First paragraph text')
                .to.contain("2. PAYMENT TERMS.")
            expect($terms_para.eq(17), 'First paragraph text')
                .to.contain("2.1. Annual License and Monthly Service Fees.")
                .to.contain("The User shall pay a one-time GIVE Node license fee and the then-current monthly service fee(s) for GIVE Services. GIVE or any of its affiliates or third parties may be the party that sells the software or hardware for any GIVE Node.")
            expect($terms_para.eq(18), 'First paragraph text')
                .to.contain("2.2. Software License.")
            expect($terms_para.eq(19), 'First paragraph text')
                .to.contain("The User may be required to enter into a software license agreement with GIVE or any third party for the use of any required software for each GIVE Node. The User shall pay all associated software license fees.")
            expect($terms_para.eq(20), 'First paragraph text')
                .to.contain("2.3. Equipment Purchase.")
            expect($terms_para.eq(21), 'First paragraph text')
                .to.contain("The User may enter into an equipment purchase agreement with a third party as it relates to the purchase of any hardware for a GIVE Node. The User is not required to purchase such hardware, but may use any equipment technology (e.g. computer, GPU, cell phone, or other technology) that can provide the necessary computing hash rate and appropriately and safely access and connect to the GIVE Blockchain.")
            expect($terms_para.eq(22), 'First paragraph text')
                .to.contain("2.4. Maintenance and Hosting Fees.")
            expect($terms_para.eq(23), 'First paragraph text')
                .to.contain("GIVE does not maintain or host any GIVE Node, but may refer the User to one or more third-party hosting companies that may or may not be affiliated with GIVE. If the User elects and is part of a separate hosting agreement, the User may be required to pay certain data center operations, maintenance and power fees (“Maintenance Fees”). These Maintenance Fees may be deducted from the User’s digital rewards or GIVE Reward with the consent of GIVE, at GIVE’s discretion.")
            expect($terms_para.eq(24), 'First paragraph text')
                .to.contain("2.5. Blockchain Transaction Fees.")
            expect($terms_para.eq(25), 'First paragraph text')
                .to.contain("The delivery and receipt of any of the User’s digital rewards through the GIVE App may be subject to network or transaction fees charged by the blockchain associated with the User-selected algorithm (“Blockchain Transaction Fees”), which are non-refundable. Blockchain Transaction Fees are paid to emit, record, verify, and process a transaction on the blockchain. Any withdrawal or transfer of the User’s digital rewards may be subject to Blockchain Transaction Fees.")
            expect($terms_para.eq(26), 'First paragraph text')
                .to.contain("2.6. Other Third-Party Fees.")
            expect($terms_para.eq(27), 'First paragraph text')
                .to.contain("Certain digital apps, app addresses, tools, and third-party software and devices (“Third-Party Fees”) used by the User may also charge the User a fee, including a per transaction or transfer fee, which are non-refundable. The User is responsible for satisfying any such fee(s). The User should note that any such fees may significantly reduce the User’s rewards and therefore the User is responsible for managing the selection, use, rate and frequency of their receipt of rewards to any such Third-Party Fees.")
            expect($terms_para.eq(28), 'First paragraph text')
                .to.contain("2.7. Taxes.")
            expect($terms_para.eq(29), 'First paragraph text')
                .to.contain("The User is responsible for any taxes, and the User will pay for GIVE Services without any reduction for taxes. If the User is required by law to withhold any taxes from its payments to GIVE, the User must provide GIVE with an official tax receipt or other qualified documentation to support such withholding, including value added tax (“VAT”), if applicable. The User will be liable to pay (or reimburse GIVE) for any taxes, interest, penalties or fines which may arise from any mis-declaration made by the User. The User shall pay GIVE for all taxes and governmental fees GIVE is required to collect or pay upon sale or delivery of GIVE Services.")
            expect($terms_para.eq(30), 'First paragraph text')
                .to.contain("POTENTIAL USERS OF NFTS, DIGITAL REWARDS, INCLUDING BUT NOT LIMITED TO BITCOIN, ARE FOREWARNED OF POSSIBLE FINANCIAL LOSS AT THE TIME SUCH REWARDS ARE EXCHANGED FOR FIAT CURRENCY DUE TO AN UNFAVORABLE EXCHANGE RATE. MOREOVER, A FAVORABLE EXCHANGE RATE AT THE TIME OF EXCHANGE MAY RESULT IN A TAX LIABILITY. USERS SHOULD CONSULT A TAX ADVISOR REGARDING ANY TAX CONSEQUENCES ASSOCIATED WITH THE PURCHASE, SALE, TRADE, OR OTHER USE OF DIGITAL REWARDS. USER IS SOLELY RESPONSIBLE FOR THE PAYMENT OF ANY APPLICABLE TAXES ASSOCIATED WITH THE PURCHASE, SALE, TRADE, OR OTHER USE OF NFTS, DIGITAL REWARDS, OR VIRTUAL CURRENCIES.")
        }) 
    })

    it('Expecting/Asserting Section 3 USER OBLIGATIONS text:', () => {

        cy.get('p').should(($terms_para) => {
            expect($terms_para.eq(31), 'First paragraph text')
                .to.contain("3. USER OBLIGATIONS")
            expect($terms_para.eq(32), 'First paragraph text')
                .to.contain("3.1. Software and Equipment Allocation.")
            expect($terms_para.eq(33), 'First paragraph text')
                .to.contain("The User is responsible for the allocation of the User’s software and equipment and selected optimization strategies and decisions. The User acknowledges that GIVE is not responsible for the selection or timing of blockchain protocols, nor is GIVE responsible for the protocols selected for use in connection with GIVE Services. The User is solely responsible for these decisions. The User acknowledges that the node transactions on any blockchain may vary and will not be uniform across each GIVE Node. The User acknowledges that the difficulty of mining may vary and will likely increase over time.")
            expect($terms_para.eq(34), 'First paragraph text')
                .to.contain("3.2. Log-in Credentials.")
            expect($terms_para.eq(35), 'First paragraph text')
                .to.contain("The User represents and warrants that the User is responsible for the preservation of confidentiality of the User’s login credentials on the GIVE App and any other login for the GIVE Services. Login credentials generated for the User by GIVE are for the User’s internal use only and the User is strictly prohibited from selling, transferring, or sub-licensing them to any other entity or person.")
            expect($terms_para.eq(36), 'First paragraph text')
                .to.contain("3.3. Blockchain Network Risk.")
            expect($terms_para.eq(37), 'First paragraph text')
                .to.contain("The User represents and warrants that the User accepts the risks of blockchain protocol and network, including instability, congestion, high transaction costs, network latency, information security, regulatory risk, and technological and operational error. The User understands these risks may result in delay or failure to process transactions, failure to generate hash rate, and potentially high Blockchain Transaction Fees or Third Party Fees. The User represents and agrees that GIVE is not responsible for any diminished GIVE Services, related features, or capabilities resulting from blockchain network risk. In the event of a material increase or decrease to Blockchain Transaction Fees, Third Party Fees, or operational degradation, congestion, failure or other disruption of the blockchain network used by the User, GIVE may, at its sole discretion and upon notice to the User, make any adjustments to the GIVE Services.")
            expect($terms_para.eq(38), 'First paragraph text')
                .to.contain("3.4. Blockchain Modification Risk.")
            expect($terms_para.eq(39), 'First paragraph text')
                .to.contain("The User represents and warrants that the User is familiar with and accepts the risks associated with blockchain development and code changes. Blockchain technologies are still under development and may undergo significant changes over time. Blockchain contributors may make changes to features and specifications of the algorithm selected by the User, and may fork the GIVE Blockchain protocol. Such changes may include or result in the elimination or support for specific algorithms and applications.")
            expect($terms_para.eq(40), 'First paragraph text')
                .to.contain("3.5 Proof-Of-Work Replacement Risk")
            expect($terms_para.eq(41), 'First paragraph text')
                .to.contain("In addition to blockchain modification risk, blockchain contributors may also modify the cryptographic verification process such that the blockchains can no longer be verified through Proof-of-Work and instead adopt Proof-of-Stake methodologies. The User accepts and acknowledges such risk and shall allocate the User’s hash rate to other available blockchains and mining processes that use Proof-of-Work methodologies. The User further acknowledges that certain blockchain algorithms have no alternative blockchain applications that support Proof-of-Work mining and any such switch from Proof-of-Work to Proof-of-Stake would result in no applicable use of the User’s hash rate.")
            expect($terms_para.eq(42), 'First paragraph text')
                .to.contain("3.6. Trade Compliance.")
            expect($terms_para.eq(43), 'First paragraph text')
                .to.contain("User shall comply with all applicable import, re-import, sanctions, anti-boycott, export, and re-export control laws and regulations, including all such laws and regulations that apply to European Union and U.S. companies, such as the Export Administration Regulations, the International Traffic in Arms Regulations, and economic sanctions programs implemented by the Office of Foreign Assets Control and the European Union’s Common Foreign and Security Policy (collectively, “Trade Sanctions Laws”). The User represents and warrants that the User and the User’s financial institutions, or any party that owns or controls the User or the User’s financial institutions, are not subject to sanctions or otherwise designated on any list of prohibited or restricted parties, including but not limited to the lists maintained by the United Nations Security Council, the U.S. Government (e.g., the Specially Designated Nationals List and Foreign as Evaders List of the U.S. Department of Treasury, and the Entity List of the U.S. Department of Commerce), the European Union or its Member States, or other applicable government authority.")
                .to.contain("Further, User represents and warrants that it is currently in compliance with and shall at all times during the term of this agreement remain in compliance with the regulations of the United States Office of Foreign Assets Control (“OFAC”), including those named on FFAC’s Specially Designated and Blocked Persons List, and any statute, executive order (including the September 24, 2001, Executive Order Blocking Property and Prohibiting Transactions with Persons who Commit, Threaten to Commit or Support Terrorism), or other governmental action relating thereto. Specifically, User shall not engage in business, sell to, or form a business relationship on behalf of others or for itself with any individual or country in contravention or violation of the aforementioned rules, laws, and regulations. The User warrants that it is not named on any OFAC Blocked Persons List or resides in any country or territory sanctioned by OFAC. The User shall indemnify and hold harmless GIVE against and from any claim, loss, damage or expense (including attorneys’ fees and costs for the underlying investigation) arising from any breach or misrepresentation of this section.")
            expect($terms_para.eq(44), 'First paragraph text')
                .to.contain("3.7 Anti-Bribery")
            expect($terms_para.eq(45), 'First paragraph text')
                .to.contain("User Acknowledges that its activities under this agreement may be subject to United States and other anti-bribery and corruption legislation around the world (including without limitations, the U.S. Foreign Corrupt Practices Act and the UK Bribery Act). User warrants that it has not and undertakes and agrees that it shall not, in connection with this Agreement, make or promise to make any payment or transfer of anything of value, directly, or indirectly, to:")
            expect($terms_para.eq(46), 'First paragraph text')
                .to.contain("i. any governmental official or employee (including employees of government-owned or state-controlled corporations and employees of public international organizations);")
            expect($terms_para.eq(47), 'First paragraph text')
                .to.contain("ii. any political party, official or candidate;")
            expect($terms_para.eq(48), 'First paragraph text')
                .to.contain("iii. any intermediary for payment to any of the foregoing; or")
            expect($terms_para.eq(49), 'First paragraph text')
                .to.contain("iv. to any other person or entity if such payment or transfer would violate the laws of the country in which it is made or the laws of the United States of America")
            expect($terms_para.eq(50), 'First paragraph text')
                .to.contain("v. User acknowledges and agrees that no payments or transfers of value shall be made that have the purpose or effect of public or commercial bribery, acceptance of or acquiescence in extortion, kickbacks or other unlawful or improper means of obtaining business or any improper advantage.")
            expect($terms_para.eq(51), 'First paragraph text')
                .to.contain("3.8 Ownership Restrictions.")
            expect($terms_para.eq(52), 'First paragraph text')
                .to.contain("User acknowledges and agrees that GIVE, any developer, or third party contract provider (or, as applicable, any licensors) own all legal right, title and interest in and to all elements of their respective intellectual property rights therein. The visual interfaces, graphics (including, without limitation, all art and drawings associated with the), design, systems, methods, information, computer code, software, services, “look and feel”, organization, compilation of the content, code, data, and all other elements of any content provided on the Site, GIVE App, or GIVE Blockchain are protected by copyright, trade dress, patent, and trademark laws, international conventions, other relevant intellectual property and proprietary rights, and applicable laws. All such intellectual property are the property of its owners or licensors, and all trademarks, service marks, and trade names are proprietary to its owner or licensors. Except as expressly set forth herein, the use of the GIVE Services and GIVE App does not grant User any ownership of or any other rights with respect to any content, code, data, or other materials that you may access on or through the GIVE App.")
            expect($terms_para.eq(53), 'First paragraph text')
                .to.contain("3.9 Children.")
            expect($terms_para.eq(54), 'First paragraph text')
                .to.contain("USER AFFIRMS HE/SHE IS OVER THE AGE OF 18 OR THE LEGAL AGE OF MAJORITY WHERE THE USER RESIDES IF THAT JURISDICTION HAS AN OLDER AGE OF MAJORITY, AS THE GIVE APP AND GIVE SERVICES ARE NOT INTENDED FOR CHILDREN UNDER AGE 18 OR THOSE THAT HAVE NOT REACHED THE AGE OF MAJORITY.")
            expect($terms_para.eq(55), 'First paragraph text')
                .to.contain("3.10 Responsibility for Conduct.")
            expect($terms_para.eq(56), 'First paragraph text')
               .to.contain("User takes responsibility for all activities that occur under its GIVE App and for its use of the GIVE Services, and User accepts all risks of any authorized or unauthorized access to its GIVE App, to the maximum extent permitted by law.")
               .to.contain("User represents and warrants that the User is familiar with and accepts the risks associated with digital Apps and private keys, including the risks described herein. User is solely responsible for its own conduct while accessing or using the GIVE Services or GIVE App, and for any consequences thereof.")
               .to.contain("User agrees to use the GIVE Services, GIVE App, and GIVE Blockchain for purposes that are legal, proper and in accordance with these Terms and any applicable laws or regulations. By way of example, and not as a limitation, User may not, and may not allow any third party to: (i) send, upload, distribute or disseminate any unlawful, defamatory, harassing, abusive, fraudulent, obscene, or otherwise objectionable content; (ii) distribute viruses, worms, defects, Trojan horses, corrupted files, hoaxes, or any other items of a destructive or deceptive nature; (iii) impersonate another person (via the use of an email address or otherwise); (iv) upload, post, transmit or otherwise make available through the GIVE Services any content that infringes the intellectual proprietary rights of any party; (v) use the GIVE Services to violate the legal rights (such as rights of privacy and publicity) of others; (vi) engage in, promote, or encourage illegal activity (including, without limitation, money laundering); (vii) interfere with other users’ enjoyment of the GIVE App or GIVE Blockchain; (viii) exploit the GIVE Services for any unauthorized commercial purpose; (ix) modify, adapt, translate, or reverse engineer any portion of the GIVE Services; (x) remove any copyright, trademark or other proprietary rights notices contained in or on the GIVE App or GIVE Blockchain or any part of it; (xi) reformat or frame any portion of the GIVE App; (xii) display any content on the GIVE App or GIVE Blockchain that contains any hate-related or violent content or contains any other material, products or services that violate or encourage conduct that would violate any criminal laws, any other applicable laws, or any third party rights; (xiii) use any robot, spider, site search/retrieval application, or other device to retrieve or index any portion of the GIVE App or the content posted on the GIVE App, or to collect information about its users for any unauthorized purpose; or (xiv) create user accounts by automated means or under false or fraudulent pretenses. The User shall indemnify and hold harmless GIVE against and from any claim, loss, damage or expense (including attorneys’ fees and costs for the underlying investigation) arising from any breach or misrepresentation of this section. User is solely responsible for all financial charges and legal liability that he or she may incur.")
            expect($terms_para.eq(57), 'First paragraph text')
                .to.contain("3.11 Representations Made By User.")
            expect($terms_para.eq(58), 'First paragraph text')
                .to.contain("User acknowledges and agrees that the GIVE Services, including but not limited to the GIVE Node, ARE NOT being sold as an investment by or of GIVE. \u00a0THE USER UNDERSTANDS THAT ANY REPRESENTATIONS MADE BY THE USER AT ANY TIME THAT ANY OF THE GIVE SERVICES ARE AN INVESTMENT IN GIVE (OR OTHERWISE, INCLUDING, BUT NOT LIMITED TO, IN GENERAL) TO OTHERS IN A DIRECT ATTEMPT TO MARKET GIVE SERVICES IN COORDINATION WITH SUPPLYING USER’S REFERRAL LINK IS A DIRECT BREACH OF THE TERMS & CONDITIONS. A determination of same will be made at the sole discretion of GIVE.")
            expect($terms_para.eq(59), 'First paragraph text')
                .to.contain("3.12 \u00a0GIVE NODE REPRESENTATIONS")
            expect($terms_para.eq(60), 'First paragraph text')
                .to.contain("GIVE\u00a0and the User recognize that the\u00a0SOLE AND ONLY\u00a0purpose of the\u00a0GIVE\u00a0Node is to support the GIVE Node Ecosystem. \u00a0Nothing contained in this Agreement, exhibit to this Agreement, or any representation made outside of this Agreement, conveys on the User any ownership interests in\u00a0GIVE\u00a0or its subsidiaries, or interests otherwise in GIVE\u00a0(including, but not limited to voting rights in the\u00a0GIVE), nor any expectation of profits from the efforts of GIVE\u00a0or its principals or subsidiaries. \u00a0The User understands that while it may from time to time receive rewards in line with the distribution schedule of the GIVE Node Ecosystem (“Distribution\u00a0Rewards”) (subject to change), said reward is solely earned because of and as a direct result of work accomplished and performed by the User (e.g. work done by the\u00a0GIVE\u00a0Node). \u00a0The User recognizes that should the User never actually run the\u00a0GIVE\u00a0Node, it will receive no rewards. \u00a0GIVE\u00a0has no control of the method in which rewards are distributed to the\u00a0GIVE\u00a0Node. \u00a0It is anticipated that the\u00a0GIVE\u00a0Node will be able to be sold or transferred in the future as NFTs, however,\u00a0GIVE\u00a0cannot and does not warrant or represent that the resale value of the Nodes will be higher than the purchase price should this event occur, nor that it will be legally\u00a0possible\u00a0to do so. \u00a0Further,\u00a0GIVE\u00a0cannot and does not warrant or represent that there will ever be a resale value or capability of the\u00a0GIVE\u00a0Node.")
        }) 
    })

    it('Expecting/Asserting Section 4 TERMINATION text:', () => {

        cy.get('p').should(($terms_para) => {
            expect($terms_para.eq(61), 'First paragraph text')
                .to.contain("4. TERMINATION")
            expect($terms_para.eq(62), 'First paragraph text')
                .to.contain("4.1. General.")
            expect($terms_para.eq(63), 'First paragraph text')
                .to.contain("GIVE may suspend or terminate the User’s right to access or use GIVE Services immediately and without notice if: (i) GIVE determines the User’s use of the GIVE Services poses a security risk to GIVE Services or any third party, could adversely impact GIVE, GIVE Services, GIVE Blockchain or any other GIVE users, or could subject GIVE, its affiliates, or any third party to liability, or could be fraudulent; (ii) the User is in breach of these Terms & Conditions; (iii) the User initiated a chargeback or dispute with respect to any payment or purchase of the GIVE Services; or (iv) the User has ceased to operate in the ordinary course, made an assignment for the benefit of creditors or similar disposition assets, or become the subject of any bankruptcy, reorganization, liquidation, dissolution or similar proceeding.")
            expect($terms_para.eq(64), 'First paragraph text')
                .to.contain("4.2. Effect of Suspension.")
            expect($terms_para.eq(65), 'First paragraph text')
                .to.contain("If GIVE suspends the User’s right to access or use any portion or all of the GIVE Services, the User shall remain responsible for all fees and charges the User incurs during the period of suspension, including any Maintenance Fees and Blockchain Transaction Fees; and the User may be in violation of the User’s hosting agreement or the blockchain protocols, which may prevent or limit the User’s entitlement or access to any results or rewards that may have occurred during the User’s suspension of the GIVE Services. User agrees to pay any fee charged by GIVE to reconnect the GIVE Services.")
            expect($terms_para.eq(66), 'First paragraph text')
                .to.contain("4.3. Effect of Termination.")
            expect($terms_para.eq(67), 'First paragraph text')
                .to.contain("If GIVE terminates the User’s right to access or use any portion or all of the GIVE Services, then all of the User’s rights under these Terms & Conditions immediately terminate and the User shall remain responsible for all fees owed to GIVE incurred through the termination date.")
        }) 
    })

    it('Expecting/Asserting Section 5 DECENTRALIZED GOVERNANCE text:', () => {

        cy.get('p').should(($terms_para) => {
            expect($terms_para.eq(68), 'First paragraph text')
                .to.contain("5. DECENTRALIZED GOVERNANCE")
            expect($terms_para.eq(69), 'First paragraph text')
                .to.contain("5.1. Decentralized Advisory Board.\u00a0The GIVE Blockchain may have a decentralized advisory board.")
            expect($terms_para.eq(70), 'First paragraph text')
                .to.contain("5.2. Consensus Nodes.\u00a0The GIVE Blockchain has consensus nodes, which are the GIVE Nodes that approve and validate transactions and contribute to the security and stability of the network. Any User that owns a GIVE Node involved in the consensus protocol may be rewarded from the GIVE Blockchain and be able to charge Blockchain Transaction Fees.")
            expect($terms_para.eq(71), 'First paragraph text')
                .to.contain("5.3. Community and Decentralized Innovation.\u00a0The GIVE Blockchain invites any person or entity throughout the world to contribute to the GIVE Blockchain, including coders, application developers, marketers, advertisers, and service and maintenance providers. Accepted amendments, updates, and innovation from individuals or groups of the GIVE Blockchain community may be rewarded from the GIVE Blockchain rewards.")
        }) 
    })

    it('Expecting/Asserting Section 6 & 7 PUBLICITY & REPRESENTATIONS AND WARRANTIES text:', () => {

        cy.get('p').should(($terms_para) => {
            expect($terms_para.eq(72), 'First paragraph text')
                .to.contain("6. PUBLICITY")
            expect($terms_para.eq(73), 'First paragraph text')
                .to.contain("The User is permitted to state publicly that it is a customer or user of GIVE, consistent with any Trademark Guidelines which may be adopted by GIVE from time to time. The User agrees to abide by the Privacy Policy and Code of Conduct of GIVE.")
            expect($terms_para.eq(74), 'First paragraph text')
                .to.contain("7. REPRESENTATIONS AND WARRANTIES")
            expect($terms_para.eq(75), 'First paragraph text')
                .to.contain("Each User represents and warrants that: (i) it has full power and authority to enter into these Terms & Conditions; and (ii) it will comply with all laws and regulations applicable to its provision or use of GIVE Services.")
        }) 
    })

    it('Expecting/Asserting Section 8 DISCLOSURES AND RISKS text:', () => {

        cy.get('p').should(($terms_para) => {
            expect($terms_para.eq(76), 'First paragraph text')
                .to.contain("8. DISCLOSURES & RISKS")
            expect($terms_para.eq(77), 'First paragraph text')
                .to.contain("8.1 Notification.\u00a0GIVE notifies each User of certain disclosures and risks associated with blockchain NFT and digital rewards and their associated technology and protocols. GIVE Services are not an investment product, and no action, notice, communication by any means, or omission by GIVE shall be understood or interpreted as such. GIVE has no influence whatsoever on the GIVE Blockchain, the transactions and consensus protocols, or the NFTs or digital rewards, including the GIVE Reward. Ownership of a GIVE App or Node or the use of GIVE Services does not represent or constitute any ownership right or stake, share or security, debt or equivalent right, or any right to receive any future revenue or form of participation in or relating to any blockchain or digital reward, including the GIVE Blockchain or GIVE Reward.")
            expect($terms_para.eq(78), 'First paragraph text')
                .to.contain("8.2 Digital Rewards.\u00a0Digital rewards are not considered legal tender, are not issued or backed by any government, and have fewer regulatory protections than traditional currency. Moreover, digital rewards are not insured against theft or loss by any insurance corporation or any investor protection, including the Federal Deposit Insurance Corporation or the Securities Investor Protection Corporation.")
            expect($terms_para.eq(79), 'First paragraph text')
                .to.contain("8.3 Market Risk.\u00a0The value of NFTs and digital rewards are derived from supply and demand in the global marketplace, which can rise or fall independent of any government currency. Holding NFTs and digital rewards carries exchange rate and other types of risk. The value of NFTs and digital rewards may be derived from the continued willingness of market participants to exchange traditional government currency for digital rewards, which may result in the potential for permanent and total loss of value of a particular digital reward should the market disappear. The volatility and unpredictability of the price and value of NFTs and digital rewards, relative to government currency, may result in significant loss over a short period of time. GIVE cannot guarantee or warrant the value of any NFT, digital reward or blockchain, including the GIVE Blockchain and GIVE Reward, and explicitly warns the User that that there is no reason to believe that any NFT, digital reward, or blockchain reward will increase in value, and that they may hold no value, decrease in value, or entirely lose value.")
            expect($terms_para.eq(80), 'First paragraph text')
                .to.contain("8.4. Regulatory Risk.\u00a0Legislative and regulatory changes or actions at the state, federal, or international level may adversely affect the use, transfer, exchange, and value of virtual NFTs, digital rewards, and blockchain rewards. \u00a0The regulatory status of digital assets and blockchain technology is unclear or unsettled in many jurisdictions. It is difficult to predict how or whether governmental authorities will regulate such technologies. It is likewise difficult to predict how or whether any governmental authority may make changes to existing laws, regulations and/or rules that will affect digital assets, blockchain technology and its applications. \u00a0Such changes could negatively impact the\u00a0GIVE\u00a0Services in various ways, including, for example, through a determination\u00a0that any\u00a0of the above are regulated financial instruments that require registration.\u00a0GIVE\u00a0may cease any distribution of any of the above, the development of the\u00a0GIVE\u00a0platform or cease operations in a jurisdiction in the event that governmental actions make it unlawful or commercially undesirable to continue to do so. \u00a0The industry in which\u00a0GIVE\u00a0operates is new, and may be subject to heightened oversight and scrutiny, including investigations or enforcement actions. There can be no assurance that governmental, quasi-governmental, regulatory or other similar types of (including banking) authorities will not examine the operations of\u00a0GIVE\u00a0and/or pursue enforcement actions against\u00a0GIVE. Such governmental activities may or may not be the result of targeting\u00a0GIVE\u00a0in particular. All of this may subject\u00a0GIVE\u00a0to judgments, settlements, fines or penalties, or cause\u00a0GIVE\u00a0to restructure its operations and activities or to cease offering certain products or services, all of which could harm\u00a0GIVE’s reputation or lead to higher operational costs, which may in turn have a material adverse effect on the\u00a0GIVE\u00a0Services.")
            expect($terms_para.eq(81), 'First paragraph text')
                .to.contain("8.5 Technology Risk.\u00a0Virtual NFT and digital reward transactions may be irreversible and losses due to fraudulent or accidental transactions may not be recoverable. Some virtual transactions are deemed to be made when recorded on a public ledger, which may not necessarily be the date or time the user initiated the transaction. The nature of such virtual transactions may lead to an increased risk of fraud or cyber-attacks.")
            expect($terms_para.eq(82), 'First paragraph text')
                .to.contain("8.6 Changes to GIVE Node Network.")
            expect($terms_para.eq(83), 'First paragraph text')
                .to.contain("GIVE\u00a0and User recognize that from time to time amendments will be made to the\u00a0GIVE\u00a0Node Network. \u00a0GIVE\u00a0and User both specifically agree that\u00a0GIVE\u00a0will, from time to time, present the\u00a0GIVE\u00a0Node Network with proposed amendments (the “Proposed\u00a0Amendments”) that the Node Network will then vote on whether to implement or not (the “Governance Vote”). \u00a0The User understands that the Proposed Amendments will be made at the discretion of\u00a0GIVE, and\u00a0GIVE\u00a0owes the User no duty or obligation to make proposals in its best interests.\u00a0\u00a0The User specifically understands that there may come a time when\u00a0GIVE\u00a0proposes an amendment that is not in or in direct opposition to the User’s best interests, financial or otherwise (including, but not limited to a change in the distribution calculation), and the User has no legal recourse against\u00a0GIVE\u00a0should any Proposed Amendment be approved and implemented through the Governance Vote. \u00a0The User’s only recourse is to vote against said Proposed Amendment. \u00a0GIVE\u00a0and the User both agree that one such Proposed Amendment may be to change the specifications, including, but not limited to the internet connection, Random Access Memory, Central\u00a0Processing\u00a0Unit requirements, extra space, and any other requirements needed to run the Nodes (the “Specifications”). \u00a0GIVE\u00a0and User further agree that while the Specifications may be minimal on the effective date of this Agreement, this is subject to change through the Proposed Amendment and the Governance Vote. \u00a0GIVE\u00a0does not and cannot represent or covenant that any rewards earned (financial or otherwise) for running a GIVE Node are not subject to change.")
        }) 
    })

    it('Expecting/Asserting Section 9 DISCLAIMER text:', () => {

        cy.get('p').should(($terms_para) => {
            expect($terms_para.eq(84), 'First paragraph text')
                .to.contain("9. DISCLAIMER")
            expect($terms_para.eq(85), 'First paragraph text')
                .to.contain("EXCEPT AS EXPRESSLY PROVIDED FOR IN THESE TERMS & CONDITIONS, TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, GIVE, ITS AFFILIATES, AND ITS SUPPLIERS DO NOT MAKE ANY OTHER WARRANTY OF ANY KIND, WHETHER EXPRESS, IMPLIED, STATUTORY OR OTHERWISE, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR USE AND NON-INFRINGEMENT. GIVE, ITS AFFILIATES, AND ITS SUPPLIERS ARE NOT RESPONSIBLE OR LIABLE FOR THE DELETION, FAILURE TO STORE, OR ANY LOSS OF ANY USER DATA, INCLUDING BLOCKCHAIN DATA, NFT AND DIGITAL REWARDS DERIVED, MAINTAINED, OR TRANSMITTED THROUGH USE OF GIVE SERVICES. THE USER IS SOLELY RESPONSIBLE FOR SECURING ITS CUSTOMER DATA AND DIGITAL REWARDS. NEITHER GIVE, ITS AFFILIATES, NOR ITS SUPPLIERS, WARRANTS THAT THE OPERATION OF GIVE SERVICES, GIVE BLOCKCHAIN, OR ANY OTHER SUPPORTED BLOCKCHAIN WILL BE ERROR-FREE OR UNINTERRUPTED. GIVE, ITS AFFILIATES, AND ITS SUPPLIERS ARE NOT RESPONSIBLE OR LIABLE FOR ANY LOSSES OR OPPORTUNITY COSTS RESULTING FROM BLOCKCHAIN NETWORK AND PROTOCOL OR THIRD-PARTY SOFTWARE ISSUES, WHICH MAY IN TURN RESULT IN THE INABILITY TO PROCESS TRANSACTIONS ON ANY BLOCKCHAIN AT ALL OR WITHOUT INCURRING SUBSTANTIAL FEES.")
        }) 
    })

    it('Expecting/Asserting Section 10 LIMITATIONS & LIABILITY text:', () => {

        cy.get('p').should(($terms_para) => {
            expect($terms_para.eq(86), 'First paragraph text')
                .to.contain("10. LIMITATION OF LIABILITY")
            expect($terms_para.eq(87), 'First paragraph text')
                .to.contain("10.1. Limitation of Indirect Liability.")
            expect($terms_para.eq(88), 'First paragraph text')
                .to.contain("THE AGGREGATE LIABILITY OF GIVE, ITS SUPPLIERS, CONTRACT PARTNERS, AFFILIATES, AND THE LIKE (ALTOGETHER THE “GIVE PARTIES”) ARISING FROM OR RELATING TO THIS AGREEMENT OR THE GIVE SERVICES, REGARDLESS OF THE FORM OF ACTION OR CLAIM, WHETHER CONTRACT, WARRANTY, TORT, STRICT LIABILITY, MALPRACTICE, INDEMNITY, AND/OR OTHERWISE, AND WHETHER OR NOT ARISING IN WHOLE OR IN PART FROM THE GIVE PARTIES FAULT, NEGLIGENCE, OR OMISSIONS, SHALL NOT EXCEED THE AMOUNT PAID BY THE USER FOR ONE MONTH ACCESS TO THE GIVE SERVICES MINUS ANY DIGITAL REWARDS GENERATED OR RECEIVED BY THE USER AS A RESULT OF THE USE OF THE GIVE SERVICES. THE GIVE PARTIES SHALL NOT IN ANY CASE BE LIABLE FOR ANY LOST OPPORTUNITY COSTS, SPECIAL, INCIDENTAL, CONSEQUENTIAL, INDIRECT, EXEMPLARY, OR PUNITIVE DAMAGES, EVEN IF THE GIVE PARTIES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES OR SHOULD HAVE KNOWN THAT SUCH DAMAGES WERE POSSIBLE. THE GIVE PARTIES SHALL NOT BE LIABLE TO ANY THIRD PARTY FOR ANY CLAIM, LIABILITY OR DAMAGES RESULTING FROM OR RELATING TO YOUR USE OF THE GIVE SERVICES OR ANY RELIANCE THEREON.")
                .to.contain("THE GIVE PARTIES ARE NOT RESPONSIBLE FOR LOST PROFITS OR REVENUE, LOSS OF USE OF THE GIVE SERVICES, FAILURE OF THE GIVE SERVICES TO OPERATE WITHOUT INTERRUPTION, LOSS OF DATA, COSTS OF RE-CREATING LOST DATA, OR THE COST OF ANY SUBSTITUTE EQUIPMENT OR PROGRAM.")
                .to.contain("THE OFFICERS, DIRECTORS, EMPLOYEES, CONTRACTORS, AGENTS, AND REPRESENTATIVES OF THE GIVE PARTIES ARE NOT PARTIES TO THIS AGREEMENT AND SHALL HAVE NO LIABILITY RELATING TO THIS AGREEMENT OR ITS SUBJECT MATTER. YOU ARE SOLELY RESPONSIBLE AND LIABLE FOR YOUR SUE AND RELIANCE ON THE GIVE SERVICES.")
                .to.contain("YOU ACKNOWLEDGE THAT YOU HAVE READ AND UNDERSTAND THIS AGREEMENT AND THIS AGREEMENT IS CONDITIONED ON YOUR REPRESENTATION THAT YOU HAVE ACCEPTED AND AGREE TO BE BOUND BY THIS AGREEMENT AND THESE PROVISIONS AND DISCLAIMERS. THIS LIMITATION OF LIABILITY DOES NOT APPLY TO VIOLATIONS OF THE GIVE PARTIES’ INTELLECTUAL PROPERTY RIGHTS OR THE USER’S PAYMENT OBLIGATIONS.")
        }) 
    })

    it('Expecting/Asserting Section 11 INDEMNIFICATION text:', () => {

        cy.get('p').should(($terms_para) => {
            expect($terms_para.eq(89), 'First paragraph text')
                .to.contain("11. INDEMNIFICATION")
            expect($terms_para.eq(90), 'First paragraph text')
                .to.contain("User agrees to indemnify and hold harmless GIVE, including its affiliates, and GIVE Services from and against any loss, cost, or expense incurred as a consequence of any breach of warranty or representation hereunder by User.")
                .to.contain("Additionally, User will defend, hold harmless, and indemnify GIVE and its affiliates against any settlement amounts approved by the User and damages and costs finally awarded against the User and its affiliates by a court of competent jurisdiction in any formal legal proceeding filed by an unaffiliated third party before a court or government tribunal (including any appellate proceeding) to the extent arising from the User’s use of GIVE’s Services.")
        }) 
    })

    it('Expecting/Asserting Section 12 CONFIDENTIAL INFORMATION text:', () => {

        cy.get('p').should(($terms_para) => {
            expect($terms_para.eq(91), 'First paragraph text')
                .to.contain("12. Confidential Information.")
            expect($terms_para.eq(92), 'First paragraph text')
                .to.contain("The User may be exposed to GIVE’s (and other affiliated or third party blockchain protocols) Confidential Information.")
                .to.contain("“Confidential Information” means any information, in any form or medium, whether marked confidential or not, disclosed")
                .to.contain("to the Contractor under this agreement, including, but not limited to, proprietary information, products, protocols, standards, manuals, services, business plans, customer lists, know-how, trade secrets, intellectual property rights, technical specifications, source code, object code, screen displays, designs, flowcharts, drawings, processes, algorithms, software programs, databases, marketing plans, articles, strategic direction, price lists, financial information or projections, notes, memoranda, extracts, summaries, reports, and/or analysis, including any and all derivative works of the aforementioned. Confidential Information shall not include information that is: (a) in the public domain, or subsequently becomes in the public domain, other than by breach of this or another agreement; (b) lawfully disclosed by a third party on a non-confidential basis to User, provided that the third party did not directly or indirectly receive the item from GIVE; or (c) independently developed by the User without access to GIVE’s Confidential Information and all such development efforts can be clearly documented by User.")
            expect($terms_para.eq(93), 'First paragraph text')
                .to.contain("User acknowledges that all Confidential Information is and shall continue to be the exclusive property of GIVE.")
                .to.contain("User agrees to hold all Confidential Information received from GIVE in trust and confidence and agrees that such information shall be used only for the purposes of this agreement. ")
                .to.contain("User shall not disclose, directly or indirectly, the Confidential Information to any third parties, or otherwise use the Confidential Information in a manner detrimental to GIVE.")
                .to.contain("User shall not make copies of any documents containing Confidential Information or disassemble, decompile, publicly display, distribute, create derivatives, or reverse engineer any materials, items, or products provided by the GIVE. User understands that all Confidential Information is important, unique, and materially affects GIVE’s goodwill and success in conducting its business activities, and hereby agrees to indemnify and save harmless GIVE for damages that may arise from the unauthorized disclosure of Confidential Information by the User. This agreement extends to Confidential Information that may have been previously disclosed to Contractor prior to the execution of this Agreement.")
            expect($terms_para.eq(94), 'First paragraph text')
                .to.contain("User may be exposed to other third parties confidential or proprietary information.")
                .to.contain("User will safeguard and keep confidential the confidential or proprietary information of customers, vendors, contractors, and other parties with which GIVE does business to the same extent as if it were GIVEs Confidential Information and the prohibitions and restrictions herein apply equally to third parties confidential and proprietary information received by User pursuant to this agreement as if it were GIVEs Confidential Information.")
            expect($terms_para.eq(95), 'First paragraph text')
                .to.contain("User shall immediately inform GIVE, in writing, of any misappropriation, unauthorized use, or disclosure of Confidential Information and will cooperate in every reasonable way to prevent further disclosure and to obtain possession of the misappropriated Confidential Information.")
            expect($terms_para.eq(96), 'First paragraph text')
                .to.contain("Upon written request from GIVE, user shall return to GIVE (or destroy upon the request of the GIVE) all Confidential Information received by User.")
        }) 
    })

    it('Expecting/Asserting Section 13 MISCELLANEOUS text:', () => {

        cy.get('p').should(($terms_para) => {
            expect($terms_para.eq(97), 'First paragraph text')
                .to.contain("13. MISCELLANEOUS.")
            expect($terms_para.eq(98), 'First paragraph text')
                .to.contain("13.1. Assignment.")
            expect($terms_para.eq(99), 'First paragraph text')
                .to.contain("The User will not assign or otherwise transfer the User’s rights and obligations under these Terms & Conditions, without the prior written consent of GIVE, which may be unreasonably withheld. Any assignment or transfer in violation of this section will be void. At any time and without the need for User’s consent, GIVE may assign any obligation, right and these Terms & Conditions. Subject to the foregoing, these Terms & Conditions will be binding upon, and inure to the benefit of the parties and their respective permitted successors and assigns. The User may not merge these Terms & Conditions with any other agreements with which GIVE may be a party.")
            expect($terms_para.eq(100), 'First paragraph text')
                .to.contain("13.2. Disputes.")
            expect($terms_para.eq(101), 'First paragraph text')
                .to.contain("Any dispute, controversy, difference or claim arising out of or relating to these Terms & Conditions or relating in any way to the User’s use of GIVE Sites or GIVE Services, including the existence, validity, interpretation, performance, breach or termination thereof or any dispute regarding any contractual or non-contractual obligations arising out of or relating to these Terms & Conditions shall be commenced only in a court in the State of Wyoming (federal or state), and the User and GIVE each consent to the exclusive subject matter and personal jurisdiction of such Courts.")
                .to.contain("Notwithstanding the foregoing GIVE and the User agree that GIVE may bring suit in court to enjoin infringement or other misuse of GIVE’s intellectual property rights. The prevailing party in any court action shall be entitled to costs and reasonable attorneys’ fees. CLASS ACTION WAIVER: TO THE EXTENT PERMISSIBLE BY LAW, ALL CLAIMS MUST BE BROUGHT IN A PARTY’S INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS, COLLECTIVE ACTION, OR REPRESENTATIVE PROCEEDING (COLLECTIVELY “CLASS ACTION WAIVER”). THE ARBITRATOR MAY NOT CONSOLIDATE MORE THAN ONE PERSON’S CLAIMS OR ENGAGE IN ANY CLASS ARBITRATION. CUSTOMER ACKNOWLEDGES THAT, BY AGREEING TO THESE TERMS, EACH PARTY WAIVES THE RIGHT TO A TRIAL BY JURY AND THE RIGHT TO PARTICIPATE IN A CLASS ACTION.")
            expect($terms_para.eq(102), 'First paragraph text')
                .to.contain("13.3. Entire Agreement.")
            expect($terms_para.eq(103), 'First paragraph text')
                .to.contain("These Terms & Conditions and Privacy Policy sets out all the terms agreed between the parties and supersedes all other agreements between the parties relating to its subject matter. In entering into these Terms & Conditions, neither party has relied on, and neither party will have any right or remedy based on, any statement, representation or warranty (whether made negligently or innocently), except those expressly set out in these Terms & Conditions and Privacy Policy. The terms may be updated on GIVE sites.")
            expect($terms_para.eq(104), 'First paragraph text')
                .to.contain("13.4. Force Majeure.")
            expect($terms_para.eq(105), 'First paragraph text')
                .to.contain("GIVE and its affiliates will not be liable for any failure or delay in performance of obligation under these Terms & Conditions where the failures or delay results from any cause beyond reasonable control, including, but not limited to, acts of God, labor disputes or other industrial disturbances, electrical or power outages, utilities or other telecommunications failures, earthquake, storms or other elements of nature, blockages, embargoes, riots, acts or orders of government, acts of terrorism, or war. Force Majeure events include, but are not limited to, upgrades to the validation rules of a given blockchain (e.g., a “hard fork” or “soft fork”).")
            expect($terms_para.eq(106), 'First paragraph text')
                .to.contain("13.5. Governing Law.")
            expect($terms_para.eq(107), 'First paragraph text')
                .to.contain("Any claim or dispute between the User and GIVE arising out of or relating to the User’s use of GIVE sites, GIVE Services, or these Terms & Conditions, in whole or in part, shall be governed by the laws of the State of Wyoming, USA without respect to its conflict of laws provisions. The 1980 United Nations Conventions on Contracts for the International Sale of Goods does not govern these Terms & Conditions.")
            expect($terms_para.eq(108), 'First paragraph text')
                .to.contain("13.6. Language.")
            expect($terms_para.eq(109), 'First paragraph text')
                .to.contain("All communications and notices made or given pursuant to these Terms & Conditions must be in the English language. If we provide a translation of the English language version of these Terms & Conditions, the English language version will control if there is any conflict.")
            expect($terms_para.eq(110), 'First paragraph text')
                .to.contain("13.7. Notices to the User and GIVE.")
            expect($terms_para.eq(111), 'First paragraph text')
                .to.contain("GIVE may provide any notice to the User under these Terms & Conditions by: (i) posting a notice on GIVE Site; or (ii) sending a message to the email address associated with the User’s account. Notices provided on GIVE Site will be effective upon posting and notices provided by email will be effective when the email is sent. It is the User’s responsibility to keep the User’s email address current. To give GIVE notice under these Terms & Conditions, the User must contact GIVE.")
                .to.contain("GIVE may update the address for notices by posting on the GIVE Site.")
            expect($terms_para.eq(112), 'First paragraph text')
                .to.contain("13.8. Severability.")
            expect($terms_para.eq(113), 'First paragraph text')
                .to.contain("If any portion of these Terms & Conditions is held to be invalid or unenforceable, the remaining portions will remain in full force and effect.")
            expect($terms_para.eq(114), 'First paragraph text')
                .to.contain("13.9 No Third-Party Beneficiaries")
            expect($terms_para.eq(115), 'First paragraph text')
                .to.contain("These terms of service are for the sole benefit of the parties hereto and nothing herein, express or implied, is intended to or shall confer upon any other person or entity any legal or equitable right, benefit, or remedy of any nature whatsoever under or by reason of this agreement.")
            expect($terms_para.eq(116), 'First paragraph text')
                .to.contain("13.10 Relationship")
            expect($terms_para.eq(117), 'First paragraph text')
                .to.contain("Nothing herein shall be construed to create a joint venture or partnership between the parties hereto or an employer/employee or agency relationship. Neither party hereto shall have any express or implied right or authority to assume or create any obligations on behalf of or in the name of the other party or to bind the other party to any contract, agreement, or undertaking with any third party.")
        }) 
    })
})

