/// <reference types="cypress" />

describe('Login', () => {
    beforeEach(() => {
        cy.wordpresslogin(Cypress.env('email'), Cypress.env('password'));
        cy.visit("https://giveblockchain.io/save-funnel/")
        cy.url()
            .should("include", "/save-funnel/")
    })

    it('Expecting/Asserting all text on the page', () => {
        cy.get('h1').should(($h1) => {
            expect($h1.eq(0), 'h1 First Title')
                .to.contain("Protecting Children")
        }) 

        cy.get('h2').should(($h2) => {
            expect($h2.eq(0), 'h2 First Title')
                .to.contain('HOW WE WORK')
            expect($h2.eq(1), 'h2 Second Title')
                .to.contain('Are you ready to')
            expect($h2.eq(2), 'h2 Third Title')
                .to.contain('Are you ready to')
        })

        cy.get('h3').should(($h3) => {
            expect($h3.eq(0), 'H3 First Title')
                .to.contain('OUR MISSION')
            expect($h3.eq(1), 'H3 Second Title')
                .to.contain('OUR VISION')
            expect($h3.eq(2), 'H3 Third Title')
                .to.contain('WHAT CAN WE DO?')
        }) 

        cy.get('h4').should(($h4) => {
            expect($h4.eq(0), 'h4 First title text')
                .to.contain("The global Give community is working with some of the world's top nonprofit foundations and charities to fight against human trafficking. We invite you to join us in our pursuit toward ending this evil scourge and human suffering.")
            expect($h4.eq(1), 'h4 Second title text')
                .to.contain("Rescue")
            expect($h4.eq(2), 'h4 Third title text')
                .to.contain("Aftercare")
            expect($h4.eq(3), 'h4 Fourth title text')
                .to.contain("Fighting Impunity")
            expect($h4.eq(4), 'h4 Fifth title text')
                .to.contain("Special Programs")
        })

        cy.get('p').should(($features_para) => {
            expect($features_para.eq(0), 'First paragraph text')
                .to.contain("Step 1")
            expect($features_para.eq(1), 'Second paragraph text')
                .to.contain("We support activist organizations around the world that work tirelessly to rescue girls from situations of sexual exploitation. Our rescue teams work with local police to break down the doors of the brothel, karaoke bar or dance club in order to rescue the girls.")
            expect($features_para.eq(2), 'Third paragraph text')
                .to.contain("Step 2")            
            expect($features_para.eq(3), 'Fourth paragraph text')
                .to.contain("We ensure that the victims end up in a safe situation. They are also given acute medical care and psychological assistance to process their traumas, and to prevent them from becoming victims again.")
            expect($features_para.eq(4), 'Fifth paragraph text')
                .to.contain("Step 3")
            expect($features_para.eq(5), 'Sixth paragraph text')
                .to.contain("In order to bring about lasting change, we are working with local project partners to provide legal support to victims, lobby and advocate to improve legislation, and train the police and judiciary to fight child sexual exploitation.")            
            expect($features_para.eq(6), 'Seventh paragraph text')
                .to.contain("Step 4")            
            expect($features_para.eq(7), 'Eigth paragraph text')
                .to.contain("We work with local organizations and support their activities by facilitating the exchange of knowledge. We also help and support victims to gain an education and contribute to fight impunity.")            
            expect($features_para.eq(8), 'Ninth paragraph text')
                .to.contain("Contribute to Protecting Children.")
            expect($features_para.eq(9), 'Tenth paragraph text')
                .to.contain("Two million children around the world, mostly girls, are trapped in sexually exploitative situations. They are locked up and exploited in brothels, massage parlors or garages, among other places. Our mission is to create a world without commercial exploitation of children by offering victims immediate assistance and tackling impunity.")
            expect($features_para.eq(10), 'Eleventh paragraph text')
                .to.contain("We strive for a world free of sexual exploitation of children. Every child has the right to grow up in a safe environment. All children around the world must be protected against every form of exploitation.")  
            expect($features_para.eq(11), 'Twelth paragraph text')
                .to.contain("With your generous gift, we can fund specific needs:") 
            expect($features_para.eq(12), 'Thirteenth paragraph text')
                .to.contain("For $ 5, we can provide a rescued girl with a water bottle, clothes and medical supplies;") 
            expect($features_para.eq(13), 'Fourteenth paragraph text')
                .to.contain("Contribute to Protecting Children.")             
        })

        cy.get('[class="nectar-button large regular has-icon regular-button"]').should(($button) => {
            expect($button.eq(0), 'First button text')
                .to.contain("GIVE NOW")
                .to.have.attr('href', '/protecting-children-donate/')
            expect($button.eq(1), 'Second button text')
                .to.contain("GIVE NOW") 
                .to.have.attr('href', '/protecting-children-donate/')
            expect($button.eq(2), 'Second button text')
                .to.contain("GIVE NOW")
                .to.have.attr('href', '/protecting-children-donate/') 
            expect($button.eq(3), 'Second button text')
                .to.contain("GIVE NOW")
                .to.have.attr('href', '/protecting-children-donate/') 
            expect($button.eq(4), 'Second button text')
                .to.contain("GIVE NOW")
                .to.have.attr('href', '/protecting-children-donate/')      
            expect($button.eq(5), 'Second button text')
                .to.contain("GIVE NOW")
                .to.have.attr('href', '/protecting-children-donate/')           
        }) 
    })

    it('Expecting/Asserting button clicks are working and accurate', () => {
        cy.get('[class="nectar-button large regular has-icon regular-button"]')
            .eq(0)
            .click()
        cy.url()
            .should('include', "/protecting-children-donate/")
        cy.go('back')
        cy.get('[class="nectar-button large regular has-icon regular-button"]')
            .eq(1)
            .click()
        cy.url()
            .should('include', "/protecting-children-donate/")
        cy.go('back')
        cy.get('[class="nectar-button large regular has-icon regular-button"]')
            .eq(2)
            .click()
        cy.url()
            .should('include', '/protecting-children-donate/')
        cy.go('back')
        cy.get('[class="nectar-button large regular has-icon regular-button"]')
            .eq(3)
            .click()
        cy.url()
            .should('include', '/protecting-children-donate/')
        cy.go('back')
        cy.get('[class="nectar-button large regular has-icon regular-button"]')
            .eq(4)
            .click()
        cy.url()
            .should('include', "/protecting-children-donate/")
        cy.go('back')
        cy.get('[class="nectar-button large regular has-icon regular-button"]')
            .eq(5)
            .click()
        cy.url()
            .should('include', "/protecting-children-donate/")
        cy.go('back')
    })
})