/// <reference types="cypress" />

describe('Login', () => {

    it('Document Test - iPhone-8-portrait', () => {
        cy.viewport('iphone-8', 'portrait')
        cy.wordpresslogin(Cypress.env('email'), Cypress.env('password')) 
        cy.document().should(doc => {
            const titleText = doc.title
                expect(titleText).to.eql('Dashboard - Give')
                expect(titleText).to.not.eql('Give')

            const domain = doc.domainName
                expect(domainName).to.eql('giveblockchain.io')
                expect(domainName).to.not.eql('giveblockchain.com')

        })

        cy.get('h3').should(($h3) => {
            expect($h3.eq(0), 'H3 First Title')
                .to.contain("Notice")
        }) 

        cy.get('h6').should(($h6) => {
            expect($h6.eq(0), 'First title text')
                .to.contain("MY BALANCE")
            expect($h6.eq(1), 'Second title text')
                .to.contain("MY LICENSES")
            expect($h6.eq(2), 'Third title text')
                .to.contain("MY VAULT")
            expect($h6.eq(3), 'Fourth title text')
                .to.contain("SHARE GIVE")
            expect($h6.eq(4), 'Fifth title text')
                .to.contain("NODE (COMING SOON)")
            expect($h6.eq(5), 'Sixth title text')
                .to.contain("SMART NODE (COMING SOON)")
            expect($h6.eq(6), 'Seventh title text')
                .to.contain("DOWNLOAD NODE SOFTWARE")
            expect($h6.eq(7), 'Eigth title text')
                .to.contain("LET’S GIVE (UNDERGOING IMPROVEMENTS )")
            expect($h6.eq(8), 'Ninth title text')
                .to.contain("DOWNLOAD NODE SOFTWARE NOW")
            expect($h6.eq(9), 'tenth title text')
                .to.contain("SETUP VPS (COMING SOON)")    
        }) 

        cy.get('p').should(($para) => {
            expect($para.eq(0), 'First paragraph text')
                .to.contain("Your Node and Smart Node licenses will be available in your app in 30-180 days from purchase.")
            expect($para.eq(1), 'Second paragraph text')
                .to.contain("Download Give Node Software. Works with Give Node and Give Smart Node Licences.")            
            expect($para.eq(2), 'Third paragraph text')
                .to.contain("You must fill out the Terms and Conditions before installing any software.")                    
        }) 

        cy.get('[class="column-link"]')
            .eq(0)
            .click()
        cy.url().should('include', "app.giveblockchain.io/inventory/")
        cy.get('[class="v-card__title"]').should(($balances_title) =>  {
            expect($balances_title.eq(0), 'First title text')
                .to.contain("Balances")
        })
        cy.go('back')
        cy.get('[class="column-link"]')
            .eq(1)
            .click()
        cy.url().should('include', "app.giveblockchain.io/nodes/")
        cy.get('[class="v-card__title text-capitalize"]').should(($node_title) =>  {
            expect($node_title.eq(0), 'First title text')
                .to.contain("give Node Info")
        })
        cy.go('back')
        cy.get('[class="column-link"]')
            .eq(2)
            .click()
        cy.url().should('include', "app.giveblockchain.io/vault/")
        cy.get('[class="v-card__title"]')
            .should('have.text', "Vault Items")
        cy.go('back')
        cy.get('[class="column-link"]')
            .eq(3)
            .click()
        cy.url().should('include', "app.giveblockchain.io/social/")
        cy.get('[class="v-card__title text-h6 text-sm-h5"]').should(($share_title) =>  {
            expect($share_title.eq(0), 'First title text')
                .to.contain("Share with your Friends!")
        })
        cy.go('back')
        cy.get('[class="column-link"]')
            .eq(4)
            .click()
        cy.url().should('include', "giveblockchain.io/dashboard/#download")
    })

    it('Document Test - iPhone-x-portrait', () => {
        cy.viewport('iphone-x', 'portrait')
        cy.wordpresslogin(Cypress.env('email'), Cypress.env('password')) 
        cy.document().should(doc => {
            const titleText = doc.title
            expect(titleText).to.eql('Dashboard - Give')
            expect(titleText).to.not.eql('Give')
        })

        cy.get('h3').should(($h3) => {
            expect($h3.eq(0), 'H3 First Title')
                .to.contain("Notice")
        }) 

        cy.get('h6').should(($h6) => {
            expect($h6.eq(0), 'First title text')
                .to.contain("MY BALANCE")
            expect($h6.eq(1), 'Second title text')
                .to.contain("MY LICENSES")
            expect($h6.eq(2), 'Third title text')
                .to.contain("MY VAULT")
            expect($h6.eq(3), 'Fourth title text')
                .to.contain("SHARE GIVE")
            expect($h6.eq(4), 'Fifth title text')
                .to.contain("NODE (COMING SOON)")
            expect($h6.eq(5), 'Sixth title text')
                .to.contain("SMART NODE (COMING SOON)")
            expect($h6.eq(6), 'Seventh title text')
                .to.contain("DOWNLOAD NODE SOFTWARE")
            expect($h6.eq(7), 'Eigth title text')
                .to.contain("LET’S GIVE (UNDERGOING IMPROVEMENTS )")
            expect($h6.eq(8), 'Ninth title text')
                .to.contain("DOWNLOAD NODE SOFTWARE NOW")
            expect($h6.eq(9), 'tenth title text')
                .to.contain("SETUP VPS (COMING SOON)")    
        }) 

        cy.get('p').should(($para) => {
            expect($para.eq(0), 'First paragraph text')
                .to.contain("Your Node and Smart Node licenses will be available in your app in 30-180 days from purchase.")
            expect($para.eq(1), 'Second paragraph text')
                .to.contain("Download Give Node Software. Works with Give Node and Give Smart Node Licences.")            
            expect($para.eq(2), 'Third paragraph text')
                .to.contain("You must fill out the Terms and Conditions before installing any software.")                    
        }) 

        cy.get('[class="column-link"]')
            .eq(0)
            .click()
        cy.url().should('include', "app.giveblockchain.io/inventory/")
        cy.get('[class="v-card__title"]').should(($balances_title) =>  {
            expect($balances_title.eq(0), 'First title text')
                .to.contain("Balances")
        })
        cy.go('back')
        cy.get('[class="column-link"]')
            .eq(1)
            .click()
        cy.url().should('include', "app.giveblockchain.io/nodes/")
        cy.get('[class="v-card__title text-capitalize"]').should(($node_title) =>  {
            expect($node_title.eq(0), 'First title text')
                .to.contain("give Node Info")
        })
        cy.go('back')
        cy.get('[class="column-link"]')
            .eq(2)
            .click()
        cy.url().should('include', "app.giveblockchain.io/vault/")
        cy.get('[class="v-card__title"]')
            .should('have.text', "Vault Items")
        cy.go('back')
        cy.get('[class="column-link"]')
            .eq(3)
            .click()
        cy.url().should('include', "app.giveblockchain.io/social/")
        cy.get('[class="v-card__title text-h6 text-sm-h5"]').should(($share_title) =>  {
            expect($share_title.eq(0), 'First title text')
                .to.contain("Share with your Friends!")
        })
        cy.go('back')
        cy.get('[class="column-link"]')
            .eq(4)
            .click()
        cy.url().should('include', "giveblockchain.io/dashboard/#download")
    })

    it('Document Test - iPad-mini-landscape', () => {
        cy.viewport('ipad-mini', 'landscape')
        cy.wordpresslogin(Cypress.env('email'), Cypress.env('password')) 
        cy.document().should(doc => {
            const titleText = doc.title
            expect(titleText).to.eql('Dashboard - Give')
            expect(titleText).to.not.eql('Give')
        })

        cy.get('h3').should(($h3) => {
            expect($h3.eq(0), 'H3 First Title')
                .to.contain("Notice")
        }) 

        cy.get('h6').should(($h6) => {
            expect($h6.eq(0), 'First title text')
                .to.contain("MY BALANCE")
            expect($h6.eq(1), 'Second title text')
                .to.contain("MY LICENSES")
            expect($h6.eq(2), 'Third title text')
                .to.contain("MY VAULT")
            expect($h6.eq(3), 'Fourth title text')
                .to.contain("SHARE GIVE")
            expect($h6.eq(4), 'Fifth title text')
                .to.contain("NODE (COMING SOON)")
            expect($h6.eq(5), 'Sixth title text')
                .to.contain("SMART NODE (COMING SOON)")
            expect($h6.eq(6), 'Seventh title text')
                .to.contain("DOWNLOAD NODE SOFTWARE")
            expect($h6.eq(7), 'Eigth title text')
                .to.contain("LET’S GIVE (UNDERGOING IMPROVEMENTS )")
            expect($h6.eq(8), 'Ninth title text')
                .to.contain("DOWNLOAD NODE SOFTWARE NOW")
            expect($h6.eq(9), 'tenth title text')
                .to.contain("SETUP VPS (COMING SOON)")    
        }) 

        cy.get('p').should(($para) => {
            expect($para.eq(0), 'First paragraph text')
                .to.contain("Your Node and Smart Node licenses will be available in your app in 30-180 days from purchase.")
            expect($para.eq(1), 'Second paragraph text')
                .to.contain("Download Give Node Software. Works with Give Node and Give Smart Node Licences.")            
            expect($para.eq(2), 'Third paragraph text')
                .to.contain("You must fill out the Terms and Conditions before installing any software.")                    
        }) 

        cy.get('[class="column-link"]')
            .eq(0)
            .click()
        cy.url().should('include', "app.giveblockchain.io/inventory/")
        cy.get('[class="v-card__title"]').should(($balances_title) =>  {
            expect($balances_title.eq(0), 'First title text')
                .to.contain("Balances")
        })
        cy.go('back')
        cy.get('[class="column-link"]')
            .eq(1)
            .click()
        cy.url().should('include', "app.giveblockchain.io/nodes/")
        cy.get('[class="v-card__title text-capitalize"]').should(($node_title) =>  {
            expect($node_title.eq(0), 'First title text')
                .to.contain("give Node Info")
        })
        cy.go('back')
        cy.get('[class="column-link"]')
            .eq(2)
            .click()
        cy.url().should('include', "app.giveblockchain.io/vault/")
        cy.get('[class="v-card__title"]')
            .should('have.text', "Vault Items")
        cy.go('back')
        cy.get('[class="column-link"]')
            .eq(3)
            .click()
        cy.url().should('include', "app.giveblockchain.io/social/")
        cy.get('[class="v-card__title text-h6 text-sm-h5"]').should(($share_title) =>  {
            expect($share_title.eq(0), 'First title text')
                .to.contain("Share with your Friends!")
        })
        cy.go('back')
        cy.get('[class="column-link"]')
            .eq(4)
            .click()
        cy.url().should('include', "giveblockchain.io/dashboard/#download")
    })

    it('Document Test - iPad-2-landscape', () => {
        cy.viewport('ipad-2', 'landscape')
        cy.wordpresslogin(Cypress.env('email'), Cypress.env('password')) 
        cy.document().should(doc => {
            const titleText = doc.title
            expect(titleText).to.eql('Dashboard - Give')
            expect(titleText).to.not.eql('Give')
        })

        cy.get('h3').should(($h3) => {
            expect($h3.eq(0), 'H3 First Title')
                .to.contain("Notice")
        }) 

        cy.get('h6').should(($h6) => {
            expect($h6.eq(0), 'First title text')
                .to.contain("MY BALANCE")
            expect($h6.eq(1), 'Second title text')
                .to.contain("MY LICENSES")
            expect($h6.eq(2), 'Third title text')
                .to.contain("MY VAULT")
            expect($h6.eq(3), 'Fourth title text')
                .to.contain("SHARE GIVE")
            expect($h6.eq(4), 'Fifth title text')
                .to.contain("NODE (COMING SOON)")
            expect($h6.eq(5), 'Sixth title text')
                .to.contain("SMART NODE (COMING SOON)")
            expect($h6.eq(6), 'Seventh title text')
                .to.contain("DOWNLOAD NODE SOFTWARE")
            expect($h6.eq(7), 'Eigth title text')
                .to.contain("LET’S GIVE (UNDERGOING IMPROVEMENTS )")
            expect($h6.eq(8), 'Ninth title text')
                .to.contain("DOWNLOAD NODE SOFTWARE NOW")
            expect($h6.eq(9), 'tenth title text')
                .to.contain("SETUP VPS (COMING SOON)")    
        }) 

        cy.get('p').should(($para) => {
            expect($para.eq(0), 'First paragraph text')
                .to.contain("Your Node and Smart Node licenses will be available in your app in 30-180 days from purchase.")
            expect($para.eq(1), 'Second paragraph text')
                .to.contain("Download Give Node Software. Works with Give Node and Give Smart Node Licences.")            
            expect($para.eq(2), 'Third paragraph text')
                .to.contain("You must fill out the Terms and Conditions before installing any software.")                    
        }) 

        cy.get('[class="column-link"]')
            .eq(0)
            .click()
        cy.url().should('include', "app.giveblockchain.io/inventory/")
        cy.get('[class="v-card__title"]').should(($balances_title) =>  {
            expect($balances_title.eq(0), 'First title text')
                .to.contain("Balances")
        })
        cy.go('back')
        cy.get('[class="column-link"]')
            .eq(1)
            .click()
        cy.url().should('include', "app.giveblockchain.io/nodes/")
        cy.get('[class="v-card__title text-capitalize"]').should(($node_title) =>  {
            expect($node_title.eq(0), 'First title text')
                .to.contain("give Node Info")
        })
        cy.go('back')
        cy.get('[class="column-link"]')
            .eq(2)
            .click()
        cy.url().should('include', "app.giveblockchain.io/vault/")
        cy.get('[class="v-card__title"]')
            .should('have.text', "Vault Items")
        cy.go('back')
        cy.get('[class="column-link"]')
            .eq(3)
            .click()
        cy.url().should('include', "app.giveblockchain.io/social/")
        cy.get('[class="v-card__title text-h6 text-sm-h5"]').should(($share_title) =>  {
            expect($share_title.eq(0), 'First title text')
                .to.contain("Share with your Friends!")
        })
        cy.go('back')
        cy.get('[class="column-link"]')
            .eq(4)
            .click()
        cy.url().should('include', "giveblockchain.io/dashboard/#download")
    })

    it('Document Test - SamsungS10-portrait', () => {
        cy.viewport('samsung-s10', 'portrait')
        cy.wordpresslogin(Cypress.env('email'), Cypress.env('password')) 
        cy.document().should(doc => {
            const titleText = doc.title
            expect(titleText).to.eql('Dashboard - Give')
            expect(titleText).to.not.eql('Give')
        })

        cy.get('h3').should(($h3) => {
            expect($h3.eq(0), 'H3 First Title')
                .to.contain("Notice")
        }) 

        cy.get('h6').should(($h6) => {
            expect($h6.eq(0), 'First title text')
                .to.contain("MY BALANCE")
            expect($h6.eq(1), 'Second title text')
                .to.contain("MY LICENSES")
            expect($h6.eq(2), 'Third title text')
                .to.contain("MY VAULT")
            expect($h6.eq(3), 'Fourth title text')
                .to.contain("SHARE GIVE")
            expect($h6.eq(4), 'Fifth title text')
                .to.contain("NODE (COMING SOON)")
            expect($h6.eq(5), 'Sixth title text')
                .to.contain("SMART NODE (COMING SOON)")
            expect($h6.eq(6), 'Seventh title text')
                .to.contain("DOWNLOAD NODE SOFTWARE")
            expect($h6.eq(7), 'Eigth title text')
                .to.contain("LET’S GIVE (UNDERGOING IMPROVEMENTS )")
            expect($h6.eq(8), 'Ninth title text')
                .to.contain("DOWNLOAD NODE SOFTWARE NOW")
            expect($h6.eq(9), 'tenth title text')
                .to.contain("SETUP VPS (COMING SOON)")    
        }) 

        cy.get('p').should(($para) => {
            expect($para.eq(0), 'First paragraph text')
                .to.contain("Your Node and Smart Node licenses will be available in your app in 30-180 days from purchase.")
            expect($para.eq(1), 'Second paragraph text')
                .to.contain("Download Give Node Software. Works with Give Node and Give Smart Node Licences.")            
            expect($para.eq(2), 'Third paragraph text')
                .to.contain("You must fill out the Terms and Conditions before installing any software.")                    
        }) 

        cy.get('[class="column-link"]')
            .eq(0)
            .click()
        cy.url().should('include', "app.giveblockchain.io/inventory/")
        cy.get('[class="v-card__title"]').should(($balances_title) =>  {
            expect($balances_title.eq(0), 'First title text')
                .to.contain("Balances")
        })
        cy.go('back')
        cy.get('[class="column-link"]')
            .eq(1)
            .click()
        cy.url().should('include', "app.giveblockchain.io/nodes/")
        cy.get('[class="v-card__title text-capitalize"]').should(($node_title) =>  {
            expect($node_title.eq(0), 'First title text')
                .to.contain("give Node Info")
        })
        cy.go('back')
        cy.get('[class="column-link"]')
            .eq(2)
            .click()
        cy.url().should('include', "app.giveblockchain.io/vault/")
        cy.get('[class="v-card__title"]')
            .should('have.text', "Vault Items")
        cy.go('back')
        cy.get('[class="column-link"]')
            .eq(3)
            .click()
        cy.url().should('include', "app.giveblockchain.io/social/")
        cy.get('[class="v-card__title text-h6 text-sm-h5"]').should(($share_title) =>  {
            expect($share_title.eq(0), 'First title text')
                .to.contain("Share with your Friends!")
        })
        cy.go('back')
        cy.get('[class="column-link"]')
            .eq(4)
            .click()
        cy.url().should('include', "giveblockchain.io/dashboard/#download")
    })

    it('Document Test - Samsung-Note9-portrait', () => {
        cy.viewport('samsung-note9', 'portrait')
        cy.wordpresslogin(Cypress.env('email'), Cypress.env('password')) 
        cy.document().should(doc => {
            const titleText = doc.title
            expect(titleText).to.eql('Dashboard - Give')
            expect(titleText).to.not.eql('Give')
        })

        cy.get('h3').should(($h3) => {
            expect($h3.eq(0), 'H3 First Title')
                .to.contain("Notice")
        }) 

        cy.get('h6').should(($h6) => {
            expect($h6.eq(0), 'First title text')
                .to.contain("MY BALANCE")
            expect($h6.eq(1), 'Second title text')
                .to.contain("MY LICENSES")
            expect($h6.eq(2), 'Third title text')
                .to.contain("MY VAULT")
            expect($h6.eq(3), 'Fourth title text')
                .to.contain("SHARE GIVE")
            expect($h6.eq(4), 'Fifth title text')
                .to.contain("NODE (COMING SOON)")
            expect($h6.eq(5), 'Sixth title text')
                .to.contain("SMART NODE (COMING SOON)")
            expect($h6.eq(6), 'Seventh title text')
                .to.contain("DOWNLOAD NODE SOFTWARE")
            expect($h6.eq(7), 'Eigth title text')
                .to.contain("LET’S GIVE (UNDERGOING IMPROVEMENTS )")
            expect($h6.eq(8), 'Ninth title text')
                .to.contain("DOWNLOAD NODE SOFTWARE NOW")
            expect($h6.eq(9), 'tenth title text')
                .to.contain("SETUP VPS (COMING SOON)")    
        }) 

        cy.get('p').should(($para) => {
            expect($para.eq(0), 'First paragraph text')
                .to.contain("Your Node and Smart Node licenses will be available in your app in 30-180 days from purchase.")
            expect($para.eq(1), 'Second paragraph text')
                .to.contain("Download Give Node Software. Works with Give Node and Give Smart Node Licences.")            
            expect($para.eq(2), 'Third paragraph text')
                .to.contain("You must fill out the Terms and Conditions before installing any software.")                    
        }) 

        cy.get('[class="column-link"]')
            .eq(0)
            .click()
        cy.url().should('include', "app.giveblockchain.io/inventory/")
        cy.get('[class="v-card__title"]').should(($balances_title) =>  {
            expect($balances_title.eq(0), 'First title text')
                .to.contain("Balances")
        })
        cy.go('back')
        cy.get('[class="column-link"]')
            .eq(1)
            .click()
        cy.url().should('include', "app.giveblockchain.io/nodes/")
        cy.get('[class="v-card__title text-capitalize"]').should(($node_title) =>  {
            expect($node_title.eq(0), 'First title text')
                .to.contain("give Node Info")
        })
        cy.go('back')
        cy.get('[class="column-link"]')
            .eq(2)
            .click()
        cy.url().should('include', "app.giveblockchain.io/vault/")
        cy.get('[class="v-card__title"]')
            .should('have.text', "Vault Items")
        cy.go('back')
        cy.get('[class="column-link"]')
            .eq(3)
            .click()
        cy.url().should('include', "app.giveblockchain.io/social/")
        cy.get('[class="v-card__title text-h6 text-sm-h5"]').should(($share_title) =>  {
            expect($share_title.eq(0), 'First title text')
                .to.contain("Share with your Friends!")
        })
        cy.go('back')
        cy.get('[class="column-link"]')
            .eq(4)
            .click()
        cy.url().should('include', "giveblockchain.io/dashboard/#download")
    })

    it('Document Test - iPhone12-portrait', () => {
        cy.viewport(390,844, 'portrait')
        cy.wordpresslogin(Cypress.env('email'), Cypress.env('password')) 
        cy.document().should(doc => {
            const titleText = doc.title
            expect(titleText).to.eql('Dashboard - Give')
            expect(titleText).to.not.eql('Give')
        })

        cy.get('h3').should(($h3) => {
            expect($h3.eq(0), 'H3 First Title')
                .to.contain("Notice")
        }) 

        cy.get('h6').should(($h6) => {
            expect($h6.eq(0), 'First title text')
                .to.contain("MY BALANCE")
            expect($h6.eq(1), 'Second title text')
                .to.contain("MY LICENSES")
            expect($h6.eq(2), 'Third title text')
                .to.contain("MY VAULT")
            expect($h6.eq(3), 'Fourth title text')
                .to.contain("SHARE GIVE")
            expect($h6.eq(4), 'Fifth title text')
                .to.contain("NODE (COMING SOON)")
            expect($h6.eq(5), 'Sixth title text')
                .to.contain("SMART NODE (COMING SOON)")
            expect($h6.eq(6), 'Seventh title text')
                .to.contain("DOWNLOAD NODE SOFTWARE")
            expect($h6.eq(7), 'Eigth title text')
                .to.contain("LET’S GIVE (UNDERGOING IMPROVEMENTS )")
            expect($h6.eq(8), 'Ninth title text')
                .to.contain("DOWNLOAD NODE SOFTWARE NOW")
            expect($h6.eq(9), 'tenth title text')
                .to.contain("SETUP VPS (COMING SOON)")    
        }) 

        cy.get('p').should(($para) => {
            expect($para.eq(0), 'First paragraph text')
                .to.contain("Your Node and Smart Node licenses will be available in your app in 30-180 days from purchase.")
            expect($para.eq(1), 'Second paragraph text')
                .to.contain("Download Give Node Software. Works with Give Node and Give Smart Node Licences.")            
            expect($para.eq(2), 'Third paragraph text')
                .to.contain("You must fill out the Terms and Conditions before installing any software.")                    
        }) 

        cy.get('[class="column-link"]')
            .eq(0)
            .click()
        cy.url().should('include', "app.giveblockchain.io/inventory/")
        cy.get('[class="v-card__title"]').should(($balances_title) =>  {
            expect($balances_title.eq(0), 'First title text')
                .to.contain("Balances")
        })
        cy.go('back')
        cy.get('[class="column-link"]')
            .eq(1)
            .click()
        cy.url().should('include', "app.giveblockchain.io/nodes/")
        cy.get('[class="v-card__title text-capitalize"]').should(($node_title) =>  {
            expect($node_title.eq(0), 'First title text')
                .to.contain("give Node Info")
        })
        cy.go('back')
        cy.get('[class="column-link"]')
            .eq(2)
            .click()
        cy.url().should('include', "app.giveblockchain.io/vault/")
        cy.get('[class="v-card__title"]')
            .should('have.text', "Vault Items")
        cy.go('back')
        cy.get('[class="column-link"]')
            .eq(3)
            .click()
        cy.url().should('include', "app.giveblockchain.io/social/")
        cy.get('[class="v-card__title text-h6 text-sm-h5"]').should(($share_title) =>  {
            expect($share_title.eq(0), 'First title text')
                .to.contain("Share with your Friends!")
        })
        cy.go('back')
        cy.get('[class="column-link"]')
            .eq(4)
            .click()
        cy.url().should('include', "giveblockchain.io/dashboard/#download")
    })

    it('Document Test - iPhone12-Mini-portrait', () => {
        cy.viewport(390,780, 'portrait')
        cy.wordpresslogin(Cypress.env('email'), Cypress.env('password')) 
        cy.document().should(doc => {
            const titleText = doc.title
            expect(titleText).to.eql('Dashboard - Give')
            expect(titleText).to.not.eql('Give')
        })

        cy.get('h3').should(($h3) => {
            expect($h3.eq(0), 'H3 First Title')
                .to.contain("Notice")
        }) 

        cy.get('h6').should(($h6) => {
            expect($h6.eq(0), 'First title text')
                .to.contain("MY BALANCE")
            expect($h6.eq(1), 'Second title text')
                .to.contain("MY LICENSES")
            expect($h6.eq(2), 'Third title text')
                .to.contain("MY VAULT")
            expect($h6.eq(3), 'Fourth title text')
                .to.contain("SHARE GIVE")
            expect($h6.eq(4), 'Fifth title text')
                .to.contain("NODE (COMING SOON)")
            expect($h6.eq(5), 'Sixth title text')
                .to.contain("SMART NODE (COMING SOON)")
            expect($h6.eq(6), 'Seventh title text')
                .to.contain("DOWNLOAD NODE SOFTWARE")
            expect($h6.eq(7), 'Eigth title text')
                .to.contain("LET’S GIVE (UNDERGOING IMPROVEMENTS )")
            expect($h6.eq(8), 'Ninth title text')
                .to.contain("DOWNLOAD NODE SOFTWARE NOW")
            expect($h6.eq(9), 'tenth title text')
                .to.contain("SETUP VPS (COMING SOON)")    
        }) 

        cy.get('p').should(($para) => {
            expect($para.eq(0), 'First paragraph text')
                .to.contain("Your Node and Smart Node licenses will be available in your app in 30-180 days from purchase.")
            expect($para.eq(1), 'Second paragraph text')
                .to.contain("Download Give Node Software. Works with Give Node and Give Smart Node Licences.")            
            expect($para.eq(2), 'Third paragraph text')
                .to.contain("You must fill out the Terms and Conditions before installing any software.")                    
        }) 

        cy.get('[class="column-link"]')
            .eq(0)
            .click()
        cy.url().should('include', "app.giveblockchain.io/inventory/")
        cy.get('[class="v-card__title"]').should(($balances_title) =>  {
            expect($balances_title.eq(0), 'First title text')
                .to.contain("Balances")
        })
        cy.go('back')
        cy.get('[class="column-link"]')
            .eq(1)
            .click()
        cy.url().should('include', "app.giveblockchain.io/nodes/")
        cy.get('[class="v-card__title text-capitalize"]').should(($node_title) =>  {
            expect($node_title.eq(0), 'First title text')
                .to.contain("give Node Info")
        })
        cy.go('back')
        cy.get('[class="column-link"]')
            .eq(2)
            .click()
        cy.url().should('include', "app.giveblockchain.io/vault/")
        cy.get('[class="v-card__title"]')
            .should('have.text', "Vault Items")
        cy.go('back')
        cy.get('[class="column-link"]')
            .eq(3)
            .click()
        cy.url().should('include', "app.giveblockchain.io/social/")
        cy.get('[class="v-card__title text-h6 text-sm-h5"]').should(($share_title) =>  {
            expect($share_title.eq(0), 'First title text')
                .to.contain("Share with your Friends!")
        })
        cy.go('back')
        cy.get('[class="column-link"]')
            .eq(4)
            .click()
        cy.url().should('include', "giveblockchain.io/dashboard/#download")
    })

    it('Document Test - iPad-Pro-landscape', () => {
        cy.viewport(1366,1024, 'landscape')
        cy.wordpresslogin(Cypress.env('email'), Cypress.env('password')) 
        cy.document().should(doc => {
            const titleText = doc.title
            expect(titleText).to.eql('Dashboard - Give')
            expect(titleText).to.not.eql('Give')
        })

        cy.get('h3').should(($h3) => {
            expect($h3.eq(0), 'H3 First Title')
                .to.contain("Notice")
        }) 

        cy.get('h6').should(($h6) => {
            expect($h6.eq(0), 'First title text')
                .to.contain("MY BALANCE")
            expect($h6.eq(1), 'Second title text')
                .to.contain("MY LICENSES")
            expect($h6.eq(2), 'Third title text')
                .to.contain("MY VAULT")
            expect($h6.eq(3), 'Fourth title text')
                .to.contain("SHARE GIVE")
            expect($h6.eq(4), 'Fifth title text')
                .to.contain("NODE (COMING SOON)")
            expect($h6.eq(5), 'Sixth title text')
                .to.contain("SMART NODE (COMING SOON)")
            expect($h6.eq(6), 'Seventh title text')
                .to.contain("DOWNLOAD NODE SOFTWARE")
            expect($h6.eq(7), 'Eigth title text')
                .to.contain("LET’S GIVE (UNDERGOING IMPROVEMENTS )")
            expect($h6.eq(8), 'Ninth title text')
                .to.contain("DOWNLOAD NODE SOFTWARE NOW")
            expect($h6.eq(9), 'tenth title text')
                .to.contain("SETUP VPS (COMING SOON)")    
        }) 

        cy.get('p').should(($para) => {
            expect($para.eq(0), 'First paragraph text')
                .to.contain("Your Node and Smart Node licenses will be available in your app in 30-180 days from purchase.")
            expect($para.eq(1), 'Second paragraph text')
                .to.contain("Download Give Node Software. Works with Give Node and Give Smart Node Licences.")            
            expect($para.eq(2), 'Third paragraph text')
                .to.contain("You must fill out the Terms and Conditions before installing any software.")                    
        }) 

        cy.get('[class="column-link"]')
            .eq(0)
            .click()
        cy.url().should('include', "app.giveblockchain.io/inventory/")
        cy.get('[class="v-card__title"]').should(($balances_title) =>  {
            expect($balances_title.eq(0), 'First title text')
                .to.contain("Balances")
        })
        cy.go('back')
        cy.get('[class="column-link"]')
            .eq(1)
            .click()
        cy.url().should('include', "app.giveblockchain.io/nodes/")
        cy.get('[class="v-card__title text-capitalize"]').should(($node_title) =>  {
            expect($node_title.eq(0), 'First title text')
                .to.contain("give Node Info")
        })
        cy.go('back')
        cy.get('[class="column-link"]')
            .eq(2)
            .click()
        cy.url().should('include', "app.giveblockchain.io/vault/")
        cy.get('[class="v-card__title"]')
            .should('have.text', "Vault Items")
        cy.go('back')
        cy.get('[class="column-link"]')
            .eq(3)
            .click()
        cy.url().should('include', "app.giveblockchain.io/social/")
        cy.get('[class="v-card__title text-h6 text-sm-h5"]').should(($share_title) =>  {
            expect($share_title.eq(0), 'First title text')
                .to.contain("Share with your Friends!")
        })
        cy.go('back')
        cy.get('[class="column-link"]')
            .eq(4)
            .click()
        cy.url().should('include', "giveblockchain.io/dashboard/#download")
    })

    it('Document Test - iPad-Pro-portrait', () => {
        cy.viewport(1024,1366, 'portrait')
        cy.wordpresslogin(Cypress.env('email'), Cypress.env('password')) 
        cy.document().should(doc => {
            const titleText = doc.title
            expect(titleText).to.eql('Dashboard - Give')
            expect(titleText).to.not.eql('Give')
        })

        cy.get('h3').should(($h3) => {
            expect($h3.eq(0), 'H3 First Title')
                .to.contain("Notice")
        }) 

        cy.get('h6').should(($h6) => {
            expect($h6.eq(0), 'First title text')
                .to.contain("MY BALANCE")
            expect($h6.eq(1), 'Second title text')
                .to.contain("MY LICENSES")
            expect($h6.eq(2), 'Third title text')
                .to.contain("MY VAULT")
            expect($h6.eq(3), 'Fourth title text')
                .to.contain("SHARE GIVE")
            expect($h6.eq(4), 'Fifth title text')
                .to.contain("NODE (COMING SOON)")
            expect($h6.eq(5), 'Sixth title text')
                .to.contain("SMART NODE (COMING SOON)")
            expect($h6.eq(6), 'Seventh title text')
                .to.contain("DOWNLOAD NODE SOFTWARE")
            expect($h6.eq(7), 'Eigth title text')
                .to.contain("LET’S GIVE (UNDERGOING IMPROVEMENTS )")
            expect($h6.eq(8), 'Ninth title text')
                .to.contain("DOWNLOAD NODE SOFTWARE NOW")
            expect($h6.eq(9), 'tenth title text')
                .to.contain("SETUP VPS (COMING SOON)")    
        }) 

        cy.get('p').should(($para) => {
            expect($para.eq(0), 'First paragraph text')
                .to.contain("Your Node and Smart Node licenses will be available in your app in 30-180 days from purchase.")
            expect($para.eq(1), 'Second paragraph text')
                .to.contain("Download Give Node Software. Works with Give Node and Give Smart Node Licences.")            
            expect($para.eq(2), 'Third paragraph text')
                .to.contain("You must fill out the Terms and Conditions before installing any software.")                    
        }) 

        cy.get('[class="column-link"]')
            .eq(0)
            .click()
        cy.url().should('include', "app.giveblockchain.io/inventory/")
        cy.get('[class="v-card__title"]').should(($balances_title) =>  {
            expect($balances_title.eq(0), 'First title text')
                .to.contain("Balances")
        })
        cy.go('back')
        cy.get('[class="column-link"]')
            .eq(1)
            .click()
        cy.url().should('include', "app.giveblockchain.io/nodes/")
        cy.get('[class="v-card__title text-capitalize"]').should(($node_title) =>  {
            expect($node_title.eq(0), 'First title text')
                .to.contain("give Node Info")
        })
        cy.go('back')
        cy.get('[class="column-link"]')
            .eq(2)
            .click()
        cy.url().should('include', "app.giveblockchain.io/vault/")
        cy.get('[class="v-card__title"]')
            .should('have.text', "Vault Items")
        cy.go('back')
        cy.get('[class="column-link"]')
            .eq(3)
            .click()
        cy.url().should('include', "app.giveblockchain.io/social/")
        cy.get('[class="v-card__title text-h6 text-sm-h5"]').should(($share_title) =>  {
            expect($share_title.eq(0), 'First title text')
                .to.contain("Share with your Friends!")
        })
        cy.go('back')
        cy.get('[class="column-link"]')
            .eq(4)
            .click()
        cy.url().should('include', "giveblockchain.io/dashboard/#download")
    })

})