/// <reference types="cypress" />

describe('Login', () => {
    beforeEach(() => {
        cy.login(Cypress.env('email'), Cypress.env('password'));
        cy.wait(500)   
      })

    it('Document Test - iPhone-8-portrait', () => {
        cy.viewport('iphone-8', 'portrait')
        // WordPress log in logs you into the Dashboard rather than Summary or Balances
        // This sections covers the chevron clicks making sure they open correctly
        cy.get("#menu-icon")
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(0)
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(1)
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(2)
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(3)
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(4)
            .click();
        // This section covers the Share link and page content
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(0)
            .click();
        cy.get("[class='v-list-item__title']")
            .eq(0)
            .should('have.text', "Share Page")
            .click();
        cy.get('[class="v-card__title text-h6 text-sm-h5"]')
            .contains("Share with your Friends!")
        cy.get('[class="v-card__text text-center"]')
            .contains("Share with friends and family. Click the share button below.")
        cy.get('[class="mx-auto text-center"]')
            //.contains("Share Give")
            .click() 
        cy.get('.v-overlay__scrim')
            .click({ force: true });
        cy.get("#menu-icon")
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(1)
            .click();
        cy.get('[class="v-list-item__title"]')
            .eq(1)
            .contains("Profile")
            .click()
        cy.get('h1')
            .contains("edit_profile")
        cy.get('[class="ui-heading"]')
            .contains("Edit Profile")
        cy.get('[class="field-label"]')
            .eq(0)
            .should('have.text', "First Name")
        cy.get('[class="field-label"]')
            .eq(1)
            .should('have.text', "Last Name")

        cy.get('[class="field-label"]')
            .eq(2)
            .should('have.text', "Enter Email Address")

        cy.get('[class="phone-label"]')
            .eq(0)
            .should('have.text', "Enter Phone Number")

        cy.get('[class="ui-input"]')
            .eq(0)
            .click()
            .clear()
            .type("Change")

        cy.get('[class="ui-input"]')
            .eq(1)
            .click()
            .clear()
            .type("Name")

        cy.get('[class="button-title"]')
            .click()

        cy.get('[class="ui-input"]')
            .eq(0)
            .click()
            .clear()
            .type("Andrew")

        cy.get('[class="ui-input"]')
            .eq(1)
            .click()
            .clear()
            .type("Exon")
        
        cy.get('[class="button-title"]')
            .click()

        cy.get('[class="v-icon notranslate material-icons theme--dark"]')
            .click()
        
        cy.get("[class='v-list-item__title']")
            .eq(2)
            .contains("Advanced Settings")
            .click()
        cy.get('h1')
            .contains("Advanced Settings")
        cy.get('[class="v-card__title heading"]')
            .contains("Reveal Private Key")
        cy.get('p')
            .contains("Using this tool, you will be able to download and save your private key which is connected to your Ethereum address BE VERY CAREFUL WITH THIS KEY as it can grant the holder total control over your Ethereum address.")
        cy.get('[class="v-text-field__slot"]')
            .click()
            .type(Cypress.env('wallet'))
        cy.get('#pkey')
            .should('have.class', "v-btn v-btn--contained v-btn--is-elevated v-btn--has-bg theme--light v-size--default")
        cy.get('[class="v-icon notranslate material-icons theme--dark"]')
            .click()
        cy.get("[class='v-list-item__title']")
            .eq(2)
            .contains("Advanced Settings")

        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(2)
            .click();
        cy.get("[class='v-list-item__title']")
            .eq(3)
            .contains("2-Factor Auth (2FA)")
            .click()
        cy.get('h1')
            .contains("2-Factor Auth (2FA)")
        cy.get('.v-stepper__header')
            .contains("Take the following steps to enable two-factor authentication and add greater security to your wallet")
        cy.get('.v-stepper__step--active > .v-stepper__label')
            .contains("Download Authenticator App")
        cy.get(':nth-child(3) > .v-stepper__wrapper > p')
            .contains("Install an authenticator app on your mobile device. Recommended options:")
        cy.get(":nth-child(4) > .v-stepper__label")
            .contains("Add wallet to authenticator app")
        cy.get(":nth-child(6) > .v-stepper__label")
            .contains("Verify provided code")
        cy.get(".v-toolbar__content > .v-btn > .v-btn__content > .v-icon")
            .click()
        cy.get("[class='v-list-item__title']")
            .eq(4)
            .contains("Account Password")
            .click()
        cy.get('h1')
            .contains("Account Password")
        cy.get(".heading")
            .contains("Fill out the fields below to change your account password.")
        cy.get('#input-285')
            .click()
            .type(Cypress.env('wallet'))
        cy.get('#input-287')
            .click()
            .type(Cypress.env('wallet'))
        cy.get(".mr-2 > .v-btn__content")
            .should('have.text', "Cancel")
        cy.get(".base > .v-btn__content")
            .contains("Submit")
        cy.get(".v-toolbar__content > .v-btn > .v-btn__content > .v-icon")
            .click()
        cy.get("[class='v-list-item__title']")
            .eq(5)
            .contains("Encryption Password")
            .click()
        // cy.get('[class="dialog-title text-capitalize centered"]')
        //     .contains("Encryption Password")
        cy.get(".rounded-corners > .v-card__title")
            .contains("Change Your Encryption Password")
        cy.get("#input-296")
            //.contains("App Backup Phrase")
            .type(Cypress.env('phrase'))
        cy.get("#input-301")
            .click()
            .type(Cypress.env('wallet'))
        cy.get('#input-303')
            .click()
            .type(Cypress.env('wallet'))
        cy.get('.mr-2 > .v-btn__content')
            .should('have.text', "Cancel")
        cy.get(".base > .v-btn__content")
            .contains("Save")
        cy.get('.v-toolbar__content > .v-btn > .v-btn__content > .v-icon')
            .click()
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
                .eq(3)
                .click();  
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(3)
            .click();
        cy.get("[class='v-list-item__title']")
            .eq(6)
            .contains("Information")
        cy.get("[class='v-list-item__title']")
            .eq(7)
            .contains("Purchase")  

        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(4)
            .click();
        cy.get("[class='v-list-item__title']")
            .eq(8)
            .contains("Frequently Asked Questions")
        cy.get("[class='v-list-item__title']")
            .eq(9)
            .contains("Terms & Conditions")
        cy.get("[class='v-list-item__title']")
            .eq(10)
            .contains("Privacy Policy")
    })

    it('Document Test - iPhone-x-portrait', () => {
        cy.viewport('iphone-x', 'portrait')
        // WordPress log in logs you into the Dashboard rather than Summary or Balances
        // This sections covers the chevron clicks making sure they open correctly
        cy.get("#menu-icon")
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(0)
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(1)
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(2)
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(3)
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(4)
            .click();
        // This section covers the Share link and page content
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(0)
            .click();
        cy.get("[class='v-list-item__title']")
            .eq(0)
            .should('have.text', "Share Page")
            .click();
        cy.get('[class="v-card__title text-h6 text-sm-h5"]')
            .contains("Share with your Friends!")
        cy.get('[class="v-card__text text-center"]')
            .contains("Share with friends and family. Click the share button below.")
        cy.get('[class="mx-auto text-center"]')
            //.contains("Share Give")
            .click() 
        cy.get('.v-overlay__scrim')
            .click({ force: true });
        cy.get("#menu-icon")
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(1)
            .click();
        cy.get('[class="v-list-item__title"]')
            .eq(1)
            .contains("Profile")
            .click()
        cy.get('h1')
            .contains("edit_profile")
        cy.get('[class="ui-heading"]')
            .contains("Edit Profile")
        cy.get('[class="field-label"]')
            .eq(0)
            .should('have.text', "First Name")
        cy.get('[class="field-label"]')
            .eq(1)
            .should('have.text', "Last Name")

        cy.get('[class="field-label"]')
            .eq(2)
            .should('have.text', "Enter Email Address")

        cy.get('[class="phone-label"]')
            .eq(0)
            .should('have.text', "Enter Phone Number")

        cy.get('[class="ui-input"]')
            .eq(0)
            .click()
            .clear()
            .type("Change")

        cy.get('[class="ui-input"]')
            .eq(1)
            .click()
            .clear()
            .type("Name")

        cy.get('[class="button-title"]')
            .click()

        cy.get('[class="ui-input"]')
            .eq(0)
            .click()
            .clear()
            .type("Andrew")

        cy.get('[class="ui-input"]')
            .eq(1)
            .click()
            .clear()
            .type("Exon")
        
        cy.get('[class="button-title"]')
            .click()

        cy.get('[class="v-icon notranslate material-icons theme--dark"]')
            .click()
        
        cy.get("[class='v-list-item__title']")
            .eq(2)
            .contains("Advanced Settings")
            .click()
        cy.get('h1')
            .contains("Advanced Settings")
        cy.get('[class="v-card__title heading"]')
            .contains("Reveal Private Key")
        cy.get('p')
            .contains("Using this tool, you will be able to download and save your private key which is connected to your Ethereum address BE VERY CAREFUL WITH THIS KEY as it can grant the holder total control over your Ethereum address.")
        cy.get('[class="v-text-field__slot"]')
            .click()
            .type(Cypress.env('wallet'))
        cy.get('#pkey')
            .should('have.class', "v-btn v-btn--contained v-btn--is-elevated v-btn--has-bg theme--light v-size--default")
        cy.get('[class="v-icon notranslate material-icons theme--dark"]')
            .click()
        cy.get("[class='v-list-item__title']")
            .eq(2)
            .contains("Advanced Settings")

        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(2)
            .click();
        cy.get("[class='v-list-item__title']")
            .eq(3)
            .contains("2-Factor Auth (2FA)")
            .click()
        cy.get('h1')
            .contains("2-Factor Auth (2FA)")
        cy.get('.v-stepper__header')
            .contains("Take the following steps to enable two-factor authentication and add greater security to your wallet")
        cy.get('.v-stepper__step--active > .v-stepper__label')
            .contains("Download Authenticator App")
        cy.get(':nth-child(3) > .v-stepper__wrapper > p')
            .contains("Install an authenticator app on your mobile device. Recommended options:")
        cy.get(":nth-child(4) > .v-stepper__label")
            .contains("Add wallet to authenticator app")
        cy.get(":nth-child(6) > .v-stepper__label")
            .contains("Verify provided code")
        cy.get(".v-toolbar__content > .v-btn > .v-btn__content > .v-icon")
            .click()
        cy.get("[class='v-list-item__title']")
            .eq(4)
            .contains("Account Password")
            .click()
        cy.get('h1')
            .contains("Account Password")
        cy.get(".heading")
            .contains("Fill out the fields below to change your account password.")
        cy.get('#input-285')
            .click()
            .type(Cypress.env('wallet'))
        cy.get('#input-287')
            .click()
            .type(Cypress.env('wallet'))
        cy.get(".mr-2 > .v-btn__content")
            .should('have.text', "Cancel")
        cy.get(".base > .v-btn__content")
            .contains("Submit")
        cy.get(".v-toolbar__content > .v-btn > .v-btn__content > .v-icon")
            .click()
        cy.get("[class='v-list-item__title']")
            .eq(5)
            .contains("Encryption Password")
            .click()
        // cy.get('[class="dialog-title text-capitalize centered"]')
        //     .contains("Encryption Password")
        cy.get(".rounded-corners > .v-card__title")
            .contains("Change Your Encryption Password")
        cy.get("#input-296")
            //.contains("App Backup Phrase")
            .type(Cypress.env('phrase'))
        cy.get("#input-301")
            .click()
            .type(Cypress.env('wallet'))
        cy.get('#input-303')
            .click()
            .type(Cypress.env('wallet'))
        cy.get('.mr-2 > .v-btn__content')
            .should('have.text', "Cancel")
        cy.get(".base > .v-btn__content")
            .contains("Save")
        cy.get('.v-toolbar__content > .v-btn > .v-btn__content > .v-icon')
            .click()
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
                .eq(3)
                .click();  
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(3)
            .click();
        cy.get("[class='v-list-item__title']")
            .eq(6)
            .contains("Information")
        cy.get("[class='v-list-item__title']")
            .eq(7)
            .contains("Purchase")  

        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(4)
            .click();
        cy.get("[class='v-list-item__title']")
            .eq(8)
            .contains("Frequently Asked Questions")
        cy.get("[class='v-list-item__title']")
            .eq(9)
            .contains("Terms & Conditions")
        cy.get("[class='v-list-item__title']")
            .eq(10)
            .contains("Privacy Policy")
    })

    it('Document Test - iPad-mini-landscape', () => {
        cy.viewport('ipad-mini', 'landscape')
        // WordPress log in logs you into the Dashboard rather than Summary or Balances
        // This sections covers the chevron clicks making sure they open correctly
        cy.get("#menu-icon")
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(0)
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(1)
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(2)
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(3)
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(4)
            .click();
        // This section covers the Share link and page content
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(0)
            .click();
        cy.get("[class='v-list-item__title']")
            .eq(0)
            .should('have.text', "Share Page")
            .click();
        cy.get('[class="v-card__title text-h6 text-sm-h5"]')
            .contains("Share with your Friends!")
        cy.get('[class="v-card__text text-center"]')
            .contains("Share with friends and family. Click the share button below.")
        cy.get('[class="mx-auto text-center"]')
            //.contains("Share Give")
            .click() 
        cy.get('.v-overlay__scrim')
            .click({ force: true });
        cy.get("#menu-icon")
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(1)
            .click();
        cy.get('[class="v-list-item__title"]')
            .eq(1)
            .contains("Profile")
            .click()
        cy.get('h1')
            .contains("edit_profile")
        cy.get('[class="ui-heading"]')
            .contains("Edit Profile")
        cy.get('[class="field-label"]')
            .eq(0)
            .should('have.text', "First Name")
        cy.get('[class="field-label"]')
            .eq(1)
            .should('have.text', "Last Name")

        cy.get('[class="field-label"]')
            .eq(2)
            .should('have.text', "Enter Email Address")

        cy.get('[class="phone-label"]')
            .eq(0)
            .should('have.text', "Enter Phone Number")

        cy.get('[class="ui-input"]')
            .eq(0)
            .click()
            .clear()
            .type("Change")

        cy.get('[class="ui-input"]')
            .eq(1)
            .click()
            .clear()
            .type("Name")

        cy.get('[class="button-title"]')
            .click()

        cy.get('[class="ui-input"]')
            .eq(0)
            .click()
            .clear()
            .type("Andrew")

        cy.get('[class="ui-input"]')
            .eq(1)
            .click()
            .clear()
            .type("Exon")
        
        cy.get('[class="button-title"]')
            .click()

        cy.get('[class="v-icon notranslate material-icons theme--dark"]')
            .click()
        
        cy.get("[class='v-list-item__title']")
            .eq(2)
            .contains("Advanced Settings")
            .click()
        cy.get('h1')
            .contains("Advanced Settings")
        cy.get('[class="v-card__title heading"]')
            .contains("Reveal Private Key")
        cy.get('p')
            .contains("Using this tool, you will be able to download and save your private key which is connected to your Ethereum address BE VERY CAREFUL WITH THIS KEY as it can grant the holder total control over your Ethereum address.")
        cy.get('[class="v-text-field__slot"]')
            .click()
            .type(Cypress.env('wallet'))
        cy.get('#pkey')
            .should('have.class', "v-btn v-btn--contained v-btn--is-elevated v-btn--has-bg theme--light v-size--default")
        cy.get('[class="v-icon notranslate material-icons theme--dark"]')
            .click()
        cy.get("[class='v-list-item__title']")
            .eq(2)
            .contains("Advanced Settings")

        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(2)
            .click();
        cy.get("[class='v-list-item__title']")
            .eq(3)
            .contains("2-Factor Auth (2FA)")
            .click()
        cy.get('h1')
            .contains("2-Factor Auth (2FA)")
        cy.get('.v-stepper__header')
            .contains("Take the following steps to enable two-factor authentication and add greater security to your wallet")
        cy.get('.v-stepper__step--active > .v-stepper__label')
            .contains("Download Authenticator App")
        cy.get(':nth-child(3) > .v-stepper__wrapper > p')
            .contains("Install an authenticator app on your mobile device. Recommended options:")
        cy.get(":nth-child(4) > .v-stepper__label")
            .contains("Add wallet to authenticator app")
        cy.get(":nth-child(6) > .v-stepper__label")
            .contains("Verify provided code")
        cy.get(".v-toolbar__content > .v-btn > .v-btn__content > .v-icon")
            .click()
        cy.get("[class='v-list-item__title']")
            .eq(4)
            .contains("Account Password")
            .click()
        cy.get('h1')
            .contains("Account Password")
        cy.get(".heading")
            .contains("Fill out the fields below to change your account password.")
        cy.get('#input-285')
            .click()
            .type(Cypress.env('wallet'))
        cy.get('#input-287')
            .click()
            .type(Cypress.env('wallet'))
        cy.get(".mr-2 > .v-btn__content")
            .should('have.text', "Cancel")
        cy.get(".base > .v-btn__content")
            .contains("Submit")
        cy.get(".v-toolbar__content > .v-btn > .v-btn__content > .v-icon")
            .click()
        cy.get("[class='v-list-item__title']")
            .eq(5)
            .contains("Encryption Password")
            .click()
        // cy.get('[class="dialog-title text-capitalize centered"]')
        //     .contains("Encryption Password")
        cy.get(".rounded-corners > .v-card__title")
            .contains("Change Your Encryption Password")
        cy.get("#input-296")
            //.contains("App Backup Phrase")
            .type(Cypress.env('phrase'))
        cy.get("#input-301")
            .click()
            .type(Cypress.env('wallet'))
        cy.get('#input-303')
            .click()
            .type(Cypress.env('wallet'))
        cy.get('.mr-2 > .v-btn__content')
            .should('have.text', "Cancel")
        cy.get(".base > .v-btn__content")
            .contains("Save")
        cy.get('.v-toolbar__content > .v-btn > .v-btn__content > .v-icon')
            .click()
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
                .eq(3)
                .click();  
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(3)
            .click();
        cy.get("[class='v-list-item__title']")
            .eq(6)
            .contains("Information")
        cy.get("[class='v-list-item__title']")
            .eq(7)
            .contains("Purchase")  

        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(4)
            .click();
        cy.get("[class='v-list-item__title']")
            .eq(8)
            .contains("Frequently Asked Questions")
        cy.get("[class='v-list-item__title']")
            .eq(9)
            .contains("Terms & Conditions")
        cy.get("[class='v-list-item__title']")
            .eq(10)
            .contains("Privacy Policy")
    })

    it('Document Test - iPad-2-landscape', () => {
        cy.viewport('ipad-2', 'landscape')
        // WordPress log in logs you into the Dashboard rather than Summary or Balances
        // This sections covers the chevron clicks making sure they open correctly
        cy.get("#menu-icon")
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(0)
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(1)
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(2)
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(3)
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(4)
            .click();
        // This section covers the Share link and page content
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(0)
            .click();
        cy.get("[class='v-list-item__title']")
            .eq(0)
            .should('have.text', "Share Page")
            .click();
        cy.get('[class="v-card__title text-h6 text-sm-h5"]')
            .contains("Share with your Friends!")
        cy.get('[class="v-card__text text-center"]')
            .contains("Share with friends and family. Click the share button below.")
        cy.get('[class="mx-auto text-center"]')
            //.contains("Share Give")
            .click() 
        cy.get('.v-overlay__scrim')
            .click({ force: true });
        cy.get("#menu-icon")
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(1)
            .click();
        cy.get('[class="v-list-item__title"]')
            .eq(1)
            .contains("Profile")
            .click()
        cy.get('h1')
            .contains("edit_profile")
        cy.get('[class="ui-heading"]')
            .contains("Edit Profile")
        cy.get('[class="field-label"]')
            .eq(0)
            .should('have.text', "First Name")
        cy.get('[class="field-label"]')
            .eq(1)
            .should('have.text', "Last Name")

        cy.get('[class="field-label"]')
            .eq(2)
            .should('have.text', "Enter Email Address")

        cy.get('[class="phone-label"]')
            .eq(0)
            .should('have.text', "Enter Phone Number")

        cy.get('[class="ui-input"]')
            .eq(0)
            .click()
            .clear()
            .type("Change")

        cy.get('[class="ui-input"]')
            .eq(1)
            .click()
            .clear()
            .type("Name")

        cy.get('[class="button-title"]')
            .click()

        cy.get('[class="ui-input"]')
            .eq(0)
            .click()
            .clear()
            .type("Andrew")

        cy.get('[class="ui-input"]')
            .eq(1)
            .click()
            .clear()
            .type("Exon")
        
        cy.get('[class="button-title"]')
            .click()

        cy.get('[class="v-icon notranslate material-icons theme--dark"]')
            .click()
        
        cy.get("[class='v-list-item__title']")
            .eq(2)
            .contains("Advanced Settings")
            .click()
        cy.get('h1')
            .contains("Advanced Settings")
        cy.get('[class="v-card__title heading"]')
            .contains("Reveal Private Key")
        cy.get('p')
            .contains("Using this tool, you will be able to download and save your private key which is connected to your Ethereum address BE VERY CAREFUL WITH THIS KEY as it can grant the holder total control over your Ethereum address.")
        cy.get('[class="v-text-field__slot"]')
            .click()
            .type(Cypress.env('wallet'))
        cy.get('#pkey')
            .should('have.class', "v-btn v-btn--contained v-btn--is-elevated v-btn--has-bg theme--light v-size--default")
        cy.get('[class="v-icon notranslate material-icons theme--dark"]')
            .click()
        cy.get("[class='v-list-item__title']")
            .eq(2)
            .contains("Advanced Settings")

        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(2)
            .click();
        cy.get("[class='v-list-item__title']")
            .eq(3)
            .contains("2-Factor Auth (2FA)")
            .click()
        cy.get('h1')
            .contains("2-Factor Auth (2FA)")
        cy.get('.v-stepper__header')
            .contains("Take the following steps to enable two-factor authentication and add greater security to your wallet")
        cy.get('.v-stepper__step--active > .v-stepper__label')
            .contains("Download Authenticator App")
        cy.get(':nth-child(3) > .v-stepper__wrapper > p')
            .contains("Install an authenticator app on your mobile device. Recommended options:")
        cy.get(":nth-child(4) > .v-stepper__label")
            .contains("Add wallet to authenticator app")
        cy.get(":nth-child(6) > .v-stepper__label")
            .contains("Verify provided code")
        cy.get(".v-toolbar__content > .v-btn > .v-btn__content > .v-icon")
            .click()
        cy.get("[class='v-list-item__title']")
            .eq(4)
            .contains("Account Password")
            .click()
        cy.get('h1')
            .contains("Account Password")
        cy.get(".heading")
            .contains("Fill out the fields below to change your account password.")
        cy.get('#input-285')
            .click()
            .type(Cypress.env('wallet'))
        cy.get('#input-287')
            .click()
            .type(Cypress.env('wallet'))
        cy.get(".mr-2 > .v-btn__content")
            .should('have.text', "Cancel")
        cy.get(".base > .v-btn__content")
            .contains("Submit")
        cy.get(".v-toolbar__content > .v-btn > .v-btn__content > .v-icon")
            .click()
        cy.get("[class='v-list-item__title']")
            .eq(5)
            .contains("Encryption Password")
            .click()
        // cy.get('[class="dialog-title text-capitalize centered"]')
        //     .contains("Encryption Password")
        cy.get(".rounded-corners > .v-card__title")
            .contains("Change Your Encryption Password")
        cy.get("#input-296")
            //.contains("App Backup Phrase")
            .type(Cypress.env('phrase'))
        cy.get("#input-301")
            .click()
            .type(Cypress.env('wallet'))
        cy.get('#input-303')
            .click()
            .type(Cypress.env('wallet'))
        cy.get('.mr-2 > .v-btn__content')
            .should('have.text', "Cancel")
        cy.get(".base > .v-btn__content")
            .contains("Save")
        cy.get('.v-toolbar__content > .v-btn > .v-btn__content > .v-icon')
            .click()
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
                .eq(3)
                .click();  
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(3)
            .click();
        cy.get("[class='v-list-item__title']")
            .eq(6)
            .contains("Information")
        cy.get("[class='v-list-item__title']")
            .eq(7)
            .contains("Purchase")  

        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(4)
            .click();
        cy.get("[class='v-list-item__title']")
            .eq(8)
            .contains("Frequently Asked Questions")
        cy.get("[class='v-list-item__title']")
            .eq(9)
            .contains("Terms & Conditions")
        cy.get("[class='v-list-item__title']")
            .eq(10)
            .contains("Privacy Policy")
    })

    it('Document Test - SamsungS10-portrait', () => {
        cy.viewport('samsung-s10', 'portrait')
        // WordPress log in logs you into the Dashboard rather than Summary or Balances
        // This sections covers the chevron clicks making sure they open correctly
        cy.get("#menu-icon")
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(0)
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(1)
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(2)
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(3)
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(4)
            .click();
        // This section covers the Share link and page content
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(0)
            .click();
        cy.get("[class='v-list-item__title']")
            .eq(0)
            .should('have.text', "Share Page")
            .click();
        cy.get('[class="v-card__title text-h6 text-sm-h5"]')
            .contains("Share with your Friends!")
        cy.get('[class="v-card__text text-center"]')
            .contains("Share with friends and family. Click the share button below.")
        cy.get('[class="mx-auto text-center"]')
            //.contains("Share Give")
            .click() 
        cy.get('.v-overlay__scrim')
            .click({ force: true });
        cy.get("#menu-icon")
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(1)
            .click();
        cy.get('[class="v-list-item__title"]')
            .eq(1)
            .contains("Profile")
            .click()
        cy.get('h1')
            .contains("edit_profile")
        cy.get('[class="ui-heading"]')
            .contains("Edit Profile")
        cy.get('[class="field-label"]')
            .eq(0)
            .should('have.text', "First Name")
        cy.get('[class="field-label"]')
            .eq(1)
            .should('have.text', "Last Name")

        cy.get('[class="field-label"]')
            .eq(2)
            .should('have.text', "Enter Email Address")

        cy.get('[class="phone-label"]')
            .eq(0)
            .should('have.text', "Enter Phone Number")

        cy.get('[class="ui-input"]')
            .eq(0)
            .click()
            .clear()
            .type("Change")

        cy.get('[class="ui-input"]')
            .eq(1)
            .click()
            .clear()
            .type("Name")

        cy.get('[class="button-title"]')
            .click()

        cy.get('[class="ui-input"]')
            .eq(0)
            .click()
            .clear()
            .type("Andrew")

        cy.get('[class="ui-input"]')
            .eq(1)
            .click()
            .clear()
            .type("Exon")
        
        cy.get('[class="button-title"]')
            .click()

        cy.get('[class="v-icon notranslate material-icons theme--dark"]')
            .click()
        
        cy.get("[class='v-list-item__title']")
            .eq(2)
            .contains("Advanced Settings")
            .click()
        cy.get('h1')
            .contains("Advanced Settings")
        cy.get('[class="v-card__title heading"]')
            .contains("Reveal Private Key")
        cy.get('p')
            .contains("Using this tool, you will be able to download and save your private key which is connected to your Ethereum address BE VERY CAREFUL WITH THIS KEY as it can grant the holder total control over your Ethereum address.")
        cy.get('[class="v-text-field__slot"]')
            .click()
            .type(Cypress.env('wallet'))
        cy.get('#pkey')
            .should('have.class', "v-btn v-btn--contained v-btn--is-elevated v-btn--has-bg theme--light v-size--default")
        cy.get('[class="v-icon notranslate material-icons theme--dark"]')
            .click()
        cy.get("[class='v-list-item__title']")
            .eq(2)
            .contains("Advanced Settings")

        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(2)
            .click();
        cy.get("[class='v-list-item__title']")
            .eq(3)
            .contains("2-Factor Auth (2FA)")
            .click()
        cy.get('h1')
            .contains("2-Factor Auth (2FA)")
        cy.get('.v-stepper__header')
            .contains("Take the following steps to enable two-factor authentication and add greater security to your wallet")
        cy.get('.v-stepper__step--active > .v-stepper__label')
            .contains("Download Authenticator App")
        cy.get(':nth-child(3) > .v-stepper__wrapper > p')
            .contains("Install an authenticator app on your mobile device. Recommended options:")
        cy.get(":nth-child(4) > .v-stepper__label")
            .contains("Add wallet to authenticator app")
        cy.get(":nth-child(6) > .v-stepper__label")
            .contains("Verify provided code")
        cy.get(".v-toolbar__content > .v-btn > .v-btn__content > .v-icon")
            .click()
        cy.get("[class='v-list-item__title']")
            .eq(4)
            .contains("Account Password")
            .click()
        cy.get('h1')
            .contains("Account Password")
        cy.get(".heading")
            .contains("Fill out the fields below to change your account password.")
        cy.get('#input-285')
            .click()
            .type(Cypress.env('wallet'))
        cy.get('#input-287')
            .click()
            .type(Cypress.env('wallet'))
        cy.get(".mr-2 > .v-btn__content")
            .should('have.text', "Cancel")
        cy.get(".base > .v-btn__content")
            .contains("Submit")
        cy.get(".v-toolbar__content > .v-btn > .v-btn__content > .v-icon")
            .click()
        cy.get("[class='v-list-item__title']")
            .eq(5)
            .contains("Encryption Password")
            .click()
        // cy.get('[class="dialog-title text-capitalize centered"]')
        //     .contains("Encryption Password")
        cy.get(".rounded-corners > .v-card__title")
            .contains("Change Your Encryption Password")
        cy.get("#input-296")
            //.contains("App Backup Phrase")
            .type(Cypress.env('phrase'))
        cy.get("#input-301")
            .click()
            .type(Cypress.env('wallet'))
        cy.get('#input-303')
            .click()
            .type(Cypress.env('wallet'))
        cy.get('.mr-2 > .v-btn__content')
            .should('have.text', "Cancel")
        cy.get(".base > .v-btn__content")
            .contains("Save")
        cy.get('.v-toolbar__content > .v-btn > .v-btn__content > .v-icon')
            .click()
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
                .eq(3)
                .click();  
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(3)
            .click();
        cy.get("[class='v-list-item__title']")
            .eq(6)
            .contains("Information")
        cy.get("[class='v-list-item__title']")
            .eq(7)
            .contains("Purchase")  

        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(4)
            .click();
        cy.get("[class='v-list-item__title']")
            .eq(8)
            .contains("Frequently Asked Questions")
        cy.get("[class='v-list-item__title']")
            .eq(9)
            .contains("Terms & Conditions")
        cy.get("[class='v-list-item__title']")
            .eq(10)
            .contains("Privacy Policy")
    })

    it('Document Test - Samsung-Note9-portrait', () => {
        cy.viewport('samsung-note9', 'portrait')
        // WordPress log in logs you into the Dashboard rather than Summary or Balances
        // This sections covers the chevron clicks making sure they open correctly
        cy.get("#menu-icon")
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(0)
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(1)
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(2)
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(3)
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(4)
            .click();
        // This section covers the Share link and page content
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(0)
            .click();
        cy.get("[class='v-list-item__title']")
            .eq(0)
            .should('have.text', "Share Page")
            .click();
        cy.get('[class="v-card__title text-h6 text-sm-h5"]')
            .contains("Share with your Friends!")
        cy.get('[class="v-card__text text-center"]')
            .contains("Share with friends and family. Click the share button below.")
        cy.get('[class="mx-auto text-center"]')
            //.contains("Share Give")
            .click() 
        cy.get('.v-overlay__scrim')
            .click({ force: true });
        cy.get("#menu-icon")
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(1)
            .click();
        cy.get('[class="v-list-item__title"]')
            .eq(1)
            .contains("Profile")
            .click()
        cy.get('h1')
            .contains("edit_profile")
        cy.get('[class="ui-heading"]')
            .contains("Edit Profile")
        cy.get('[class="field-label"]')
            .eq(0)
            .should('have.text', "First Name")
        cy.get('[class="field-label"]')
            .eq(1)
            .should('have.text', "Last Name")

        cy.get('[class="field-label"]')
            .eq(2)
            .should('have.text', "Enter Email Address")

        cy.get('[class="phone-label"]')
            .eq(0)
            .should('have.text', "Enter Phone Number")

        cy.get('[class="ui-input"]')
            .eq(0)
            .click()
            .clear()
            .type("Change")

        cy.get('[class="ui-input"]')
            .eq(1)
            .click()
            .clear()
            .type("Name")

        cy.get('[class="button-title"]')
            .click()

        cy.get('[class="ui-input"]')
            .eq(0)
            .click()
            .clear()
            .type("Andrew")

        cy.get('[class="ui-input"]')
            .eq(1)
            .click()
            .clear()
            .type("Exon")
        
        cy.get('[class="button-title"]')
            .click()

        cy.get('[class="v-icon notranslate material-icons theme--dark"]')
            .click()
        
        cy.get("[class='v-list-item__title']")
            .eq(2)
            .contains("Advanced Settings")
            .click()
        cy.get('h1')
            .contains("Advanced Settings")
        cy.get('[class="v-card__title heading"]')
            .contains("Reveal Private Key")
        cy.get('p')
            .contains("Using this tool, you will be able to download and save your private key which is connected to your Ethereum address BE VERY CAREFUL WITH THIS KEY as it can grant the holder total control over your Ethereum address.")
        cy.get('[class="v-text-field__slot"]')
            .click()
            .type(Cypress.env('wallet'))
        cy.get('#pkey')
            .should('have.class', "v-btn v-btn--contained v-btn--is-elevated v-btn--has-bg theme--light v-size--default")
        cy.get('[class="v-icon notranslate material-icons theme--dark"]')
            .click()
        cy.get("[class='v-list-item__title']")
            .eq(2)
            .contains("Advanced Settings")

        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(2)
            .click();
        cy.get("[class='v-list-item__title']")
            .eq(3)
            .contains("2-Factor Auth (2FA)")
            .click()
        cy.get('h1')
            .contains("2-Factor Auth (2FA)")
        cy.get('.v-stepper__header')
            .contains("Take the following steps to enable two-factor authentication and add greater security to your wallet")
        cy.get('.v-stepper__step--active > .v-stepper__label')
            .contains("Download Authenticator App")
        cy.get(':nth-child(3) > .v-stepper__wrapper > p')
            .contains("Install an authenticator app on your mobile device. Recommended options:")
        cy.get(":nth-child(4) > .v-stepper__label")
            .contains("Add wallet to authenticator app")
        cy.get(":nth-child(6) > .v-stepper__label")
            .contains("Verify provided code")
        cy.get(".v-toolbar__content > .v-btn > .v-btn__content > .v-icon")
            .click()
        cy.get("[class='v-list-item__title']")
            .eq(4)
            .contains("Account Password")
            .click()
        cy.get('h1')
            .contains("Account Password")
        cy.get(".heading")
            .contains("Fill out the fields below to change your account password.")
        cy.get('#input-285')
            .click()
            .type(Cypress.env('wallet'))
        cy.get('#input-287')
            .click()
            .type(Cypress.env('wallet'))
        cy.get(".mr-2 > .v-btn__content")
            .should('have.text', "Cancel")
        cy.get(".base > .v-btn__content")
            .contains("Submit")
        cy.get(".v-toolbar__content > .v-btn > .v-btn__content > .v-icon")
            .click()
        cy.get("[class='v-list-item__title']")
            .eq(5)
            .contains("Encryption Password")
            .click()
        // cy.get('[class="dialog-title text-capitalize centered"]')
        //     .contains("Encryption Password")
        cy.get(".rounded-corners > .v-card__title")
            .contains("Change Your Encryption Password")
        cy.get("#input-296")
            //.contains("App Backup Phrase")
            .type(Cypress.env('phrase'))
        cy.get("#input-301")
            .click()
            .type(Cypress.env('wallet'))
        cy.get('#input-303')
            .click()
            .type(Cypress.env('wallet'))
        cy.get('.mr-2 > .v-btn__content')
            .should('have.text', "Cancel")
        cy.get(".base > .v-btn__content")
            .contains("Save")
        cy.get('.v-toolbar__content > .v-btn > .v-btn__content > .v-icon')
            .click()
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
                .eq(3)
                .click();  
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(3)
            .click();
        cy.get("[class='v-list-item__title']")
            .eq(6)
            .contains("Information")
        cy.get("[class='v-list-item__title']")
            .eq(7)
            .contains("Purchase")  

        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(4)
            .click();
        cy.get("[class='v-list-item__title']")
            .eq(8)
            .contains("Frequently Asked Questions")
        cy.get("[class='v-list-item__title']")
            .eq(9)
            .contains("Terms & Conditions")
        cy.get("[class='v-list-item__title']")
            .eq(10)
            .contains("Privacy Policy")
    })

    it('Document Test - iPhone12-portrait', () => {
        cy.viewport(390,844, 'portrait')
        // WordPress log in logs you into the Dashboard rather than Summary or Balances
        // This sections covers the chevron clicks making sure they open correctly
        cy.get("#menu-icon")
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(0)
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(1)
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(2)
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(3)
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(4)
            .click();
        // This section covers the Share link and page content
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(0)
            .click();
        cy.get("[class='v-list-item__title']")
            .eq(0)
            .should('have.text', "Share Page")
            .click();
        cy.get('[class="v-card__title text-h6 text-sm-h5"]')
            .contains("Share with your Friends!")
        cy.get('[class="v-card__text text-center"]')
            .contains("Share with friends and family. Click the share button below.")
        cy.get('[class="mx-auto text-center"]')
            //.contains("Share Give")
            .click() 
        cy.get('.v-overlay__scrim')
            .click({ force: true });
        cy.get("#menu-icon")
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(1)
            .click();
        cy.get('[class="v-list-item__title"]')
            .eq(1)
            .contains("Profile")
            .click()
        cy.get('h1')
            .contains("edit_profile")
        cy.get('[class="ui-heading"]')
            .contains("Edit Profile")
        cy.get('[class="field-label"]')
            .eq(0)
            .should('have.text', "First Name")
        cy.get('[class="field-label"]')
            .eq(1)
            .should('have.text', "Last Name")

        cy.get('[class="field-label"]')
            .eq(2)
            .should('have.text', "Enter Email Address")

        cy.get('[class="phone-label"]')
            .eq(0)
            .should('have.text', "Enter Phone Number")

        cy.get('[class="ui-input"]')
            .eq(0)
            .click()
            .clear()
            .type("Change")

        cy.get('[class="ui-input"]')
            .eq(1)
            .click()
            .clear()
            .type("Name")

        cy.get('[class="button-title"]')
            .click()

        cy.get('[class="ui-input"]')
            .eq(0)
            .click()
            .clear()
            .type("Andrew")

        cy.get('[class="ui-input"]')
            .eq(1)
            .click()
            .clear()
            .type("Exon")
        
        cy.get('[class="button-title"]')
            .click()

        cy.get('[class="v-icon notranslate material-icons theme--dark"]')
            .click()
        
        cy.get("[class='v-list-item__title']")
            .eq(2)
            .contains("Advanced Settings")
            .click()
        cy.get('h1')
            .contains("Advanced Settings")
        cy.get('[class="v-card__title heading"]')
            .contains("Reveal Private Key")
        cy.get('p')
            .contains("Using this tool, you will be able to download and save your private key which is connected to your Ethereum address BE VERY CAREFUL WITH THIS KEY as it can grant the holder total control over your Ethereum address.")
        cy.get('[class="v-text-field__slot"]')
            .click()
            .type(Cypress.env('wallet'))
        cy.get('#pkey')
            .should('have.class', "v-btn v-btn--contained v-btn--is-elevated v-btn--has-bg theme--light v-size--default")
        cy.get('[class="v-icon notranslate material-icons theme--dark"]')
            .click()
        cy.get("[class='v-list-item__title']")
            .eq(2)
            .contains("Advanced Settings")

        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(2)
            .click();
        cy.get("[class='v-list-item__title']")
            .eq(3)
            .contains("2-Factor Auth (2FA)")
            .click()
        cy.get('h1')
            .contains("2-Factor Auth (2FA)")
        cy.get('.v-stepper__header')
            .contains("Take the following steps to enable two-factor authentication and add greater security to your wallet")
        cy.get('.v-stepper__step--active > .v-stepper__label')
            .contains("Download Authenticator App")
        cy.get(':nth-child(3) > .v-stepper__wrapper > p')
            .contains("Install an authenticator app on your mobile device. Recommended options:")
        cy.get(":nth-child(4) > .v-stepper__label")
            .contains("Add wallet to authenticator app")
        cy.get(":nth-child(6) > .v-stepper__label")
            .contains("Verify provided code")
        cy.get(".v-toolbar__content > .v-btn > .v-btn__content > .v-icon")
            .click()
        cy.get("[class='v-list-item__title']")
            .eq(4)
            .contains("Account Password")
            .click()
        cy.get('h1')
            .contains("Account Password")
        cy.get(".heading")
            .contains("Fill out the fields below to change your account password.")
        cy.get('#input-285')
            .click()
            .type(Cypress.env('wallet'))
        cy.get('#input-287')
            .click()
            .type(Cypress.env('wallet'))
        cy.get(".mr-2 > .v-btn__content")
            .should('have.text', "Cancel")
        cy.get(".base > .v-btn__content")
            .contains("Submit")
        cy.get(".v-toolbar__content > .v-btn > .v-btn__content > .v-icon")
            .click()
        cy.get("[class='v-list-item__title']")
            .eq(5)
            .contains("Encryption Password")
            .click()
        // cy.get('[class="dialog-title text-capitalize centered"]')
        //     .contains("Encryption Password")
        cy.get(".rounded-corners > .v-card__title")
            .contains("Change Your Encryption Password")
        cy.get("#input-296")
            //.contains("App Backup Phrase")
            .type(Cypress.env('phrase'))
        cy.get("#input-301")
            .click()
            .type(Cypress.env('wallet'))
        cy.get('#input-303')
            .click()
            .type(Cypress.env('wallet'))
        cy.get('.mr-2 > .v-btn__content')
            .should('have.text', "Cancel")
        cy.get(".base > .v-btn__content")
            .contains("Save")
        cy.get('.v-toolbar__content > .v-btn > .v-btn__content > .v-icon')
            .click()
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
                .eq(3)
                .click();  
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(3)
            .click();
        cy.get("[class='v-list-item__title']")
            .eq(6)
            .contains("Information")
        cy.get("[class='v-list-item__title']")
            .eq(7)
            .contains("Purchase")  

        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(4)
            .click();
        cy.get("[class='v-list-item__title']")
            .eq(8)
            .contains("Frequently Asked Questions")
        cy.get("[class='v-list-item__title']")
            .eq(9)
            .contains("Terms & Conditions")
        cy.get("[class='v-list-item__title']")
            .eq(10)
            .contains("Privacy Policy")
    })

    it('Document Test - iPhone12-Mini-portrait', () => {
        cy.viewport(390,780, 'portrait')
        // WordPress log in logs you into the Dashboard rather than Summary or Balances
        // This sections covers the chevron clicks making sure they open correctly
        cy.get("#menu-icon")
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(0)
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(1)
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(2)
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(3)
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(4)
            .click();
        // This section covers the Share link and page content
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(0)
            .click();
        cy.get("[class='v-list-item__title']")
            .eq(0)
            .should('have.text', "Share Page")
            .click();
        cy.get('[class="v-card__title text-h6 text-sm-h5"]')
            .contains("Share with your Friends!")
        cy.get('[class="v-card__text text-center"]')
            .contains("Share with friends and family. Click the share button below.")
        cy.get('[class="mx-auto text-center"]')
            //.contains("Share Give")
            .click() 
        cy.get('.v-overlay__scrim')
            .click({ force: true });
        cy.get("#menu-icon")
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(1)
            .click();
        cy.get('[class="v-list-item__title"]')
            .eq(1)
            .contains("Profile")
            .click()
        cy.get('h1')
            .contains("edit_profile")
        cy.get('[class="ui-heading"]')
            .contains("Edit Profile")
        cy.get('[class="field-label"]')
            .eq(0)
            .should('have.text', "First Name")
        cy.get('[class="field-label"]')
            .eq(1)
            .should('have.text', "Last Name")

        cy.get('[class="field-label"]')
            .eq(2)
            .should('have.text', "Enter Email Address")

        cy.get('[class="phone-label"]')
            .eq(0)
            .should('have.text', "Enter Phone Number")

        cy.get('[class="ui-input"]')
            .eq(0)
            .click()
            .clear()
            .type("Change")

        cy.get('[class="ui-input"]')
            .eq(1)
            .click()
            .clear()
            .type("Name")

        cy.get('[class="button-title"]')
            .click()

        cy.get('[class="ui-input"]')
            .eq(0)
            .click()
            .clear()
            .type("Andrew")

        cy.get('[class="ui-input"]')
            .eq(1)
            .click()
            .clear()
            .type("Exon")
        
        cy.get('[class="button-title"]')
            .click()

        cy.get('[class="v-icon notranslate material-icons theme--dark"]')
            .click()
        
        cy.get("[class='v-list-item__title']")
            .eq(2)
            .contains("Advanced Settings")
            .click()
        cy.get('h1')
            .contains("Advanced Settings")
        cy.get('[class="v-card__title heading"]')
            .contains("Reveal Private Key")
        cy.get('p')
            .contains("Using this tool, you will be able to download and save your private key which is connected to your Ethereum address BE VERY CAREFUL WITH THIS KEY as it can grant the holder total control over your Ethereum address.")
        cy.get('[class="v-text-field__slot"]')
            .click()
            .type(Cypress.env('wallet'))
        cy.get('#pkey')
            .should('have.class', "v-btn v-btn--contained v-btn--is-elevated v-btn--has-bg theme--light v-size--default")
        cy.get('[class="v-icon notranslate material-icons theme--dark"]')
            .click()
        cy.get("[class='v-list-item__title']")
            .eq(2)
            .contains("Advanced Settings")

        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(2)
            .click();
        cy.get("[class='v-list-item__title']")
            .eq(3)
            .contains("2-Factor Auth (2FA)")
            .click()
        cy.get('h1')
            .contains("2-Factor Auth (2FA)")
        cy.get('.v-stepper__header')
            .contains("Take the following steps to enable two-factor authentication and add greater security to your wallet")
        cy.get('.v-stepper__step--active > .v-stepper__label')
            .contains("Download Authenticator App")
        cy.get(':nth-child(3) > .v-stepper__wrapper > p')
            .contains("Install an authenticator app on your mobile device. Recommended options:")
        cy.get(":nth-child(4) > .v-stepper__label")
            .contains("Add wallet to authenticator app")
        cy.get(":nth-child(6) > .v-stepper__label")
            .contains("Verify provided code")
        cy.get(".v-toolbar__content > .v-btn > .v-btn__content > .v-icon")
            .click()
        cy.get("[class='v-list-item__title']")
            .eq(4)
            .contains("Account Password")
            .click()
        cy.get('h1')
            .contains("Account Password")
        cy.get(".heading")
            .contains("Fill out the fields below to change your account password.")
        cy.get('#input-285')
            .click()
            .type(Cypress.env('wallet'))
        cy.get('#input-287')
            .click()
            .type(Cypress.env('wallet'))
        cy.get(".mr-2 > .v-btn__content")
            .should('have.text', "Cancel")
        cy.get(".base > .v-btn__content")
            .contains("Submit")
        cy.get(".v-toolbar__content > .v-btn > .v-btn__content > .v-icon")
            .click()
        cy.get("[class='v-list-item__title']")
            .eq(5)
            .contains("Encryption Password")
            .click()
        // cy.get('[class="dialog-title text-capitalize centered"]')
        //     .contains("Encryption Password")
        cy.get(".rounded-corners > .v-card__title")
            .contains("Change Your Encryption Password")
        cy.get("#input-296")
            //.contains("App Backup Phrase")
            .type(Cypress.env('phrase'))
        cy.get("#input-301")
            .click()
            .type(Cypress.env('wallet'))
        cy.get('#input-303')
            .click()
            .type(Cypress.env('wallet'))
        cy.get('.mr-2 > .v-btn__content')
            .should('have.text', "Cancel")
        cy.get(".base > .v-btn__content")
            .contains("Save")
        cy.get('.v-toolbar__content > .v-btn > .v-btn__content > .v-icon')
            .click()
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
                .eq(3)
                .click();  
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(3)
            .click();
        cy.get("[class='v-list-item__title']")
            .eq(6)
            .contains("Information")
        cy.get("[class='v-list-item__title']")
            .eq(7)
            .contains("Purchase")  

        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(4)
            .click();
        cy.get("[class='v-list-item__title']")
            .eq(8)
            .contains("Frequently Asked Questions")
        cy.get("[class='v-list-item__title']")
            .eq(9)
            .contains("Terms & Conditions")
        cy.get("[class='v-list-item__title']")
            .eq(10)
            .contains("Privacy Policy")
    })

    it('Document Test - iPad-Pro-landscape', () => {
        cy.viewport(1366,1024, 'landscape')
        // WordPress log in logs you into the Dashboard rather than Summary or Balances
        // This sections covers the chevron clicks making sure they open correctly
        cy.get("#menu-icon")
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(0)
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(1)
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(2)
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(3)
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(4)
            .click();
        // This section covers the Share link and page content
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(0)
            .click();
        cy.get("[class='v-list-item__title']")
            .eq(0)
            .should('have.text', "Share Page")
            .click();
        cy.get('[class="v-card__title text-h6 text-sm-h5"]')
            .contains("Share with your Friends!")
        cy.get('[class="v-card__text text-center"]')
            .contains("Share with friends and family. Click the share button below.")
        cy.get('[class="mx-auto text-center"]')
            //.contains("Share Give")
            .click() 
        cy.get('.v-overlay__scrim')
            .click({ force: true });
        cy.get("#menu-icon")
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(1)
            .click();
        cy.get('[class="v-list-item__title"]')
            .eq(1)
            .contains("Profile")
            .click()
        cy.get('h1')
            .contains("edit_profile")
        cy.get('[class="ui-heading"]')
            .contains("Edit Profile")
        cy.get('[class="field-label"]')
            .eq(0)
            .should('have.text', "First Name")
        cy.get('[class="field-label"]')
            .eq(1)
            .should('have.text', "Last Name")

        cy.get('[class="field-label"]')
            .eq(2)
            .should('have.text', "Enter Email Address")

        cy.get('[class="phone-label"]')
            .eq(0)
            .should('have.text', "Enter Phone Number")

        cy.get('[class="ui-input"]')
            .eq(0)
            .click()
            .clear()
            .type("Change")

        cy.get('[class="ui-input"]')
            .eq(1)
            .click()
            .clear()
            .type("Name")

        cy.get('[class="button-title"]')
            .click()

        cy.get('[class="ui-input"]')
            .eq(0)
            .click()
            .clear()
            .type("Andrew")

        cy.get('[class="ui-input"]')
            .eq(1)
            .click()
            .clear()
            .type("Exon")
        
        cy.get('[class="button-title"]')
            .click()

        cy.get('[class="v-icon notranslate material-icons theme--dark"]')
            .click()
        
        cy.get("[class='v-list-item__title']")
            .eq(2)
            .contains("Advanced Settings")
            .click()
        cy.get('h1')
            .contains("Advanced Settings")
        cy.get('[class="v-card__title heading"]')
            .contains("Reveal Private Key")
        cy.get('p')
            .contains("Using this tool, you will be able to download and save your private key which is connected to your Ethereum address BE VERY CAREFUL WITH THIS KEY as it can grant the holder total control over your Ethereum address.")
        cy.get('[class="v-text-field__slot"]')
            .click()
            .type(Cypress.env('wallet'))
        cy.get('#pkey')
            .should('have.class', "v-btn v-btn--contained v-btn--is-elevated v-btn--has-bg theme--light v-size--default")
        cy.get('[class="v-icon notranslate material-icons theme--dark"]')
            .click()
        cy.get("[class='v-list-item__title']")
            .eq(2)
            .contains("Advanced Settings")

        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(2)
            .click();
        cy.get("[class='v-list-item__title']")
            .eq(3)
            .contains("2-Factor Auth (2FA)")
            .click()
        cy.get('h1')
            .contains("2-Factor Auth (2FA)")
        cy.get('.v-stepper__header')
            .contains("Take the following steps to enable two-factor authentication and add greater security to your wallet")
        cy.get('.v-stepper__step--active > .v-stepper__label')
            .contains("Download Authenticator App")
        cy.get(':nth-child(3) > .v-stepper__wrapper > p')
            .contains("Install an authenticator app on your mobile device. Recommended options:")
        cy.get(":nth-child(4) > .v-stepper__label")
            .contains("Add wallet to authenticator app")
        cy.get(":nth-child(6) > .v-stepper__label")
            .contains("Verify provided code")
        cy.get(".v-toolbar__content > .v-btn > .v-btn__content > .v-icon")
            .click()
        cy.get("[class='v-list-item__title']")
            .eq(4)
            .contains("Account Password")
            .click()
        cy.get('h1')
            .contains("Account Password")
        cy.get(".heading")
            .contains("Fill out the fields below to change your account password.")
        cy.get('#input-285')
            .click()
            .type(Cypress.env('wallet'))
        cy.get('#input-287')
            .click()
            .type(Cypress.env('wallet'))
        cy.get(".mr-2 > .v-btn__content")
            .should('have.text', "Cancel")
        cy.get(".base > .v-btn__content")
            .contains("Submit")
        cy.get(".v-toolbar__content > .v-btn > .v-btn__content > .v-icon")
            .click()
        cy.get("[class='v-list-item__title']")
            .eq(5)
            .contains("Encryption Password")
            .click()
        // cy.get('[class="dialog-title text-capitalize centered"]')
        //     .contains("Encryption Password")
        cy.get(".rounded-corners > .v-card__title")
            .contains("Change Your Encryption Password")
        cy.get("#input-296")
            //.contains("App Backup Phrase")
            .type(Cypress.env('phrase'))
        cy.get("#input-301")
            .click()
            .type(Cypress.env('wallet'))
        cy.get('#input-303')
            .click()
            .type(Cypress.env('wallet'))
        cy.get('.mr-2 > .v-btn__content')
            .should('have.text', "Cancel")
        cy.get(".base > .v-btn__content")
            .contains("Save")
        cy.get('.v-toolbar__content > .v-btn > .v-btn__content > .v-icon')
            .click()
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
                .eq(3)
                .click();  
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(3)
            .click();
        cy.get("[class='v-list-item__title']")
            .eq(6)
            .contains("Information")
        cy.get("[class='v-list-item__title']")
            .eq(7)
            .contains("Purchase")  

        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(4)
            .click();
        cy.get("[class='v-list-item__title']")
            .eq(8)
            .contains("Frequently Asked Questions")
        cy.get("[class='v-list-item__title']")
            .eq(9)
            .contains("Terms & Conditions")
        cy.get("[class='v-list-item__title']")
            .eq(10)
            .contains("Privacy Policy")
    })

    it('Document Test - iPad-Pro-portrait', () => {
        cy.viewport(1024,1366, 'portrait')
        // WordPress log in logs you into the Dashboard rather than Summary or Balances
        // This sections covers the chevron clicks making sure they open correctly
        cy.get("#menu-icon")
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(0)
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(1)
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(2)
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(3)
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(4)
            .click();
        // This section covers the Share link and page content
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(0)
            .click();
        cy.get("[class='v-list-item__title']")
            .eq(0)
            .should('have.text', "Share Page")
            .click();
        cy.get('[class="v-card__title text-h6 text-sm-h5"]')
            .contains("Share with your Friends!")
        cy.get('[class="v-card__text text-center"]')
            .contains("Share with friends and family. Click the share button below.")
        cy.get('[class="mx-auto text-center"]')
            //.contains("Share Give")
            .click() 
        cy.get('.v-overlay__scrim')
            .click({ force: true });
        cy.get("#menu-icon")
            .click();
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(1)
            .click();
        cy.get('[class="v-list-item__title"]')
            .eq(1)
            .contains("Profile")
            .click()
        cy.get('h1')
            .contains("edit_profile")
        cy.get('[class="ui-heading"]')
            .contains("Edit Profile")
        cy.get('[class="field-label"]')
            .eq(0)
            .should('have.text', "First Name")
        cy.get('[class="field-label"]')
            .eq(1)
            .should('have.text', "Last Name")

        cy.get('[class="field-label"]')
            .eq(2)
            .should('have.text', "Enter Email Address")

        cy.get('[class="phone-label"]')
            .eq(0)
            .should('have.text', "Enter Phone Number")

        cy.get('[class="ui-input"]')
            .eq(0)
            .click()
            .clear()
            .type("Change")

        cy.get('[class="ui-input"]')
            .eq(1)
            .click()
            .clear()
            .type("Name")

        cy.get('[class="button-title"]')
            .click()

        cy.get('[class="ui-input"]')
            .eq(0)
            .click()
            .clear()
            .type("Andrew")

        cy.get('[class="ui-input"]')
            .eq(1)
            .click()
            .clear()
            .type("Exon")
        
        cy.get('[class="button-title"]')
            .click()

        cy.get('[class="v-icon notranslate material-icons theme--dark"]')
            .click()
        
        cy.get("[class='v-list-item__title']")
            .eq(2)
            .contains("Advanced Settings")
            .click()
        cy.get('h1')
            .contains("Advanced Settings")
        cy.get('[class="v-card__title heading"]')
            .contains("Reveal Private Key")
        cy.get('p')
            .contains("Using this tool, you will be able to download and save your private key which is connected to your Ethereum address BE VERY CAREFUL WITH THIS KEY as it can grant the holder total control over your Ethereum address.")
        cy.get('[class="v-text-field__slot"]')
            .click()
            .type(Cypress.env('wallet'))
        cy.get('#pkey')
            .should('have.class', "v-btn v-btn--contained v-btn--is-elevated v-btn--has-bg theme--light v-size--default")
        cy.get('[class="v-icon notranslate material-icons theme--dark"]')
            .click()
        cy.get("[class='v-list-item__title']")
            .eq(2)
            .contains("Advanced Settings")

        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(2)
            .click();
        cy.get("[class='v-list-item__title']")
            .eq(3)
            .contains("2-Factor Auth (2FA)")
            .click()
        cy.get('h1')
            .contains("2-Factor Auth (2FA)")
        cy.get('.v-stepper__header')
            .contains("Take the following steps to enable two-factor authentication and add greater security to your wallet")
        cy.get('.v-stepper__step--active > .v-stepper__label')
            .contains("Download Authenticator App")
        cy.get(':nth-child(3) > .v-stepper__wrapper > p')
            .contains("Install an authenticator app on your mobile device. Recommended options:")
        cy.get(":nth-child(4) > .v-stepper__label")
            .contains("Add wallet to authenticator app")
        cy.get(":nth-child(6) > .v-stepper__label")
            .contains("Verify provided code")
        cy.get(".v-toolbar__content > .v-btn > .v-btn__content > .v-icon")
            .click()
        cy.get("[class='v-list-item__title']")
            .eq(4)
            .contains("Account Password")
            .click()
        cy.get('h1')
            .contains("Account Password")
        cy.get(".heading")
            .contains("Fill out the fields below to change your account password.")
        cy.get('#input-285')
            .click()
            .type(Cypress.env('wallet'))
        cy.get('#input-287')
            .click()
            .type(Cypress.env('wallet'))
        cy.get(".mr-2 > .v-btn__content")
            .should('have.text', "Cancel")
        cy.get(".base > .v-btn__content")
            .contains("Submit")
        cy.get(".v-toolbar__content > .v-btn > .v-btn__content > .v-icon")
            .click()
        cy.get("[class='v-list-item__title']")
            .eq(5)
            .contains("Encryption Password")
            .click()
        // cy.get('[class="dialog-title text-capitalize centered"]')
        //     .contains("Encryption Password")
        cy.get(".rounded-corners > .v-card__title")
            .contains("Change Your Encryption Password")
        cy.get("#input-296")
            //.contains("App Backup Phrase")
            .type(Cypress.env('phrase'))
        cy.get("#input-301")
            .click()
            .type(Cypress.env('wallet'))
        cy.get('#input-303')
            .click()
            .type(Cypress.env('wallet'))
        cy.get('.mr-2 > .v-btn__content')
            .should('have.text', "Cancel")
        cy.get(".base > .v-btn__content")
            .contains("Save")
        cy.get('.v-toolbar__content > .v-btn > .v-btn__content > .v-icon')
            .click()
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
                .eq(3)
                .click();  
        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(3)
            .click();
        cy.get("[class='v-list-item__title']")
            .eq(6)
            .contains("Information")
        cy.get("[class='v-list-item__title']")
            .eq(7)
            .contains("Purchase")  

        cy.get("[class='v-icon notranslate mdi mdi-chevron-down theme--light']")
            .eq(4)
            .click();
        cy.get("[class='v-list-item__title']")
            .eq(8)
            .contains("Frequently Asked Questions")
        cy.get("[class='v-list-item__title']")
            .eq(9)
            .contains("Terms & Conditions")
        cy.get("[class='v-list-item__title']")
            .eq(10)
            .contains("Privacy Policy")
    })
})