/// <reference types="cypress" />

describe('Login', () => {
    beforeEach(() => {
        cy.visit("https://giveblockchain.io/offer-node/")
        cy.url()
            .should("include", "/offer-node/")
    })

    it('Expecting/Asserting all text on the page', () => {
        cy.get('h1').should(($h1) => {
            expect($h1.eq(0), 'h1 First Title')
                .to.contain("Start Mining Right Now.")
            expect($h1.eq(1), 'h1 Second Title')
                .to.contain("Simple.")
        }) 

        cy.get('h2').should(($h2) => {
            expect($h2.eq(0), 'h2 First Title')
                .to.contain('How It Works')
            expect($h2.eq(1), 'h2 Second Title')
                .to.contain('Serious About Security')
            expect($h2.eq(2), 'h2 Second Title')
                .to.contain('Got a question?')
        })

        cy.get('h3').should(($h3) => {
            expect($h3.eq(0), 'H3 First Title')
                .to.contain('How do I get started?')
            expect($h3.eq(1), 'H3 Second Title')
                .to.contain('How much can I earn?')
            expect($h3.eq(2), 'H3 Third Title')
                .to.contain('Where do my rewards go?')
            expect($h3.eq(3), 'H3 Third Title')
                .to.contain('What if I need support?')
        }) 

        cy.get('h4').should(($h4) => {
            expect($h4.eq(0), 'h4 First title text')
                .to.contain("Earn Even More Rewards")
            expect($h4.eq(1), 'h4 Second title text')
                .to.contain("Encrypted")
            expect($h4.eq(2), 'h4 Third title text')
                .to.contain("Access Control")
            expect($h4.eq(3), 'h4 Fourth title text')
                .to.contain("Audited Code")
            expect($h4.eq(4), 'h4 Fifth title text')
                .to.contain("Asset Protection")
        })

        cy.get('h5').should(($h5) => {
            expect($h5.eq(0), 'First title text')
                .to.contain("Give Node™ makes mining and earning digital rewards easy for anyone with a computer.")
            expect($h5.eq(1), 'Second title text')
                .to.contain("Give Node makes it easy to earn digital rewards like a pro.")
            expect($h5.eq(2), 'Third title text')
                .to.contain("Purchase Smart Node")
            expect($h5.eq(3), 'Fourth title text')
                .to.contain("Intelligent Mining")
            expect($h5.eq(4), 'Fifth title text')
                .to.contain("Consistent Activity")
            expect($h5.eq(5), 'Sixth title text')
                .to.contain("Your security and anonymity is our highest priority. Give Node is setting the highest standard for blockchain mining security.")
        }) 

        cy.get('h6').should(($h6) => {
            expect($h6.eq(0), 'First card title text')
                .to.contain("STEP ONE")
            expect($h6.eq(1), 'Second card title text')
                .to.contain("STEP TWO")
            expect($h6.eq(2), 'Third card title text')
                .to.contain("STEP THREE")
        })

        cy.get('p').should(($features_para) => {
            expect($features_para.eq(0), 'First paragraph text')
                .to.contain("Give Node gives anyone easy access to sophisticated mining software. Imagine earning meaningful passive income just by having your computer turned on, all while taking part in the blockchain revolution.")
            expect($features_para.eq(1), 'Second paragraph text')
                .to.contain("Purchase Give Node and select the number of licenses you would like to activate.")
            expect($features_para.eq(2), 'Third paragraph text')
                .to.contain("Install and activate your licenses on your selected devices. Node begins mining in three simple steps.")
            expect($features_para.eq(3), 'Fourth paragraph text')
                .to.contain("Maximize your rewards by consistently running Give Node software.")
            expect($features_para.eq(4), 'Fifth paragraph text')
                .to.contain("Maximize Give by operating more node licenses.")
        })

        cy.get('[class="nectar-button large regular accent-color  regular-button"]').should(($button) => {
            expect($button.eq(0), 'First button text')
                .to.contain("BUY GIVE SMART NODE")
                .to.have.attr('href', '/register-node/')
            expect($button.eq(1), 'Second button text')
                .to.contain("BUY GIVE SMART NODE")
                .to.have.attr('href', '/register-node/')
            expect($button.eq(2), 'Second button text')
                .to.contain("SELECT YOUR BUNDLE")  
                .to.have.attr('href', '/register-node/')
            expect($button.eq(3), 'Second button text')
                .to.contain("I AM READY - LET'S DO THIS") 
                .to.have.attr('href', '/register-node/')       
        }) 

        cy.get('#wpforms-submit-9937').should(($button) => {
            expect($button.eq(0), 'Second button text')
                .to.contain("Submit")
        })

        cy.get('[class="wpforms-field-label"]').should(($button) => {
            expect($button.eq(0), 'First button text')
                .to.contain("Submit a Question ")
            expect($button.eq(1), 'Second button text')
                .to.contain("Email ")
        })
    })

    it('Expecting/Asserting the text questions', () => {
        cy.get('h3')
            .eq(0)
            .click()
        cy.get('p')
            .eq(5)
            .should('have.text', "It’s easy! Just purchase Give Node. Install the software on the device of your choice. Any computer will do. Activate your license and then just make sure your software is running consistently. The more it runs—the more rewards you earn.")
        cy.get('h3')
            .eq(1)
            .click()
        cy.get('p')
            .eq(6)
            .should('have.text', "It depends. You can earn up to $1-3 a day per license. There are a variety of determining factors including fluctuations in the market value and the number of consistent hours you operate your Give Node. These factors all play a part in the earning potential of your device.")
        cy.get('h3')
            .eq(2)
            .click()
        cy.get('p')
            .eq(7)
            .should('have.text', "Digital rewards are deposited into your Give App. You can manage, store, convert and send from your Give App anytime.")
            cy.get('h3')
            .eq(2)
            .click()
        cy.get('p')
            .eq(8)
            .should('have.text', "No worries. Our community is always here to help. We are decentralized, so you can get help no matter where you are.")
    })
})