/// <reference types="cypress" />

// When a customer is logged out

describe('Login', () => {
    beforeEach(() => {
        cy.wordpresslogin(Cypress.env('email'), Cypress.env('password'));
        cy.visit("https://giveblockchain.io/love/")
        cy.url()
            .should("include", "/love/")
    })

    it('Expecting/Asserting all text on the page', () => {
        cy.get('h1').should(($h1) => {
            expect($h1.eq(0), 'h1 First Title')
                .to.contain("We Love to Give")
        }) 

        cy.get('h2').should(($h2) => {
            expect($h2.eq(0), 'h2 First Title')
                .to.contain('Annual Give Impact')
            expect($h2.eq(1), 'h2 Second Title')
                .to.contain('2022 Goals')
        }) 

        cy.get('h4').should(($h4) => {
            expect($h4.eq(0), 'h4 First title text')
                .to.contain("Give")
            expect($h4.eq(1), 'h4 Second title text')
                .to.contain("Donations")
            expect($h4.eq(2), 'h4 Third title text')
                .to.contain("Members")
            expect($h4.eq(3), 'h4 Fourth title text')
                .to.contain("Charities")
            expect($h4.eq(4), 'h4 Fifth title text')
                .to.contain("Nodes")
            expect($h4.eq(5), 'h4 Sixth title text')
                .to.contain("Stories")
        })

        cy.get('h5').should(($h5) => {
            expect($h5, 'h5 First Title')
                .to.contain("All of us doing something small is better than a few people trying to do it all.")
        })

        cy.get('p').should(($paragraph) => {
            expect($paragraph.eq(0), 'First paragraph text')
                .to.contain("Raise 5 billion dollars through Give.")
            expect($paragraph.eq(1), 'Second paragraph text')
                .to.contain("Receive 50k donations.")
            expect($paragraph.eq(2), 'Third paragraph text')
                .to.contain("Grow our platform to 20k followers.")
            expect($paragraph.eq(3), 'Fourth paragraph text')
                .to.contain("Support 10 charities.")
            expect($paragraph.eq(4), 'Fifth paragraph text')
                .to.contain("Sell 1000 nodes.")
            expect($paragraph.eq(5), 'Sixth paragraph text')
                .to.contain("Share the impact Give’s community makes.")
        })
    })

    it('Expecting/Asserting the "Give Impact" Section: Save', () => {
        cy.get('h5').should(($h5) => {
            expect($h5.eq(0), 'h5 First Title')
                .to.contain("53")
            expect($h5.eq(1), 'h5 Second Title')
                .to.contain("survivors reunited with their families")
            expect($h5.eq(2), 'h5 Third Title')
                .to.contain("50")
            expect($h5.eq(3), 'h5 Fourth Title')
                .to.contain("survivors receive aftercare services")
            expect($h5.eq(4), 'h5 Fifth Title')
                .to.contain("45")
            expect($h5.eq(5), 'h5 Sixth Title')
                .to.contain("survivors receive legal training")
            expect($h5.eq(6), 'h5 Seventh Title')
                .to.contain("43")
            expect($h5.eq(7), 'h5 Eigth Title')
                .to.contain("victims rescued from a situation of sexual exploitation")
            expect($h5.eq(8), 'h5 Ninth Title')
                .to.contain("25")
            expect($h5.eq(9), 'h5 Tenth Title')
                .to.contain("investigations executed")
            expect($h5.eq(10), 'h5 Eleventh Title')
                .to.contain("20")
            expect($h5.eq(11), 'h5 Twelth Title')
                .to.contain("watchdogs trained to report cases of sexual exploitation")
        })
    })

    it('Expecting/Asserting the "Give Impact" Section: Water', () => {
        cy.get('.wpb_tabs_nav > :nth-child(2) > a').click()
        cy.get('h5').should(($h5) => {
            expect($h5.eq(12), 'h5 First Title')
                .to.contain("10")
            expect($h5.eq(13), 'h5 Second Title')
                .to.contain("new WhoLives drills going up in different countries")
            expect($h5.eq(14), 'h5 Third Title')
                .to.contain("1")
            expect($h5.eq(15), 'h5 Fourth Title')
                .to.contain("working well in Kenya")
            expect($h5.eq(16), 'h5 Fifth Title')
                .to.contain("1")
            expect($h5.eq(17), 'h5 Sixth Title')
                .to.contain("working well in Tanzania")
        })
    })

    it('Expecting/Asserting the "Give Impact" Section: Humanitarian', () => {
        cy.get('.wpb_tabs_nav > :nth-child(3) > a').click()
        cy.get('h5').should(($h5) => {
            expect($h5.eq(18), 'h5 First Title')
                .to.contain("60")
            expect($h5.eq(19), 'h5 Second Title')
                .to.contain("computers donated through Pathways college")
            expect($h5.eq(20), 'h5 Third Title')
                .to.contain("3")
            expect($h5.eq(21), 'h5 Fourth Title')
                .to.contain("scholarships to Peru")
            expect($h5.eq(22), 'h5 Fifth Title')
                .to.contain("2")
            expect($h5.eq(23), 'h5 Sixth Title')
                .to.contain("orphanage classrooms put up")
            expect($h5.eq(24), 'h5 Fifth Title')
                .to.contain("1")
            expect($h5.eq(25), 'h5 Sixth Title')
                .to.contain("hospital bed donated")
            expect($h5.eq(26), 'h5 Fifth Title')
                .to.contain("1")
            expect($h5.eq(27), 'h5 Fifth Title')
                .to.contain("WhoLives drill built")
            expect($h5.eq(28), 'h5 Fifth Title')
                .to.contain("")
            expect($h5.eq(29), 'h5 Fifth Title')
                .to.contain("medical kits to help deliver babies")
        })
    })

    it('Expecting/Asserting the "Give Impact" Section: Give', () => {
        cy.get('.wpb_tabs_nav > :nth-child(4) > a').click()
        cy.get('h5').should(($h5) => {
            expect($h5.eq(30), 'h5 First Title')
                .to.contain("2000")
            expect($h5.eq(31), 'h5 Second Title')
                .to.contain("Afghanistan people provided housing and life support.")
            expect($h5.eq(32), 'h5 Third Title')
                .to.contain("36")
            expect($h5.eq(33), 'h5 Fourth Title')
                .to.contain("tons of medical supplies were delivered to care for Ukrainians affected by this terrible conflict")
            expect($h5.eq(34), 'h5 Fifth Title')
                .to.contain("1")
            expect($h5.eq(35), 'h5 Sixth Title')
                .to.contain("Ukrainian citizen and developer for Gala Games who was under extreme risk was evacuated to a safe location in Western Europe")
            expect($h5.eq(36), 'h5 Fifth Title')
                .to.contain("1")
            expect($h5.eq(37), 'h5 Sixth Title')
                .to.contain("highly effective relief coordination center in a nearby nation established")
            expect($h5.eq(38), 'h5 Fifth Title')
                .to.contain("1")
            expect($h5.eq(39), 'h5 Fifth Title')
                .to.contain("modern underground railroad established for safe evacuation of displaced persons (this infrastructure will be used for some time)")
            expect($h5.eq(40), 'h5 Fifth Title')
                .to.contain("")
            expect($h5.eq(41), 'h5 Fifth Title')
                .to.contain("flights were funded for highly specialized aid workers from the US to Europe")
            expect($h5.eq(42), 'h5 Fifth Title')
                .to.contain("")
            expect($h5.eq(43), 'h5 Fifth Title')
                .to.contain("assisted in the procurement of safe, discreet local vehicles to deliver supplies to people who need them")
        })
    })
})