/// <reference types="cypress" />

describe('Login', () => {
    beforeEach(() => {
        cy.login(Cypress.env('email'), Cypress.env('password'));
        cy.get('[type="button"]')
            .eq(2)
            .click()
        cy.wait(1000)
      })

    // it('Document Test - iPhone-8-portrait', () => {
    //     cy.viewport('iphone-8', 'portrait')
    //     cy.prices_coin_mobile('Bitcoin', "Bitcoin test: ")
    //     cy.url().should('include', '/prices/BTC')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "Bitcoin")
    //     cy.get('.d-flex > .v-icon').click()

    //     cy.prices_coin_mobile('Ethereum')
    //     cy.url().should('include', '/prices/ETH')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "Ethereum")
    //     cy.get('.d-flex > .v-icon').click()

    //     cy.prices_coin_mobile('XRP')
    //     cy.url().should('include', '/prices/XRP')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "XRP")
    //     cy.get('.d-flex > .v-icon').click()

    //     cy.prices_coin_mobile('Bitcoin Cash')
    //     cy.url().should('include', '/prices/BCH')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "Bitcoin Cash")
    //     cy.get('.d-flex > .v-icon').click()

    //     cy.prices_coin_mobile('Litecoin')
    //     cy.url().should('include', '/prices/LTC')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "Litecoin")
    //     cy.get('.d-flex > .v-icon').click()

    //     cy.prices_coin_mobile('Cardano')
    //     cy.url().should('include', '/prices/ADA')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "Cardano")
    //     cy.get('.d-flex > .v-icon').click()

    //     cy.prices_coin_mobile('Gala')
    //     cy.url().should('include', '/prices/GALA')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "Gala")
    //     cy.get('.d-flex > .v-icon').click()

    //     cy.prices_coin_mobile('IOTA')
    //     cy.url().should('include', '/prices/MIOTA')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "IOTA")
    //     cy.get('.d-flex > .v-icon').click()

    //     cy.prices_coin_mobile('Dash')
    //     cy.url().should('include', '/prices/DASH')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "Dash")
    //     cy.get('.d-flex > .v-icon').click()

    //     cy.prices_coin_mobile('NEM')
    //     cy.url().should('include', '/prices/XEM')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "NEM")
    //     cy.get('.d-flex > .v-icon').click()
        
    //     cy.prices_coin_mobile('Monero')
    //     cy.url().should('include', '/prices/XMR')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "Monero")
    //     cy.get('.d-flex > .v-icon').click()

    //     cy.prices_coin_mobile('EOS')
    //     cy.url().should('include', '/prices/EOS')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "EOS")
    //     cy.get('.d-flex > .v-icon').click()
        
    //     cy.prices_coin_mobile('Bitcoin Gold')
    //     cy.url().should('include', '/prices/BTG')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "Bitcoin Gold")
    //     cy.get('.d-flex > .v-icon').click()

    //     cy.prices_coin_mobile('NEO')
    //     cy.url().should('include', '/prices/NEO')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "NEO")
    //     cy.get('.d-flex > .v-icon').click()

    //     cy.prices_coin_mobile('QTUM')
    //     cy.url().should('include', '/prices/QTUM')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "QTUM")
    //     cy.get('.d-flex > .v-icon').click()

    //     cy.prices_coin_mobile('Stellar')
    //     cy.url().should('include', '/prices/XLM')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "Stellar")
    //     cy.get('.d-flex > .v-icon').click()

    //     cy.prices_coin_mobile('Ethereum Classic')
    //     cy.url().should('include', '/prices/ETC')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "Ethereum Classic")
    //     cy.get('.d-flex > .v-icon').click()

    //     cy.prices_coin_mobile('Lisk')
    //     cy.url().should('include', '/prices/LSK')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "Lisk")
    //     cy.get('.d-flex > .v-icon').click()

    //     cy.prices_coin_mobile('TRON')
    //     cy.url().should('include', '/prices/TRX')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "TRON")
    //     cy.get('.d-flex > .v-icon').click()

    //     cy.prices_coin_mobile('Verge')
    //     cy.url().should('include', '/prices/XVG')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "Verge")
    //     cy.get('.d-flex > .v-icon').click()

    //     cy.prices_coin_mobile('ICON Project')
    //     cy.url().should('include', '/prices/ICX')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "ICON Project")
    //     cy.get('.d-flex > .v-icon').click()

    //     cy.prices_coin_mobile('ZCash')
    //     cy.url().should('include', '/prices/ZEC')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "ZCash")
    //     cy.get('.d-flex > .v-icon').click()

    //     cy.prices_coin_mobile('Ardor')
    //     cy.url().should('include', '/prices/ARDR')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "Ardor")
    //     cy.get('.d-flex > .v-icon').click()

    //     cy.prices_coin_mobile('OmiseGo')
    //     cy.url().should('include', '/prices/OMG')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "OmiseGo")
    //     cy.get('.d-flex > .v-icon').click()

    //     cy.prices_coin_mobile('Bitshares')
    //     cy.url().should('include', '/prices/BTS')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "Bitshares")
    //     cy.get('.d-flex > .v-icon').click()

    //     cy.prices_coin_mobile('Tether')
    //     cy.url().should('include', '/prices/USDT')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "Tether")
    //     cy.get('.d-flex > .v-icon').click()

    //     cy.prices_coin_mobile('Populous')
    //     cy.url().should('include', '/prices/PPT')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "Populous")
    //     cy.get('.d-flex > .v-icon').click()

    //     cy.prices_coin_mobile('Waves')
    //     cy.url().should('include', '/prices/WAVES')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "Waves")
    //     cy.get('.d-flex > .v-icon').click()

    //     cy.prices_coin_mobile('Nxt')
    //     cy.url().should('include', '/prices/NXT')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "Nxt")
    //     cy.get('.d-flex > .v-icon').click()

    //     cy.prices_coin_mobile('ByteCoin')
    //     cy.url().should('include', '/prices/BCN')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "ByteCoin")
    //     cy.get('.d-flex > .v-icon').click()
    // })

    // it('Document Test - iPhone-x-portrait', () => {
    //     cy.viewport('iphone-x', 'portrait')
    //     cy.prices_coin_mobile('Bitcoin', "Bitcoin test: ")
    //     cy.url().should('include', '/prices/BTC')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "Bitcoin")
    //     cy.get('.d-flex > .v-icon').click()

    //     cy.prices_coin_mobile('Ethereum')
    //     cy.url().should('include', '/prices/ETH')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "Ethereum")
    //     cy.get('.d-flex > .v-icon').click()

    //     cy.prices_coin_mobile('XRP')
    //     cy.url().should('include', '/prices/XRP')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "XRP")
    //     cy.get('.d-flex > .v-icon').click()

    //     cy.prices_coin_mobile('Bitcoin Cash')
    //     cy.url().should('include', '/prices/BCH')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "Bitcoin Cash")
    //     cy.get('.d-flex > .v-icon').click()

    //     cy.prices_coin_mobile('Litecoin')
    //     cy.url().should('include', '/prices/LTC')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "Litecoin")
    //     cy.get('.d-flex > .v-icon').click()

    //     cy.prices_coin_mobile('Cardano')
    //     cy.url().should('include', '/prices/ADA')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "Cardano")
    //     cy.get('.d-flex > .v-icon').click()

    //     cy.prices_coin_mobile('Gala')
    //     cy.url().should('include', '/prices/GALA')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "Gala")
    //     cy.get('.d-flex > .v-icon').click()

    //     cy.prices_coin_mobile('IOTA')
    //     cy.url().should('include', '/prices/MIOTA')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "IOTA")
    //     cy.get('.d-flex > .v-icon').click()

    //     cy.prices_coin_mobile('Dash')
    //     cy.url().should('include', '/prices/DASH')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "Dash")
    //     cy.get('.d-flex > .v-icon').click()

    //     cy.prices_coin_mobile('NEM')
    //     cy.url().should('include', '/prices/XEM')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "NEM")
    //     cy.get('.d-flex > .v-icon').click()
        
    //     cy.prices_coin_mobile('Monero')
    //     cy.url().should('include', '/prices/XMR')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "Monero")
    //     cy.get('.d-flex > .v-icon').click()

    //     cy.prices_coin_mobile('EOS')
    //     cy.url().should('include', '/prices/EOS')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "EOS")
    //     cy.get('.d-flex > .v-icon').click()
        
    //     cy.prices_coin_mobile('Bitcoin Gold')
    //     cy.url().should('include', '/prices/BTG')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "Bitcoin Gold")
    //     cy.get('.d-flex > .v-icon').click()

    //     cy.prices_coin_mobile('NEO')
    //     cy.url().should('include', '/prices/NEO')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "NEO")
    //     cy.get('.d-flex > .v-icon').click()

    //     cy.prices_coin_mobile('QTUM')
    //     cy.url().should('include', '/prices/QTUM')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "QTUM")
    //     cy.get('.d-flex > .v-icon').click()

    //     cy.prices_coin_mobile('Stellar')
    //     cy.url().should('include', '/prices/XLM')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "Stellar")
    //     cy.get('.d-flex > .v-icon').click()

    //     cy.prices_coin_mobile('Ethereum Classic')
    //     cy.url().should('include', '/prices/ETC')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "Ethereum Classic")
    //     cy.get('.d-flex > .v-icon').click()

    //     cy.prices_coin_mobile('Lisk')
    //     cy.url().should('include', '/prices/LSK')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "Lisk")
    //     cy.get('.d-flex > .v-icon').click()

    //     cy.prices_coin_mobile('TRON')
    //     cy.url().should('include', '/prices/TRX')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "TRON")
    //     cy.get('.d-flex > .v-icon').click()

    //     cy.prices_coin_mobile('Verge')
    //     cy.url().should('include', '/prices/XVG')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "Verge")
    //     cy.get('.d-flex > .v-icon').click()

    //     cy.prices_coin_mobile('ICON Project')
    //     cy.url().should('include', '/prices/ICX')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "ICON Project")
    //     cy.get('.d-flex > .v-icon').click()

    //     cy.prices_coin_mobile('ZCash')
    //     cy.url().should('include', '/prices/ZEC')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "ZCash")
    //     cy.get('.d-flex > .v-icon').click()

    //     cy.prices_coin_mobile('Ardor')
    //     cy.url().should('include', '/prices/ARDR')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "Ardor")
    //     cy.get('.d-flex > .v-icon').click()

    //     cy.prices_coin_mobile('OmiseGo')
    //     cy.url().should('include', '/prices/OMG')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "OmiseGo")
    //     cy.get('.d-flex > .v-icon').click()

    //     cy.prices_coin_mobile('Bitshares')
    //     cy.url().should('include', '/prices/BTS')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "Bitshares")
    //     cy.get('.d-flex > .v-icon').click()

    //     cy.prices_coin_mobile('Tether')
    //     cy.url().should('include', '/prices/USDT')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "Tether")
    //     cy.get('.d-flex > .v-icon').click()

    //     cy.prices_coin_mobile('Populous')
    //     cy.url().should('include', '/prices/PPT')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "Populous")
    //     cy.get('.d-flex > .v-icon').click()

    //     cy.prices_coin_mobile('Waves')
    //     cy.url().should('include', '/prices/WAVES')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "Waves")
    //     cy.get('.d-flex > .v-icon').click()

    //     cy.prices_coin_mobile('Nxt')
    //     cy.url().should('include', '/prices/NXT')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "Nxt")
    //     cy.get('[type="button"]').eq(0).click()

    //     cy.prices_coin_mobile('ByteCoin')
    //     cy.url().should('include', '/prices/BCN')
    //     cy.get('.offset-3 > .container > .row > :nth-child(2)')
    //         .should('have.text', "ByteCoin")
    //     cy.get('.d-flex > .v-icon').click()
        
    // })

    // it('Document Test - iPad-mini-landscape', () => {
    //     cy.viewport('ipad-mini', 'landscape')
    // })

    // it('Document Test - iPad-2-landscape', () => {
    //     cy.viewport('ipad-2', 'landscape')
       
    // })

    it('Document Test - SamsungS10-portrait', () => {
        cy.viewport('samsung-s10', 'portrait')
        cy.prices_coin_mobile('Bitcoin', "Bitcoin test: ")
        cy.url().should('include', '/prices/BTC')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Bitcoin")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Ethereum')
        cy.url().should('include', '/prices/ETH')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Ethereum")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('XRP')
        cy.url().should('include', '/prices/XRP')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "XRP")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Bitcoin Cash')
        cy.url().should('include', '/prices/BCH')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Bitcoin Cash")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Litecoin')
        cy.url().should('include', '/prices/LTC')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Litecoin")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Cardano')
        cy.url().should('include', '/prices/ADA')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Cardano")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Gala')
        cy.url().should('include', '/prices/GALA')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Gala")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('IOTA')
        cy.url().should('include', '/prices/MIOTA')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "IOTA")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Dash')
        cy.url().should('include', '/prices/DASH')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Dash")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('NEM')
        cy.url().should('include', '/prices/XEM')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "NEM")
        cy.get('.d-flex > .v-icon').click()
        
        cy.prices_coin_mobile('Monero')
        cy.url().should('include', '/prices/XMR')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Monero")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('EOS')
        cy.url().should('include', '/prices/EOS')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "EOS")
        cy.get('.d-flex > .v-icon').click()
        
        cy.prices_coin_mobile('Bitcoin Gold')
        cy.url().should('include', '/prices/BTG')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Bitcoin Gold")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('NEO')
        cy.url().should('include', '/prices/NEO')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "NEO")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('QTUM')
        cy.url().should('include', '/prices/QTUM')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "QTUM")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Stellar')
        cy.url().should('include', '/prices/XLM')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Stellar")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Ethereum Classic')
        cy.url().should('include', '/prices/ETC')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Ethereum Classic")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Lisk')
        cy.url().should('include', '/prices/LSK')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Lisk")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('TRON')
        cy.url().should('include', '/prices/TRX')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "TRON")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Verge')
        cy.url().should('include', '/prices/XVG')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Verge")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('ICON Project')
        cy.url().should('include', '/prices/ICX')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "ICON Project")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('ZCash')
        cy.url().should('include', '/prices/ZEC')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "ZCash")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Ardor')
        cy.url().should('include', '/prices/ARDR')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Ardor")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('OmiseGo')
        cy.url().should('include', '/prices/OMG')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "OmiseGo")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Bitshares')
        cy.url().should('include', '/prices/BTS')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Bitshares")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Tether')
        cy.url().should('include', '/prices/USDT')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Tether")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Populous')
        cy.url().should('include', '/prices/PPT')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Populous")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Waves')
        cy.url().should('include', '/prices/WAVES')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Waves")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Nxt')
        cy.url().should('include', '/prices/NXT')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Nxt")
        cy.get('[type="button"]').eq(0).click()

        cy.prices_coin_mobile('ByteCoin')
        cy.url().should('include', '/prices/BCN')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "ByteCoin")
        cy.get('.d-flex > .v-icon').click()
        
    })

    it('Document Test - Samsung-Note9-portrait', () => {
        cy.viewport('samsung-note9', 'portrait')
        cy.prices_coin_mobile('Bitcoin', "Bitcoin test: ")
        cy.url().should('include', '/prices/BTC')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Bitcoin")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Ethereum')
        cy.url().should('include', '/prices/ETH')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Ethereum")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('XRP')
        cy.url().should('include', '/prices/XRP')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "XRP")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Bitcoin Cash')
        cy.url().should('include', '/prices/BCH')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Bitcoin Cash")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Litecoin')
        cy.url().should('include', '/prices/LTC')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Litecoin")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Cardano')
        cy.url().should('include', '/prices/ADA')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Cardano")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Gala')
        cy.url().should('include', '/prices/GALA')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Gala")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('IOTA')
        cy.url().should('include', '/prices/MIOTA')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "IOTA")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Dash')
        cy.url().should('include', '/prices/DASH')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Dash")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('NEM')
        cy.url().should('include', '/prices/XEM')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "NEM")
        cy.get('.d-flex > .v-icon').click()
        
        cy.prices_coin_mobile('Monero')
        cy.url().should('include', '/prices/XMR')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Monero")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('EOS')
        cy.url().should('include', '/prices/EOS')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "EOS")
        cy.get('.d-flex > .v-icon').click()
        
        cy.prices_coin_mobile('Bitcoin Gold')
        cy.url().should('include', '/prices/BTG')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Bitcoin Gold")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('NEO')
        cy.url().should('include', '/prices/NEO')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "NEO")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('QTUM')
        cy.url().should('include', '/prices/QTUM')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "QTUM")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Stellar')
        cy.url().should('include', '/prices/XLM')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Stellar")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Ethereum Classic')
        cy.url().should('include', '/prices/ETC')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Ethereum Classic")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Lisk')
        cy.url().should('include', '/prices/LSK')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Lisk")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('TRON')
        cy.url().should('include', '/prices/TRX')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "TRON")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Verge')
        cy.url().should('include', '/prices/XVG')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Verge")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('ICON Project')
        cy.url().should('include', '/prices/ICX')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "ICON Project")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('ZCash')
        cy.url().should('include', '/prices/ZEC')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "ZCash")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Ardor')
        cy.url().should('include', '/prices/ARDR')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Ardor")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('OmiseGo')
        cy.url().should('include', '/prices/OMG')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "OmiseGo")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Bitshares')
        cy.url().should('include', '/prices/BTS')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Bitshares")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Tether')
        cy.url().should('include', '/prices/USDT')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Tether")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Populous')
        cy.url().should('include', '/prices/PPT')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Populous")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Waves')
        cy.url().should('include', '/prices/WAVES')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Waves")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Nxt')
        cy.url().should('include', '/prices/NXT')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Nxt")
        cy.get('[type="button"]').eq(0).click()

        cy.prices_coin_mobile('ByteCoin')
        cy.url().should('include', '/prices/BCN')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "ByteCoin")
        cy.get('.d-flex > .v-icon').click()
    })

    it('Document Test - iPhone12-portrait', () => {
        cy.viewport(390,844, 'portrait')
        cy.prices_coin_mobile('Bitcoin', "Bitcoin test: ")
        cy.url().should('include', '/prices/BTC')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Bitcoin")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Ethereum')
        cy.url().should('include', '/prices/ETH')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Ethereum")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('XRP')
        cy.url().should('include', '/prices/XRP')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "XRP")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Bitcoin Cash')
        cy.url().should('include', '/prices/BCH')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Bitcoin Cash")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Litecoin')
        cy.url().should('include', '/prices/LTC')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Litecoin")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Cardano')
        cy.url().should('include', '/prices/ADA')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Cardano")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Gala')
        cy.url().should('include', '/prices/GALA')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Gala")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('IOTA')
        cy.url().should('include', '/prices/MIOTA')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "IOTA")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Dash')
        cy.url().should('include', '/prices/DASH')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Dash")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('NEM')
        cy.url().should('include', '/prices/XEM')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "NEM")
        cy.get('.d-flex > .v-icon').click()
        
        cy.prices_coin_mobile('Monero')
        cy.url().should('include', '/prices/XMR')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Monero")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('EOS')
        cy.url().should('include', '/prices/EOS')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "EOS")
        cy.get('.d-flex > .v-icon').click()
        
        cy.prices_coin_mobile('Bitcoin Gold')
        cy.url().should('include', '/prices/BTG')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Bitcoin Gold")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('NEO')
        cy.url().should('include', '/prices/NEO')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "NEO")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('QTUM')
        cy.url().should('include', '/prices/QTUM')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "QTUM")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Stellar')
        cy.url().should('include', '/prices/XLM')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Stellar")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Ethereum Classic')
        cy.url().should('include', '/prices/ETC')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Ethereum Classic")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Lisk')
        cy.url().should('include', '/prices/LSK')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Lisk")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('TRON')
        cy.url().should('include', '/prices/TRX')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "TRON")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Verge')
        cy.url().should('include', '/prices/XVG')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Verge")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('ICON Project')
        cy.url().should('include', '/prices/ICX')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "ICON Project")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('ZCash')
        cy.url().should('include', '/prices/ZEC')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "ZCash")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Ardor')
        cy.url().should('include', '/prices/ARDR')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Ardor")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('OmiseGo')
        cy.url().should('include', '/prices/OMG')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "OmiseGo")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Bitshares')
        cy.url().should('include', '/prices/BTS')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Bitshares")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Tether')
        cy.url().should('include', '/prices/USDT')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Tether")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Populous')
        cy.url().should('include', '/prices/PPT')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Populous")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Waves')
        cy.url().should('include', '/prices/WAVES')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Waves")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Nxt')
        cy.url().should('include', '/prices/NXT')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Nxt")
        cy.get('[type="button"]').eq(0).click()

        cy.prices_coin_mobile('ByteCoin')
        cy.url().should('include', '/prices/BCN')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "ByteCoin")
        cy.get('.d-flex > .v-icon').click()
    })

    it('Document Test - iPhone12-Mini-portrait', () => {
        cy.viewport(390,780, 'portrait')
        cy.prices_coin_mobile('Bitcoin', "Bitcoin test: ")
        cy.url().should('include', '/prices/BTC')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Bitcoin")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Ethereum')
        cy.url().should('include', '/prices/ETH')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Ethereum")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('XRP')
        cy.url().should('include', '/prices/XRP')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "XRP")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Bitcoin Cash')
        cy.url().should('include', '/prices/BCH')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Bitcoin Cash")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Litecoin')
        cy.url().should('include', '/prices/LTC')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Litecoin")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Cardano')
        cy.url().should('include', '/prices/ADA')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Cardano")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Gala')
        cy.url().should('include', '/prices/GALA')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Gala")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('IOTA')
        cy.url().should('include', '/prices/MIOTA')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "IOTA")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Dash')
        cy.url().should('include', '/prices/DASH')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Dash")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('NEM')
        cy.url().should('include', '/prices/XEM')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "NEM")
        cy.get('.d-flex > .v-icon').click()
        
        cy.prices_coin_mobile('Monero')
        cy.url().should('include', '/prices/XMR')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Monero")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('EOS')
        cy.url().should('include', '/prices/EOS')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "EOS")
        cy.get('.d-flex > .v-icon').click()
        
        cy.prices_coin_mobile('Bitcoin Gold')
        cy.url().should('include', '/prices/BTG')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Bitcoin Gold")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('NEO')
        cy.url().should('include', '/prices/NEO')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "NEO")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('QTUM')
        cy.url().should('include', '/prices/QTUM')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "QTUM")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Stellar')
        cy.url().should('include', '/prices/XLM')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Stellar")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Ethereum Classic')
        cy.url().should('include', '/prices/ETC')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Ethereum Classic")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Lisk')
        cy.url().should('include', '/prices/LSK')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Lisk")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('TRON')
        cy.url().should('include', '/prices/TRX')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "TRON")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Verge')
        cy.url().should('include', '/prices/XVG')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Verge")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('ICON Project')
        cy.url().should('include', '/prices/ICX')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "ICON Project")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('ZCash')
        cy.url().should('include', '/prices/ZEC')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "ZCash")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Ardor')
        cy.url().should('include', '/prices/ARDR')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Ardor")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('OmiseGo')
        cy.url().should('include', '/prices/OMG')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "OmiseGo")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Bitshares')
        cy.url().should('include', '/prices/BTS')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Bitshares")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Tether')
        cy.url().should('include', '/prices/USDT')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Tether")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Populous')
        cy.url().should('include', '/prices/PPT')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Populous")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Waves')
        cy.url().should('include', '/prices/WAVES')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Waves")
        cy.get('.d-flex > .v-icon').click()

        cy.prices_coin_mobile('Nxt')
        cy.url().should('include', '/prices/NXT')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "Nxt")
        cy.get('[type="button"]').eq(0).click()

        cy.prices_coin_mobile('ByteCoin')
        cy.url().should('include', '/prices/BCN')
        cy.get('.offset-3 > .container > .row > :nth-child(2)')
            .should('have.text', "ByteCoin")
        cy.get('.d-flex > .v-icon').click()
    })

    // it('Document Test - iPad-Pro-landscape', () => {
    //     cy.viewport(1366,1024, 'landscape')
       
    // })

    // it('Document Test - iPad-Pro-portrait', () => {
    //     cy.viewport(1024,1366, 'portrait')
       
    // })
})